### ISSUE TITLE
Key exchange Tartine<->Tartine is not starting

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#100]
Reproduce :
- Open a new tartine client in a new clean browser. 
- log in and refuse all dialogs for restoring keys. You now have a new client with no keys.
- Request keys to be able to decrypt messages.

Expected : all open clients display a key exchange dialog.
Obtained : tchap v2 displays a key exchange dialog, but tartine does not.

Notes : 
 - in existing Tartine client, the new session is listed in "Where you're signed in", under "Unverified devices".
 - in new Tartine client, in Settings, Security, "Verify current session" does not offer key exchange between devices :  
![image](https://user-images.githubusercontent.com/911434/178502616-b234678b-26cf-45cb-b1aa-d4d09c8dec71.png)
Same screen in element offers the key exchange between devices :
![image](https://user-images.githubusercontent.com/911434/178502783-d7bd341a-ef8e-4f08-8eda-7ddca88eede8.png)

**Comment by estellecomment** [comment]
Note : this may be because none of my sessions were verified. We have to figure out if this is common or not.

**Comment by jdauphant** [comment]
We may need cross-signing enabled

**Comment by odelcroi** [comment]
Closing this issue as it does not happen with cross signing disabled, feel free to reopen if it happens again
