### ISSUE TITLE
Partage de géolocalisation : créer les pages FAQ

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-web-v4#1003]
Le partage de géolocalisation (en temps réel ou non) va bientôt être déployé.

il faut créer une page de FAQ par plateforme pour expliquer aux utilisateurs : 
- où trouver la fonctionnalité
- comment paramétrer les autorisations pour autoriser la fonctionnalité

**Comment by MarcWadai** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/helpdesk/articles/fr/0b78af5c-4cfa-4a35-ba19-8762b7e18423/
