### ISSUE TITLE
Notification panel : Untranslated new options

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#1005]
### Steps to reproduce

<img width="717" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/e3aaa57e-cf78-4a0e-9ce7-b2b0b48e2786">

### Will you send logs?

Yes

**Comment by MarcWadai** [comment]
I contributed directly in [localazy](https://localazy.com/p/element-web) with
- `settings.tac_only_notifications`:  "Montrer les notifications seulement dans le Centre d'Activité des Fils de discussion"
- `settings.showbold`: "Afficher toute l'activité dans la liste des salons (points ou nombre de messages non lus)"

We should then get the translations in future updates
