### ISSUE TITLE
Key exchange V2->Tartine : dialog doesn't close

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#101]
Reproduce :
- Open a new tartine client in a new clean browser. You also have an existing v2 client open.
- log in and refuse all dialogs for restoring keys. You now have a new client with no keys.
- Request keys to be able to decrypt messages. Existing v2 client displays the key exchande dialog
- Do the key exchange.

Expected : when exchange is finished, all dialogs close
Obtained : last dialog stays open with a wait spinner
![image](https://user-images.githubusercontent.com/911434/178503282-8c478a79-5091-4137-b135-75bd4b16d40a.png)

However, the key exchange has worked.

**Comment by odelcroi** [comment]
Can not be reproduced with current version. Closing for now
