### ISSUE TITLE
Study - Deactivate some notification events (ex power level) ?

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1010]
link to https://github.com/orgs/tchapgouv/projects/15/views/1?pane=issue&itemId=63711558

Check how we can manage notification
- power levels
- change of profile pics 
- ...to be completed 

Maybe we can add a new parameter in the notification setting in order to activate or deactivate those kind of notifications.

So for exemple before executing the script to update power levels to all rooms, we can notice the users that they can have the ability to deactivate those notifications if they want

**Comment by MarcWadai** [comment]
To get the list of pushrules for a user you can use this endpoint 
`GET /_matrix/client/v3/pushrules/`

I tried to disable an endpoint which at first seems to take care of rooms power_levels : 
`/_matrix/client/v3/pushrules/global/override/.m.rule.room.server_acl/enabled`
But without success.

--- 
Acutally i found out that most of the unread "bold" room magic is done on the client side, since before receiving the event, it is an encrypted message.

I tested and if we want the event to not trigger an unread room display (bold and moving up the list), we can add an exception really easily with a simple customisation (one line of code).
```typescript
// matrix-react-sdk/src/Unread.ts
export function eventTriggersUnreadCount(client: MatrixClient, ev: MatrixEvent): boolean {
 ...
    switch (ev.getType()) {
        ...
        case EventType.RoomPowerLevels:
        ...
            return false;
    }
  ...
}
```
The room is not display as unread anymore but we can still see which users changed power levels.

This still need to be tested more to see if we really don't receive a notification on other devices etc. @odelcroi What do you think ? Should we go this way ?

**Comment by odelcroi** [comment]
This is a nice way to explore how not to bother users with unnecessary unread count, does it also cover the annoying lines in forum : "this guy has changed its avatar?" or "this guy has changed its name?"

**Comment by odelcroi** [comment]
ticket produit https://github.com/tchapgouv/tchap-product/issues/144
