### ISSUE TITLE
Change UI colors to improve consistency with iOS and Android

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-web-v4#102]
### Your use case

Following the ticket in Tchap-Design ( https://github.com/tchapgouv/tchap-design/issues/93 ), here is a summary of the colors that should be changed

### Sidebars
- [x] Background of SpacePanel: 000091;
- [x] Glyph of SpacePanel (plus button, settings button): ffffff;
- [x] Background of LeftPanel: EDF1F7;
- [x] **Every** Avatar background (when profile picture is missing): 8F96A4;
![Screenshot 2022-07-12 at 15 37 51](https://user-images.githubusercontent.com/1255251/178503292-a44b24c8-4c23-4fab-9c71-10891de4498a.png)

### RoomView Timeline
- [x] Message author name: 000091;
- [x] When someone is cited in a message reply, it should appear like this
![Screenshot 2022-07-12 at 15 37 34](https://user-images.githubusercontent.com/1255251/178503231-10076529-ee5f-4505-ba94-47d8fe42e10b.png)
Or at least the user name should be black 3B3B3B; 
- [x] Quote left border: BABABA;
- [x] #544
- [x] Links in a message: 000091 
- [x] Link in Room header description: 7E7EC4;
That said, I'd get rid of the description in the header. That's too heavy visually

**Comment by areox-net** [comment]
As an extention of this ticket we should also change the following:

- [ ] All links and button should have the Tchap color: 000091 
(This should apply to all links and button, and color-underlined texts across the application)
- [ ] Change app icon with attached image icon.png (available in different sizes)

### LogIn page
- [ ] The app icon should also be updated here
- [ ] Replace the Element background image (lake.jpg) with the attached image tchap-bg.jpg
Note: this should be done twice, since Element uses this background for both the main container .mx_AuthPage and for mx_AuthPage_modalBlur for a blurred background effect
- [ ] Add background color to .mx_AuthHeader: EDF1F7;
- [ ] Get rid of the gradient background in the footer ("Propulsé par Matrix") and change the text color: 61708b

[Tchap-web-assets.zip](https://github.com/tchapgouv/tchap-web-v4/files/9100725/Tchap-web-assets.zip)

**Comment by jdauphant** [comment]
tchap-bg.jpg is 3.2mo, do you have SVG version or light png ?

**Comment by areox-net** [comment]
Sorry, forgot to optimize after figma export. here you go 

![tchap-bg](https://user-images.githubusercontent.com/1255251/179397698-90cbed7e-25d6-4711-9250-f0cf6c016a65.svg)
![tchap-bg](https://user-images.githubusercontent.com/1255251/179397702-4244aa70-3a1b-4321-bdfe-ce6454c33922.jpg)

**Comment by odelcroi** [comment]
@areox-net  Pourrait-on faire une update sur cette liste de tache? Les taches les plus importantes pourraient avoir une issue dédiée.

**Comment by areox-net** [comment]
@odelcroi Desormais ce ticket est obsolete. Il y a plutot un travail de coherence à faire sur mobile.
Je prévois un check complet et on fera un nouveau ticket macro, avec des sous-taches.
