### ISSUE TITLE
Element Web spams homeserver with unnecessary requests

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#1024]
Detected issues on two homeservers : social and finance

A new version of Element Web send lots of unnecessary requests to homeserver. CPU is 120% and does not go down until restart.

Users of those homeserver do not seem to be much impacted though.

Tchap Web does not face this bug

New version of Element Web should fix the problem : 
https://github.com/matrix-org/matrix-js-sdk/pull/4216
https://github.com/matrix-org/matrix-js-sdk/releases/tag/v33.0.0

related issue : 
https://github.com/tchapgouv/tchap-web-v4/issues/901
https://github.com/element-hq/element-web/issues/27165#issuecomment-2129299940

**Comment by MarcWadai** [comment]
This issue was introduced in element 1.11.67 and should be fixed in 1.11.68
It was not impacted us because we didn't activate rust crypto yet.

**Comment by odelcroi** [comment]
@MatMaul @pseudonyme21 is this issue closed from your perspective? Are the server spammed still?
