### ISSUE TITLE
Impossible de supprimer un administrateur dans un salon

### ISSUE THREAD

**Issue by MBR0001** [tchapgouv/tchap-web-v4#1025]
### Steps to reproduce

Bonjour,

Un consultant externe a terminé sa mission et quitté le ministère des finances. 
A son départ, il était toujours administrateur d'un salon.
D'autres personnes sont aussi administrateur de ce salon.

1) Nous avons besoin de supprimer ce consultant de la liste des administrateur du salon.
2) Le consultant a du conserver une version de tchap (avec ses clés) sur son téléphone portable,
et peux toujours accéder aux informations des salons, ce qui constitue une faille sécurité.
Comment faire pour invalider les clés de cet utilisateur ?

Merci pour vos réponses à venir.

### Will you send logs?

Yes

**Comment by MarcWadai** [comment]
Bonjour,
Pour la demande de suppression de compte, je vous pris d'envoyer un mail au support : support@tchap.beta.gouv.fr 
Merci et bonne journée,

**Comment by MBR0001** [comment]
Bonjour,

Merci pour ce retour. Je viens d'adresser un mail à l'adresse indiquée.
