### ISSUE TITLE
Difficulties to download some files 

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1029]
## Description 
Multiple reports of difficulties to download a file. At the end sometimes it works using another browser or in private navigation modes. This problem was brought up by people using Edge and Mozilla.

From one exemple that I got with a user : 
- Click the file and wait
- Nothing happens exept a timeout, you can click multiple times and nothing will happen either
- In the console no errors are thrown, and the file seems to be well fetched from the backend 

Here are the network logs from the moment the user click on the file. We can see that future request are also going out after some times 

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/2c00d04e-cc0d-4abe-ae42-ad1d26e3ab68)

The request to download the file is well formed and we have in the response the data for the file. But it is not displayed
 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/40fd231d-f28e-45ef-8678-d181b99d901c)

## Steps to reproduce 
No idea

**Comment by MarcWadai** [comment]
On the frontend multiple files are related to the display of the file : 
- The button on which we click DownloadActionButton.tsx
- The eventTile that display the message as a media message EventTile.tsx on the timeline 

```
// Our component structure for EventTiles on the timeline is:
//
// .-EventTile------------------------------------------------.
// | MemberAvatar (SenderProfile)                   TimeStamp |
// |    .-{Message,Textual}Event---------------. Read Avatars |
// |    |   .-MFooBody-------------------.     |              |
// |    |   |  (only if MessageEvent)    |     |              |
// |    |   '----------------------------'     |              |
// |    '--------------------------------------'              |
// '----------------------------------------------------------'
```

The hypothesis is that the file is well received but didn't display and trigger the browser download eventhough the data was received from the backend.
The message received is well decrypted as a media file because we have the correct display, but it is later in the process that we are missing an information about it.

- Another important file is MFilebod.tsx which contains most of thelogic to decrypt the file content. Here below are some interesting information of how its done : 
```
 But attachments with end-to-end encryption are more difficult to handle.
 We need to decrypt the attachment on the client and then display it.
 To display the attachment we need to turn the decrypted bytes into a URL.

 There are two ways to turn bytes into URLs, data URL and blob URLs.
 Data URLs aren't suitable for downloading a file because Chrome has a
 2MB limit on the size of URLs that can be viewed in the browser or
 downloaded. This limit does not seem to apply when the url is used as
 the source attribute of an image tag.

 Blob URLs are generated using window.URL.createObjectURL and unfortunately
 for our purposes they inherit the origin of the page that created them.
 This means that any scripts that run when the URL is viewed will be able
 to access local storage.

 The easiest solution is to host the code that generates the blob URL on
 a different domain to the client.
 Another possibility is to generate the blob URL within a sandboxed iframe.
 The downside of using a second domain is that it complicates hosting,
 the downside of using a sandboxed iframe is that the browers are overly
 restrictive in what you are allowed to do with the generated URL.

/**
```

**Comment by jdauphant** [comment]
@MarcWadai Some users have problem with the setting "automatic download" isn't enabled in there browser.
I have help multiple users to setup correctly there browser.

In chrome like browser :
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/2af30756-96e2-47c6-8902-dc495c5e888a)
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/315f9888-3609-4276-944d-f7f611083b4f)
If this setting is not enable, you will have trouble to download files with Tchap Web.

**Comment by jdauphant** [comment]
> @MarcWadai Some users have problem with the setting "automatic download" isn't enabled in there browser. I have help multiple users to setup correctly there browser.
> 
> In chrome like browser : ![image](https://private-user-images.githubusercontent.com/1238254/339009335-2af30756-96e2-47c6-8902-dc495c5e888a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NDcsIm5iZiI6MTcxODIwODU0NywicGF0aCI6Ii8xMjM4MjU0LzMzOTAwOTMzNS0yYWYzMDc1Ni05NmUyLTQ3YzYtODkwMi1kYzQ5NWM1ZTg4OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTYwOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM1NmFlZDBhYTA5NTU1MGFkNTE4YjU0MDNkYjIzMGRmMzgxZjNmYjVlOTQ4MjgzM2ZiZmIyNDRiYzg2N2JhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rD7_0Q4AoGKJiCD8M5mduWnx3QVQBSt6LCB2ch84hFI) ![image](https://private-user-images.githubusercontent.com/1238254/339009496-315f9888-3609-4276-944d-f7f611083b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NDcsIm5iZiI6MTcxODIwODU0NywicGF0aCI6Ii8xMjM4MjU0LzMzOTAwOTQ5Ni0zMTVmOTg4OC0zNjA5LTQyNzYtOTQ0ZC1mN2Y2MTEwODNiNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTYwOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzliNTM5MmIyMmEwZmVmMTc1ZTMzNzUwYTQwNGIwZDkxNGFjOTIzZTk0ZmVkNjhhZWIzYTUzMGUxNDljY2RiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.etvx8X3vCIJQeGsfOMdBumskZlAVFqT6dEqbSI1juJs) If this setting is not enable, you will have trouble to download files with Tchap Web.

It not only cause for this problem

**Comment by jdauphant** [comment]
I have one case : 
- Some add the problem to download files fews days ago
- I have solve his problem by activate "automatic downloads" on his browser
- Today, he told me after the update, I had again problem to download files

**Comment by jdauphant** [comment]
I can see this erreur in the console (appear only once after the app is loaded)
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/d004b2ef-92ad-436e-b0a1-d8944bae1f85)

This problem was observed on 1 user that have a mac and chrome 126.

**Comment by MarcWadai** [comment]
Seems like this directive has been removed and should not be used. I opened a ticket on element side :arrow_up:

**Comment by MarcWadai** [comment]
- The difficulties to download file can also come from local cache problem. When switching from different web version. See https://github.com/tchapgouv/tchap-infra/issues/3023 -> ~~Should be solved soon~~ will be fixed by https://github.com/tchapgouv/tchap-infra/pull/3033
