### ISSUE TITLE
Géolocalisation: le fond du bloc s'affiche pas à la bonne couleur et le texte est en partie illisible

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-web-v4#1031]
### Steps to reproduce

Quand un utilisateur partage sa position dans un salon, le bloc affichant la carte n'est pas affché avec les bonnes couleurs.

#### What did you expect?
le bloc affichant la carte sur Tchap Web devrait respecter les couleurs du theme sélèctionné.

#### What happened instead?
Le bloc est sur fond noir en theme clair. La première ligne du texte est illisible car noire sur noir.
![Screenshot 2024-06-10 at 17 44 02](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/2b1ada92-f0fb-4a30-9238-dbc6f9e25a56)

Il passe en blanc en mode Sombre
![Screenshot 2024-06-10 at 17 43 51](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/c3b4e4f5-9657-44bc-a91d-c672c3afabe5)

Pour reference, sur iOS les couleurs ressembment à ça. Ce qui est l'apparence souhaitée.
![Screenshot 2024-06-10 at 17 49 12](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/1f2fe8f1-e0ed-4964-829d-07b417fa4c2a)

### URL for webapp

https://app-v4.prod.lab.tchap.incubateur.net

### Will you send logs?

No

**Comment by areox-net** [comment]
@odelcroi Si pas d'autres urgences sur web, ce fix me semble prioritaire pour un bon déploiement de la feature. Ton avis?

**Comment by odelcroi** [comment]
Yes, à mettre dans le sprint

**Comment by odelcroi** [comment]
est-ce que le bug que tu proposes c'est que un user Web partage sa position en direct? ca semble pas courant :)

**Comment by areox-net** [comment]
@odelcroi Non, c'est la visualisation sur Web, pas le partage depuis le Web

**Comment by MarcWadai** [comment]
Sur element nous avons le même comportement : 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/d7d702ce-9432-4d93-af88-5d6be9a5b191)
![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/c829f2ad-c080-439f-96a5-660930dc495b)

@areox-net  Donc il n'y a pas eu de problème côté changement de thème au niveau du code. Dans ce cas, je ne sais pas si ça vaut le coup de faire une customisations sur Tchap. Il faut je pense remonter la question vers les designers d'element.

**Comment by areox-net** [comment]
@MarcWadai Oui, dans ce cas il faut le pousser de leur coté. Je me demande si cela n'est pas une consequence du traitement de ce ticket, meme s'il est encore ouvert. https://github.com/element-hq/element-web/issues/22854

**Comment by areox-net** [comment]
@MarcWadai Je vais publier mon ticket chez eux

**Comment by areox-net** [comment]
Posté chez Element https://github.com/element-hq/element-web/issues/27571

**Comment by areox-net** [comment]
Corrigé chez Element https://github.com/matrix-org/matrix-react-sdk/pull/12629
