### ISSUE TITLE
The Thread Activity center is not using the correct tchap theme

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1035]
- the TAC button is a little gray -> should be white
- The pastilles are green ->is this the standard in tchap ?  
![Image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/2771aaf4-bd7a-4bca-95d2-30d3c6f148bb)

**Comment by MarcWadai** [comment]
@areox-net do you know if i need to change the color of the pastille to red ? or blue ? Because this green is the standard in element, but not in tchap. And Im not sure we have other pastille in the app (only black one for room notification)

**Comment by areox-net** [comment]
@MarcWadai I agree the icon should be white with a red dot
