### ISSUE TITLE
The "Gauffre" don't open in a new windows, this cause trouble with the PWA

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#1041]
## Problem

When I open the gauffre and clic on a link, Tchap is replaced by the website, this is very annoying when Tchap web is installed as PWA.

## Expected behaviour
When I clic on a link in the gauffre, the link is open in a new windows or tab (especially if Tchap is installed as PWA)

**Comment by MarcWadai** [comment]
A PR has been opened on la-suite side to change this behavior : https://github.com/numerique-gouv/lasuite-integration/pull/2
