### ISSUE TITLE
Notifications badge doesn't have the same color 

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1053]
Some notification badge kept the black color. For now we have : 

- TAC button color -> :red_circle: 
- Thread notification -> :red_circle: 
- sometimes previous thread notification ->  :black_circle: :shrug: 
- Room notification -> :black_circle: 
- DM notificaiton -> :black_circle: 

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/80a369cd-c874-451d-96b7-4eba6f9098a8)

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/33a3f63d-112d-4a94-a31c-99e9759807ba)

**Comment by MarcWadai** [comment]
@areox-net should we put everything in red ? or keep the badge dot of rooms and DM in black ? 

Maybe its a little weird if the dot is in red and text in black bold ? 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/29fc43f4-4cf4-4539-a8f1-e6b9f7f3e8af)

**Comment by areox-net** [comment]
@MarcWadai Usually for classic messages the red one means a mention. I think it's the same for threads. If that's the case, I think we should keep it black and red.
For other elements in the sidebar like Spaces and Favorites the pill is just white today.
![Screenshot 2024-06-26 at 09 49 27](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/d7715ba3-f057-41c1-9af8-e9f0dff405a4)

I think we should start from using a white dot for the threads icon too.
Of course this could be improved to make it more visible, but I think it's the point of the Element design:

- White or Black dot when it's a simple activity notification
- Colored dot when there is a mention (green in Element, Red in Tchap)

**Comment by MarcWadai** [comment]
@areox-net Ah yes i see ! 
In element looks like all thread notification are in green dot even without a mention :
![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/0a702f1c-74e4-4a24-b885-99d81037af8e)
 
Don't know if it was on purpose or not :shrug:

**Comment by areox-net** [comment]
@MarcWadai Are you sure these are not reply to a message of yours?

**Comment by MarcWadai** [comment]
@areox-net  Yes the thread shown above is from a public room in which I never talked haha

**Comment by MarcWadai** [comment]
I notice the same behavior on element, so i will close this ticket for now
