### ISSUE TITLE
Rendre disponible l'activation d'accès à un salon par lien

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-web-v4#1057]
Il est possible d'accéder à un salon privé par un simple lien web.

Mais cette option n'est activable que sur les clients mobiles de Tchap.

Il faut rendre cette option activable dans le client web.

cf FAQ : https://aide.tchap.beta.gouv.fr/fr/article/comment-inviter-des-participants-a-rejoindre-un-salon-web-5ln3jq/

**Comment by MarcWadai** [comment]
Test du comportement actuelle : 
- Lorsqu'on clique copier le lien d'un salon sur web et qu'on partage celui-ci
- L'utilisateur recevant le lien ne pourra pas le rejoindre (403) même si l'option accès par lien est activé sur le mobile
- En faisant l'action sur le mobile de décocher puis re-cocher l'option d'accès par lien
- L'utilisateur peut maintenant rejoindre par lien dans ce salon

**Comment by Delphgateau** [comment]
@MarcWadai c'est toujours le cas ? Je n'arrive pas à reproduire l'erreur 404.
En tous cas, est-ce qu'on peut prévoir d'activer la fonctionnalité "accès par lien sur web ? Etant donné que n'importe quel membre du salon peut ensuite envoyer le lien à qui il souhaite, l'admin perd le contrôle des invitations. Il faudrait ajouter un commentaire lorsqu'il active l'option pour le prévenir du genre "les membres du salon auront accès au lien et pourront le partager"

**Comment by MarcWadai** [comment]
Endroit du code de tchap-v2 contenant ce code : https://github.com/tchapgouv/tchap-web-v2/blob/5f0f5c478e382e2b714c2c75bd223c4a1a261a22/matrix-react-sdk/src/components/views/room_settings/RoomProfileSettings.js#L250
TLDR : 
- Création d'un alias
- Setup des joinrules en public pour cette alias 
- Affichage du lien

Dans element-web on ne trouve pas cette fonctionnalité.

**Comment by MarcWadai** [comment]
@Delphgateau @areox-net est-ce que ca vous va si je rajoute cette section ici ? Ou est-ce que vous avez d'autres idées.

![image](https://github.com/user-attachments/assets/57b9d16f-9649-4fab-9009-1839179b071d)

**Comment by Delphgateau** [comment]
Oui je trouve aussi que c'est le meilleur endroit pour mettre l'option.
Il y a un ticket en cours sur mobile à prendre en compte si possible : https://github.com/tchapgouv/tchap-android/issues/1112
