### ISSUE TITLE
Get inspiration from Tchap Web V3

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#106]
Some change can be retrieved from :
https://github.com/tchapgouv/tchap-web-v3/compare/master...develop
and here for matrix-react-sdk : 
https://github.com/tchapgouv/matrix-react-sdk-v3/compare/e70085ed2e14a74dc4f482645b89bbb82101de38...develop

Informations already extracted :
- https://github.com/tchapgouv/tchap-web-v4/issues/88#issuecomment-1189357892

**Comment by estellecomment** [comment]
Reading the whole v3 diff is difficult to understand and we will end up spending too much time on things that are not necessarily important.
However, when we know that we have to implement a feature, it will be useful to go see the v3 diff to learn from it.

**Comment by estellecomment** [comment]
@jdauphant ok to close ?

**Comment by jdauphant** [comment]
I have read quickly a quarter of it, I will read and extract what I found interesting, I may take me 1 or 2h.

**Comment by jdauphant** [comment]
Done with #88
