### ISSUE TITLE
Etudier la création des sous espace 

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1064]
Lorsqu'on est dans un espace, il y a la possibilité de créer un sous espace.

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/38633b91-bf11-4dec-99fb-af973b26af1a)

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/34a1e693-aca8-4492-8256-025dcb637f29)

Cette fonctionnalité est encore en beta chez Element. 

Si nous gardons cette fonctionnalité, il faudra aussi enlever l'option public de la liste et rajouter cette fonctionnalité dans la FAQ des espaces.

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/036b42fd-2c61-4721-b2e9-45776425a57b)

**Comment by MarcWadai** [comment]
@areox-net @julie-ri @Delphgateau quel est votre avis sur le sujet ?

**Comment by areox-net** [comment]
@MarcWadai J'allais t'en parler justement. Mon avis est qu'il faut cacher cette fonctionnalité chez nous, car trop de complexité. Je ne suis meme pas sur qu'elle va rester chez Element.

**Comment by julie-ri** [comment]
d'accord avec @areox-net , je propose qu'on valide cette décision au sync produit de cet aprem

**Comment by MarcWadai** [comment]
Les différents boutons pour créér des sous espaces seront retirer de l'UI https://github.com/tchapgouv/tchap-web-v4/issues/878
