### ISSUE TITLE
Création de compte: ajouter un message "ne pas fermer cette page" pendant le reset MDP

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-web-v4#1067]
En attendant de savoir si des améliorations sont prévues coté Element, l'équipe bizdev propose d'ajouter un message "Ne pas fermer cette page" à cette étape du reset MDP.

**Actuelle**
![Capture d’écran 2024-07-17 à 16 35 55](https://github.com/user-attachments/assets/d6a34a8d-732e-4e94-b708-ec9aa1bf5c2b)

**Souhaitée**
![Capture d’écran 2024-07-17 à 16 35 55](https://github.com/user-attachments/assets/420928f6-1dcb-4dc9-b7d2-c80accb4f5ec)

**Comment by areox-net** [comment]
@Raphaelrobert65 je te laisse regarder si tu as en tete un message ou formule.

**Comment by Raphaelrobert65** [comment]
Ça me semble très bien. En plus, en rouge, ça attire le regard, c'est top
