### ISSUE TITLE
à vérifier si c'est necessaire : lors de la création de la room, enlever l’option “rejoindre le salon pour les membres du space”

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#107]

**Comment by odelcroi** [comment]
Steps to reproduce : 

- create a {private, public }space
- create a {public, private, dm} room
- check that the option "rejoindre le salon pour les membres du space" is not active

**Comment by odelcroi** [comment]
nb : create a public space is not possible. It might be due to the version of synapse. 
`{"errcode":"M_UNKNOWN","error":"Invalid power levels content override"}`

**Comment by odelcroi** [comment]
As long as the room creation panel is custom, no option will be shown :   

![Capture d’écran 2022-07-15 à 14 19 22](https://user-images.githubusercontent.com/4077729/179221605-983e8558-423d-48b0-a19b-ae6a5249ce7b.png)


related issue : https://github.com/tchapgouv/tchap-design/issues/90

**Comment by jdauphant** [comment]
So we can close the issue ?
