### ISSUE TITLE
Exported keys file is called "element-keys.txt"

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#108]
![image](https://user-images.githubusercontent.com/911434/178779151-2c9c3659-27b8-4716-a82d-dede8db65575.png)

cles-tchap-<date>.txt would be better (check with design that "clés Tchap" is the word used in the UI for encryption keys)

**Comment by estellecomment** [comment]
Could be a good PR for element, it's here : https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx#L89

We could use SdkConfig.get().brand (example in Notifier.ts)
And localize it too, with the string `"%(brand)s-keys.txt" : "cles-%(brand)s.txt"`

**Comment by estellecomment** [comment]
@JDixmier : do you think this is confusing users ? Does it matter ?

**Comment by JDixmier** [comment]
I think it would be better, if possible, to have the file called "Clés Tchap", as suggested by Caro after her investigations with users
