### ISSUE TITLE
Lorsqu'un admin se rétrograde, il doit recevoir un message d'alerte

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-web-v4#1092]
### Your use case

L'utilisateur est prévenu lorsqu'il se rétrograde sur les clients mobiles et sur web, dans la section "personnes" -> cliquer sur le nom de la personne -> rétrograder : 
<img width="596" alt="image" src="https://github.com/user-attachments/assets/f4a641c6-9ca8-45dc-9458-0daa76a2bbfc">
On pourrait modifier le message pour plus de clarté : "Avant de retirer votre rôle d'administrateur, vérifiez qu'un autre administrateur est présent dans le salon. Sans cela, le salon ne pourra plus être géré. Notez que seul un administrateur pourra vous réattribuer ce rôle."

En revanche, il n'est pas alerter lorsqu'il se rétrograde depuis la section "rôle et permissions" des paramètres sur web : 
<img width="808" alt="image" src="https://github.com/user-attachments/assets/7a544efd-f2e6-4c19-bfe2-49af8358609d">

Il faudrait ajouter le message d'alerte

**Comment by MarcWadai** [comment]
En effet l'alerte n'est pas présente sur l'écran de paramètre. Je pense que c'est un oubli de la part d'element. Il faudrait ouvrir une PR chez eux pour le rajouter. (je le ferais après l'upgrade du merge avec react sdk du coup)

**Comment by MarcWadai** [comment]
L'issue a été crée chez element https://github.com/element-hq/element-web/issues/28547
