### ISSUE TITLE
Ajouter le lien de la FAQ lors de la création de l'espace

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#1095]
#### What would you like to do?

Ajouter un lien vers la FAQ pour éveiller les utilisateurs aux anomalies des espaces.

FAQ : https://aide.tchap.beta.gouv.fr/fr/article/comment-creer-un-espace-sur-tchap-1wmlenx/

par exemple ici : 
![image](https://github.com/user-attachments/assets/2401abb8-15b0-4c45-92d3-3f460f97f4f3)

**Comment by MarcWadai** [comment]
@odelcroi C'est déjà le cas avec le lien "En savoir plus". Est-ce que tu as une idée d'affichage différente ?

**Comment by odelcroi** [comment]
Closed by not les yeux en face des trous.
Well done :D
