### ISSUE TITLE
Problème de déchiffrement sur Chrome 128.0.6613.119

### ISSUE THREAD

**Issue by pseudonyme21** [tchapgouv/tchap-web-v4#1101]
**Constaté sur la version de TCHAP 4.7.0 et 4.6.1**

<img width="901" alt="Capture d’écran 2024-09-05 à 17 48 09" src="https://github.com/user-attachments/assets/78f2ff30-542c-4ad1-8ccf-a4a9fc82167d">

**après un** 

<img width="296" alt="Capture d’écran 2024-09-05 à 18 05 39" src="https://github.com/user-attachments/assets/cc1e02d0-d6ee-4d7f-adce-8a77e643bb65">

**résultat**

<img width="881" alt="Capture d’écran 2024-09-05 à 17 59 46" src="https://github.com/user-attachments/assets/ae74cba5-aff0-49b5-884d-6b86a213617a">

Précision 1 : aucun problème de déchiffrement sur mon IOS ou mon firefox du SPAN ( version 102.8.0esr)

Précision 2 : tous mes appareils sont vérifiés

 
<img width="680" alt="Capture d’écran 2024-09-05 à 17 50 15" src="https://github.com/user-attachments/assets/a9a0b4d6-31d4-4bec-8103-f6cd7a1acad8">

**Comment by MarcWadai** [comment]
@pseudonyme21 thx pour le ticket et l'explication.
- Dans la partie "Aide et à propos" des paramètres, pourrais-tu voir si tu es en crypto Rust ou Olm ? 
- Est-ce que le problème est apparu que sur cette session chrome, ou toutes les autres sessions chrome sont similaire ? 
- Est-ce que le problème est encore persistant ?

**Comment by MarcWadai** [comment]
Ce problème a été réglé à l'aide du code de récup :man_shrugging:
