### ISSUE TITLE
Changer le texte de la page d'avertissement de compatibilité du navigateur

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1104]
Depuis la 4.7.0, les utilisateurs avec des anciens navigateurs vont atterrir sur cette page. 
Il faudrait la rendre plus Tchap friendly :

- [ ] Changer l'icone
- [ ] Votre navigateur ne peut pas exécuter Tchap -> Votre navigateur n'est pas optimal pour l'utilisation de Tchap
- [ ] Changer le texte du bouton : Je souhaite tout de même utiliser Tchap avec ce navigateur
- [ ] Enlever le lien vers element

![image](https://github.com/user-attachments/assets/af4fbb97-466d-4971-9f98-32bacf1ea987)

**Comment by MarcWadai** [comment]
@areox-net @Delphgateau  qu'est ce que vous en pensez ? :)

**Comment by areox-net** [comment]
@MarcWadai Si tu as un screenshot c'est mieux, mais ce que je vois dans le commit me semble bien.

**Comment by MarcWadai** [comment]
@areox-net done, j'ai rajouté la capture sur la PR :)

**Comment by areox-net** [comment]
@Delphgateau Je sais pas ce que tu en penses, mais je me dis qu'on pourrait éviter la repetion de "Votre navigateur" dans les deux titres.

**Comment by Delphgateau** [comment]
Je pense qu'il faut parler de version de navigateur et pas seulement "navigateur", ça porte à confusion.
Du coup, je dirai "votre version de navigateur ne peut pas exécuter Tchap et "il faudrait "installer une nouvelle version" ou "accéder à une mise à jour de votre navigateur"
Il faudrait ajouter Edge le pauvre, c'est un des plus utilisé ;)
Et j'ai un doute sur Safari, on est sur que ça fonctionne ?
Et pour la couleur et la mise en page on peut un chouilla améliorer peut-être ? 
@angelo-martinovic @MarcWadai

**Comment by areox-net** [comment]
@MarcWadai En fait j'ai validé trop vite! Je pensais que tu avais pris en compte les retours de Delphine.
Par contre c'est bon pour Safari @Delphgateau.

Voici les bons textes:

# Ce navigateur ne supporte pas Tchap

## Tchap utilise des fonctionnalités avancées que ce navigateur ne prend pas en charge.

Pour une expérience optimale, veuillez installer une version récente de l'un des navigateurs suivants : Edge, Chrome, Firefox ou Safari.

Vous pouvez continuer d'utiliser ce navigateur, mais vous risquez de trouver que certaines fonctionnalités et/ou l'apparence de l'application sont incorrectes.

[Je souhaite tout de même continuer sur ce navigateur]

**Utiliser Tchap sur téléphone**
...

**Comment by julie-ri** [comment]
peut-être devrait-on ajouter une phrase qui dit à l'utilisateur que s'il n'a pas la main sur la version de son navigateur il peut continuer à utiliser cette version et ne pas hésiter à se rapprocher du service info de son ministère ? Ca permettra un peu de lobbying

**Comment by julie-ri** [comment]
J'enleverai "Ce navigateur ne supporte pas Tchap"
et je laisserais :


Tchap utilise des fonctionnalités avancées que ce navigateur ne prend pas en charge.

Pour une expérience optimale, veuillez installer une version récente de l'un des navigateurs suivants : Edge, Chrome, Firefox ou Safari. N'hésitez pas à vous rapprocher du service informatique de votre ministère ou organisation.

Vous pouvez continuer d'utiliser ce navigateur, mais vous risquez de trouver que certaines fonctionnalités et/ou l'apparence de l'application sont incorrectes.
