### ISSUE TITLE
Investigate : Room options allows changing public/private status of room

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#111]
edit : work to do

### What v2 options are
Rooms version : 1
for a private room : 
- Autoriser l’accès aux externes à ce salon  
- Activer l'accès au salon par lien 

for a private room with extern : 
- Activer l'accès au salon par lien 
- [activated] Autoriser l’accès aux externes à ce salon  (can not be changed)

for public rooms (forum : 
-  Retirer ce salon de l'annuaire des forums
- [activated] Activer l'accès au salon par lien (can not be changed)

### What should be done in v4 to stick to v2 behaviour
Rooms version : 1
for a private room remove the possibility to change : 
- [ ] Publier ce salon dans le répertoire de salons public (make no sense)
- [x] Accès> Membres de l’espace
- [x] Accès> Public

for a private room with externe remove the possibility to change  : 
- [ ] Publier ce salon dans le répertoire de salons public (make no sense)
- [x] Accès> Membres de l’espace
- [x] Accès> Public

for a public room remove the possibility to change : 
- [x] Chiffré (public room must not be not encrypted)
- [x] Accès> Membres de l’espace
- [x] Accès> Private
- [ ] Activer l’accès visiteur

### What should be added in v4 

for a private room
- [x] #169

----

Questions : 
- should be continue creating rooms with version 1 or upgrade to new room version? 

Initial ticket : 
In tartine, you can change a public room to private, and back again. 
In Tchap-style rooms, there are several settings that go together to define the type of the room. Not sure what happens if you change only public/private.

![Capture d’écran 2022-07-15 à 14 32 48](https://user-images.githubusercontent.com/4077729/179223846-985914f1-8e30-45fb-b487-fc7c41b37ae8.png)

**Comment by estellecomment** [comment]
Investigate : 
 - what changes are possible in v2 ? 
 - how would this break tchap-style rooms ?

**Comment by mcalinghee** [comment]
Perform testing around this feature on Dev environnement

**Comment by odelcroi** [comment]
-- moved to the issue body --
