### ISSUE TITLE
Activer la fonctionnalité Pinned Messages sur Web

### ISSUE THREAD

**Issue by julie-ri** [tchapgouv/tchap-web-v4#1115]
#### What would you like to do?
En tant qu'utilisateur j'aimerais pouvoir épingler un message  ou plusieurs dans des salons / forum ou MP si je suis administrateur ou modérateur uniquement
#### Why would you like to do it?
C'est une fonctionnalité très demandée par les users
#### How would you like to achieve it?
En activant cette fonctionnalité qui est présente sur Element Web
![image](https://github.com/user-attachments/assets/8bfb0139-0c59-4d76-9412-838d069810ae)

### Additional context

Attention il faut qu'on teste l'effet déceptif qui fait que les pinned messages ne seront pas déchiffrés pour les users qui sont ajoutés après le pinning. Soit on liasse comme ça soit on cherche une solution tech ?

**Comment by julie-ri** [comment]
https://spec.matrix.org/unstable/client-server-api/#mroompinned_events

**Comment by MarcWadai** [comment]
Présente dans la version 4.9.2 de Tchap
