### ISSUE TITLE
Investigate : Setting "Afficher tous les salons dans Accueil" is changeable in Settings

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#112]
Should we hide all mention of this ? 
Seen in : 
1. Settings>Preferences
![Capture d’écran 2022-07-15 à 14 28 48](https://user-images.githubusercontent.com/4077729/179223355-eca13bd3-ae4e-4c2c-b5a1-7285bd5fe267.png)

2. Settings>Barre latérale
![Capture d’écran 2022-07-15 à 14 31 30](https://user-images.githubusercontent.com/4077729/179223527-b70f445f-d1dd-4891-87e7-016d431ca26c.png)

**Comment by estellecomment** [comment]
Investigate : when a user has no spaces, can they break their UI with this setting ? 
(if it's vaguely confusing but doesn't break anything, it's fin for beta)

**Comment by jdauphant** [comment]
It's not a problem for me. It's confusing if you don't have space but we should leave it if we don't remove the spaces section.

**Comment by odelcroi** [comment]
I have no spaces on my account. Setting this option ON or OFF does not make any effect on my home page, we should be fine for beta. Removing the beta tag.

**Comment by odelcroi** [comment]
closing, not an issue
