### ISSUE TITLE
PC - impossible de supprimer son compte

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#1122]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/34447bec-18e8-42c7-be0f-ce014d5cb0db)

la fenetre ne s'ouvre pas

### Outcome

![image](https://github.com/user-attachments/assets/859388d0-9981-44bc-9e46-36ee94ca4df7)

### URL for webapp

https://app-v4.dev.tchap.incubateur.net/

### Will you send logs?

Yes

**Comment by MarcWadai** [comment]
Problème de conflit entre la traduction Tchap et l'existant. Quand on a des clés de traduction telles que `auth|sso|email`, mais qu'il existe la clé `auth|sso` (qui ne contient donc que 1 niveau de profondeur) -> cette valeur va être ignorer.

Ce problème va être réglé avec le commit https://github.com/tchapgouv/tchap-web-v4/pull/1124/commits/9982788a9ee4281f51d3d2cab4c2b92aec9b5c4f
