### ISSUE TITLE
PC - login alors que le serveur Synapse n'est pas configuré ProConnect

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#1123]
### Steps to reproduce

- se connecter à https://app-v4.dev.tchap.incubateur.net/ avec testeur@agent2.tchap.incubateur.net

(dev02 n'est pas configuré ProConnect)

#### What did you expect?
un gentil message d'erreur à cette étape : 
![image](https://github.com/user-attachments/assets/f00c048b-2e21-4268-9145-a3e5ead773e7)

@areox-net le figma, ne contient pas ce cas
https://www.figma.com/design/3qu9dfXgLomL6u04mpaTip/Tchap?node-id=4607-35712&node-type=frame&t=Fjqp2k3yIzC9ZPZT-0

#### What happened instead?
![Capture d’écran 2024-10-08 à 14 58 02](https://github.com/user-attachments/assets/6cc8425c-5679-4e42-9612-31d9b005c4b4)

### URL for webapp

https://app-v4.dev.tchap.incubateur.net/#/welcome

### Will you send logs?

Yes

**Comment by MarcWadai** [comment]
Est-ce qu'il y a un endpoint qui me permet de découvrir si le homeserver est configuré ou non ? Car une fois le flow PC est lancé il est difficile d'attraper l'erreur dans l'app à cause des redirections
