### ISSUE TITLE
Disable creating subspaces from existing spaces

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#113]
Found a path to create a space **from an existing space**. 
**EDIT : it is a subspace that is being created, not a new space**

> go into a space
> click on menu 
![Capture d’écran 2022-07-15 à 13 46 12](https://user-images.githubusercontent.com/4077729/179217122-d2c57a1a-f8de-4cca-8d6f-a3e2989516b2.png)
> click on "Add existing room"
![Capture d’écran 2022-07-15 à 13 48 48](https://user-images.githubusercontent.com/4077729/179217451-42cce499-7e0a-4f85-a36f-f661ea48cf17.png)
> click on "Adding spaces has moved"
![Capture d’écran 2022-07-15 à 13 47 44](https://user-images.githubusercontent.com/4077729/179217280-a07197de-217e-4bdc-ab65-849838477929.png)
A button displays : "Create a new space"

- [ ] Should it be considered as an issue as ? : https://github.com/matrix-org/matrix-react-sdk/pull/9002

_Originally posted by @odelcroi in https://github.com/tchapgouv/tchap-web-v4/issues/71#issuecomment-1185469846_

**Comment by estellecomment** [comment]
I don't see it in Tartine on prod backend : 

![Screen Shot 2022-07-18 at 12 44 25](https://user-images.githubusercontent.com/911434/179504502-506a5134-4c40-463d-bda4-64a37df783ff.png)
