### ISSUE TITLE
Ajouter un bouton "liste rouge" sur le client web

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-web-v4#1134]
La fonctionnalité "Inscrire mon compte sur liste rouge" est accessibles depuis les clients mobiles uniquement, il faudrait l'ajouter sur web.
-> Le module est suspendu mais va être réactivé prochainement
-> Il n'a jamais été accessible depuis web, on aimerait aligner les 3 clients

Où ? 
Section "Général" des paramètres, partie "Profil" ou "Compte", ton avis @areox-net ? (faudrait le mettre au même endroit que sur mobile may be)
Ticket Tchap web 2  : https://github.com/tchapgouv/tchap-web-v2/issues/188
![image](https://github.com/user-attachments/assets/db095a4e-6354-4740-9c36-0310df3fecf8)

**Comment by MarcWadai** [comment]
Ancien code pour la liste rouge sur tchap-v2 : https://github.com/tchapgouv/tchap-web-v2/blob/5f0f5c478e382e2b714c2c75bd223c4a1a261a22/matrix-react-sdk/src/components/views/settings/tabs/user/GeneralUserSettingsTab.js#L94

**Comment by areox-net** [comment]
Merci @MarcWadai . 
@Delphgateau je pense qu'on peut afficher cette fonction dans Réglages > Sécurité et vie privée > Avancé

**Comment by Delphgateau** [comment]
Yep @areox-net, sur android et iOS c'est dans la section Paramètres utilisateurs donc pas la même section. Pour guider les users c'est peut-être plus simple de faire pareil partout ?

**Comment by areox-net** [comment]
@Delphgateau Oui, tu as raison. Je ne pense pas que ça vaut la peine de la déplacer sur mobile. 
Mettons là dans Account meme sur Web. On la déplacera sur Tchap X si besoin.
