### ISSUE TITLE
Nouvelle modale pour insiter à renseigner le code de récupération

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#1139]
Sur element une nouvelle modale est mise à disposition lors d'une nouvelle connexion mais pas présente sur Tchap (à cause de certaine customisations).

Il faudrait aussi la rajouter sur Tchap :

![image](https://github.com/user-attachments/assets/dd5ab422-5ce9-4410-a192-aa67e2d8cf03)

**Comment by MarcWadai** [comment]
@Delphgateau @areox-net Est-ce que vous pensez que le wording est ok pour cette nouvelle modale ?

**Comment by areox-net** [comment]
@MarcWadai Cela apparait quand tu fermes la modale de Vérification?

Dans la modale précedente on dit actuellement:
`Vérifiez votre identité pour accéder aux messages verrouillés et prouver votre identité aux autres.
`

Je pense une traduction de cette phrase ça devrait aller.
`Sans vérification, vous risquez de ne pas pouvoir accéder à vos messages et prouver votre identité aux autres.
`

**Comment by MarcWadai** [comment]
Je viens de remarquer que dans le code cette partie a été enlever explicitement et que ce n'est pas une nouvelle modale. Je suppose que c'était dans une idée de simplifier le parcours utilisateurs.

Je pense que dans notre vision actuelle nous souhaitons insister et informer le plus possible sur le sujet de clé de récupération, donc de remettre cette modale.

**Comment by areox-net** [comment]
@MarcWadai Mais oui! J'avais pas capté en la voyant en anglais. On avait viré une étape pour que le parcours soit moins lourd.
