### ISSUE TITLE
Les liens des salons redirigent vers matrix

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-web-v4#114]
### Steps to reproduce

Sur web, Tartine :

1. Choisir un forum
2. Copier le lien du forum depuis les paramètres du forum
3. Le coller dans la barre de navigation

#### What did you expect?

Arriver dans le salon sur Tchap 

#### What happened instead?
![Capture d’écran 2022-07-18 à 14 41 58](https://user-images.githubusercontent.com/45665538/179517482-507a22bc-1297-4564-b627-0be3022f80f4.png)

![Capture d’écran 2022-07-18 à 14 42 09](https://user-images.githubusercontent.com/45665538/179517506-44b71973-5220-4d60-b19e-14c556f76978.png)

![Capture d’écran 2022-07-18 à 14 42 22](https://user-images.githubusercontent.com/45665538/179517528-80180cb1-85a0-4c07-8995-4258cc064194.png)

### Will you send logs?

No

**Comment by JDixmier** [comment]
A noter qu'il n'y a pas de problème quand je clique sur le même lien depuis mon mobile (iOS) : j'arrive bien sur le salon
Edit : ça fonctionne aussi sur web quand on partage le lien dans Tchap

**Comment by jdauphant** [comment]
@estellecomment @mcalinghee I think we should put it in the Bucheron release.
The PR is already made
