### ISSUE TITLE
Améliorer le visuel d'explication pour un externe voulant créer un salon privé

### ISSUE THREAD

**Issue by pseudonyme21** [tchapgouv/tchap-web-v4#1144]
<img width="773" alt="Capture d’écran 2023-09-14 à 10 41 40" src="https://github.com/tchapgouv/tchap-web-v4/assets/11921231/d54eeb31-6d40-4038-9579-28895472c6c4">

**Comment by Delphgateau** [comment]
Echec de création du salon

En tant qu'invité externe, vous n'avez pas la possibilité de créer un salon privé. 

@areox-net ok pour toi ?

**Comment by areox-net** [comment]
@Delphgateau Oui, ça me parait bien.
