### ISSUE TITLE
Bug dans la barre de recherche utilisateur.ices

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-web-v4#1179]
Depuis 3 jours, les recherches depuis la barre de recherche sautent. Cela fonctionne quand on tape une première lettre, qu'on attend un peu.

Problème corrigé chez element-web v1.11.87 : https://github.com/element-hq/element-web/issues/28657

**Comment by odelcroi** [comment]
j'ai le meme probleme

**Comment by MarcWadai** [comment]
fix avec https://github.com/tchapgouv/tchap-web-v4/issues/1180
