### ISSUE TITLE
Disable possiblity to publish a DM

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#123]
### Steps to reproduce

In settings of a DM, we can choose lot of strange option, like publish the DM :
![image](https://user-images.githubusercontent.com/1238254/180091317-4f1e134b-7de3-4fb6-8dc9-8d38ee36922d.png)

### Outcome

I was espected not to publish DM or change DM parameters

### Will you send logs?

No

**Comment by jdauphant** [comment]
We can also disable the possibility to leave a DM

**Comment by jdauphant** [comment]
Linked to #111

**Comment by odelcroi** [comment]
> 
We can also disable the possibility to leave a DM


@jdauphant  I wouldn't process this comment in this ticket, you could create another ticket if you think it is relevant
