### ISSUE TITLE
Room creation : setup by default is "historique visible par les membres depuis leur arrivée"

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-web-v4#126]
### Your use case

I think this setup is confusing. 
Could in be "depuis leur invitation" by default, as it is in Tchap V2 ? 

![Capture d’écran 2022-07-21 à 16 07 32](https://user-images.githubusercontent.com/45665538/180234258-01e6b36e-583e-4c6e-a625-8d5929be1865.png)

**Comment by jdauphant** [comment]
closed by #128
