### ISSUE TITLE
Improve Theme customization

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#130]
#### What would you like to do?
Having a way to customize CSS

#### Why would you like to do it?
To improve the design.

#### How would you like to achieve it?
I want to override https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/dark/css/dark.pcss
https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/light/css/light.pcs

And define our own css variables and fonts

**Comment by jdauphant** [comment]
@estellecomment @odelcroi cette PR rend autonome @areox-net pour modifier le théme est améliorer l'expérience.
On pourra en discuter pour que vous faites un avis technique sur le projet

**Comment by odelcroi** [comment]
Definitely interesting, let's investigate it after the beta

**Comment by odelcroi** [comment]
linked to #186, @jdauphant have you something in mind?

**Comment by odelcroi** [comment]
relates to #273

**Comment by estellecomment** [comment]
We now have tchap pcss files which we can use to define our themes. I think this fixes this issue. (reopen if not)

**Comment by jdauphant** [comment]
@estellecomment can we link the PR to this ticket ?

**Comment by jdauphant** [comment]
Found it !
Closed by #277
