### ISSUE TITLE
What do to with secure storage on Tartine

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#135]
### Your use case

This ticket is a placeholder to study what are the impacts of the secure storage activation on the backend. 

-> Tartine will start the secure storage process when users log in the first time

Should we disable it on the web client?
Should we study and improve the UI ?

**Comment by estellecomment** [comment]
Attempt to disable cross-signing : https://github.com/tchapgouv/tchap-web-v4/pull/188/files
This means the client will not use secure storage either (for the cross signing keys)

**Comment by estellecomment** [comment]
We don't want users to set up secure storage.
We don't want cross signing either, but it could also work if we use it.

**Comment by estellecomment** [comment]
Is there a flag to disable use of secure storage and cross signing ? 
@weeman1337 do you know ?

**Comment by weeman1337** [comment]
After a quick look into the settings I would say no.

Adding a config flag in the UI should be doable with reasonable effort https://github.com/vector-im/element-web/blob/develop/docs/config.md#ui-features

**Comment by odelcroi** [comment]
We should hide this part in the UI :
<img width="599" alt="Capture d’écran 2022-09-22 à 09 23 34" src="https://user-images.githubusercontent.com/4077729/191684124-7fc47ecf-164f-4273-b60d-7da375496d3b.png">

**Comment by odelcroi** [comment]
And this button "Start secure backup" while logging out : 

<img width="459" alt="Capture d’écran 2022-09-22 à 09 48 52" src="https://user-images.githubusercontent.com/4077729/191688933-70716552-d927-46fa-ac32-6cb78fbcc31c.png">

**Comment by estellecomment** [comment]
I am not getting this dialog any more, probably because we removed cross-signing.

**Comment by estellecomment** [comment]
Started a PR anyway : https://github.com/tchapgouv/tchap-web-v4/pull/208

**Comment by odelcroi** [comment]
I tested with a brand new user, I get the dialog, I think the PR is needed

**Comment by estellecomment** [comment]
PR merged.
All mentions of secure storage have been hidden (unless we find new ones later :) )
