### ISSUE TITLE
Submit debug log points to tchap-web

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#143]
### Problem
If an error occurs, the client offers you the possibility to submit the logs by creating an issue on the repo : vector-im/element-web
<img width="1208" alt="Screenshot 2022-08-31 at 14 43 53" src="https://user-images.githubusercontent.com/3725676/187687917-c186cbe1-192e-4e80-9360-07e3f2cec57c.png">

When clicking on "Submit logs", this pop up appears : 
<img width="798" alt="Screenshot 2022-08-31 at 14 44 28" src="https://user-images.githubusercontent.com/3725676/187688590-28655467-8581-41ff-964f-1a166ebf93f5.png">

By Clicking on "Send Logs" , it will direct you to vector-im/element-web

**How to reproduce to trigger this feature :**
It seems we need an error on the client side but I do not know to trigger it.

We have several option to deal this matter : 
1. we could make it point to : tchapgouv/tchap-web-v4
2. we disable this feature
3. we are ok with this and let create an issue on vector-im/element-web

**Comment by estellecomment** [comment]
I see the same error in the same channel, and so does Juliette. There's a broken event apparently.

**Comment by mcalinghee** [comment]
I am opening another issue for this as it is the underlying issue : https://github.com/tchapgouv/tchap-web-v4/issues/146

**Comment by estellecomment** [comment]
We patched BugReportDialog to send logs to tchap.
