### ISSUE TITLE
Migration vers Tartine : est-ce que je peux dechiffrer mes messages ? 

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#149]
J'ai déja un client v2.
Je commence un nouveau client Tartine. 
Est-ce que je peux bien déchiffrer mes messages sur mon nouvau client ?

**Comment by estellecomment** [comment]
Includes #101 et #103

**Comment by estellecomment** [comment]
Est-ce que je peux récupérer mes clés depuis le client android et iOS ? (en tant qu'utilisateur, je n'ai qu'un seul téléphone, android ou iOS, pas les deux)

**Comment by mcalinghee** [comment]
We already have identified issues concerning this topic
