### ISSUE TITLE
Register : create a new account with V2 screen flow

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#152]
### Your use case

In Tchap registration is customized :  
- username is created from email
- homeserver is chosen from email
- terms and condition of all identity servers must be approved automatically (to be able to be discovered)

### Have you considered any alternatives?

- Register workflow can be routed to existing screen from v2
- Same with login?

**Comment by estellecomment** [comment]
Note : when we implement register, we should check that external users cannot register before they have been invited. 
(it should be enforced by backend anyway)

**Comment by odelcroi** [comment]
When using v4, "this url leads to a blank page ? : https://www.tchap.gouv.fr/#/register"

**Comment by odelcroi** [comment]
Tchap uses /#/register (fragments), they are not sent to nginx, so we can not use it for redirection.
A new location can be created /create-account that will load v2 application via the cookie.

        location = /create-account {
                add_header Set-Cookie "split_test_version=version_current;Path=/;Max-Age=31540000;";
                return 302 https://{{ webapp_domain }}/?r=$msec#/register;
        }

The drawback is that new users will be onboarded with v2 because the cookie is set to "version_current" 👎 

@jdauphant @pli01

**Comment by odelcroi** [comment]
Another solution without cookie : 
```
        #force loading v2 version regardless of cookie
        location /v2 {
                alias $current_version_path;
                index index.html;
        }
        #create a redirection to register to v2 account register
        location = /nouveau-compte {
                return 301 "https://{{ webapp_domain }}/v2/#/register";
        }
```


https://github.com/tchapgouv/tchap-infra/pull/1470

**Comment by jdauphant** [comment]
We should go with a no cookie option.

**Comment by odelcroi** [comment]
Additionnaly to nginx configuration, we must override "sign-in" links in the register screen to direct users to V4 signin screens. 
https://github.com/tchapgouv/tchap-web/pull/327/files

**Comment by estellecomment** [comment]
registration is now merged
