### ISSUE TITLE
Settings : do not allow change of display name

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#153]
Currently the UI lets you edit your displayname :

<img width="484" alt="Screen Shot 2022-09-02 at 15 48 54" src="https://user-images.githubusercontent.com/911434/188160984-b2262beb-6f6e-4793-8679-4af4b714793f.png">

But the backend refuses the edit (which is good). This is confusing for the user.
Hide the editing completely.

**Comment by odelcroi** [comment]
NB : In my undestanding, the Edit Button is used also for the avatar image, double check this point

**Comment by Delphgateau** [comment]
Il y a une icône interdit 🚫 pour indiquer à l'utilisateur que la modification du display name n'est pas possible.
