### ISSUE TITLE
Settings : hide Spaces settings

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#154]
We don't allow spaces.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/911434/188165219-13ca5272-5443-43d7-8b68-8a1de7d45e79.png">

**Comment by estellecomment** [comment]
Also Sidebar menu : 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/911434/188165417-3cb4bce1-4089-48e4-85b3-c51f4dd38917.png">

**Comment by jdauphant** [comment]
@odelcroi Je pense qu'on peut supprimer ce ticket.

**Comment by odelcroi** [comment]
agreed.
