### ISSUE TITLE
Replying to a message with an image causes an error

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#159]
Post a message containing an image.
Click reply.
Crash : this.messageContent is not a function

https://github.com/matrix-org/matrix-react-sdk/blob/afb39d8d921ed537705c5a46ba27fb514ac522d4/src/components/views/messages/MImageReplyBody.tsx#L53

(related to our adding of ContentScanner ?)

**Comment by jdauphant** [comment]
### Steps to reproduce

Click "reply" on a image message


### Outcome

#### What did you expect?
I was expecting to be redirected to input message when click on reply

#### What happened instead?
Error message :
![image](https://user-images.githubusercontent.com/1238254/188635074-6a2b25bd-6465-48df-9f15-4671c6349fa1.png)


### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

No

**Comment by jdauphant** [comment]
Maybe linked problem : 
Can't read message that reply to image "Impossible de charger ce message ([m.room](http://m.room/).message) Envoyer les journaux"

![image](https://user-images.githubusercontent.com/1238254/188657783-27e92de2-977e-4884-8e4d-3b8332c17650.png)

**Comment by jdauphant** [comment]
> Maybe linked problem : Can't read message that reply to image "Impossible de charger ce message ([m.room](http://m.room/).message) Envoyer les journaux"
> 
> ![image](https://user-images.githubusercontent.com/1238254/188657783-27e92de2-977e-4884-8e4d-3b8332c17650.png)

Yes message in response of an image can't be showned

**Comment by estellecomment** [comment]
Signaled at least twice by users.

**Comment by estellecomment** [comment]
Probably because MImageReplyBody imports MImageBody, but with out ContentScanner setup, the code it actually imports is ContentScanningImageBody.
Then it tries to use the messageContent function, which is present normally on MImageBody, but not on ContentScannerImageBody. So it crashes.

One fix is to import the original version : in MImageReplyBody :
replace `import MImageBody from './MImageBody';`
by `import MImageBody from "../../../../../../src/components/views/messages/OriginalImageBody";`

This does fix the bug. But it means we are bypassing the content scanner for the thumbnail that's displayed in the reply to an image. So not sure it's the way to go.

**Comment by weeman1337** [comment]
I would suggest to implement a content scanning version of `MImageReplyBody` similar to the other `*Body` components.
