### ISSUE TITLE
Password policy : is tchap's policy more restrictive ?

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#181]
For example, passwords should have at least 8 chars, and a capital letter, or whatever.

Test this. 
Is it enforced in the backend ? Is there some extra work to do in the frontend ?

**Comment by giomfo** [comment]
The password policy is min length 8 with a minimum of 1 Uppercase , 1 Lowercase , 1 digit and 1 symbol
The server returns a weak pwd error if one of these constraints is missing
I think you don't need to change the code from the Element-web client on this point

**Comment by estellecomment** [comment]
it is enforced by backend, and it is tchap-specific.
