### ISSUE TITLE
Decrypted messages do not appear without user action

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#190]
Reproduce :
 - create new user, login in to android or v2 or iphone
 - send a message
 - log in to v4 (without cross-signing since #188 ) with same user. Message appears encrypted.
 -  Key exchange dialogs appear. Do the emoji exchange.

Expected : message becomes decrypted and readable.
Obtained : Message still appears encrypted. You need to reload the page, or click "resend request", for the decryption to be visible.

**Comment by weeman1337** [comment]
@estellecomment can you check if there are any console errors?
Directly after this happened, can you send the debug logs to me directly (Settings → Help → Send Debug Logs → Download)?

**Comment by weeman1337** [comment]
Upstream issue: https://github.com/vector-im/element-web/issues/23333

**Comment by weeman1337** [comment]
The upstream issue has been fixed. The change is available in latest `develop`. Can you give it a try?

**Comment by mcalinghee** [comment]
**Test - OK** 
1. Log in to iOS app
2. Send a message "Salut"
<img width="325" alt="img_2870 at 11 23 28" src="https://user-images.githubusercontent.com/3725676/205886958-11134f42-8ddf-4090-b90d-3e2a349bb9a2.PNG">
3. Log in to v4, the message appears encrypted (skip the verification process)
4. Try to verify the "iphone" device through the settings
<img width="765" alt="Screenshot 2022-12-06 at 11 23 28" src="https://user-images.githubusercontent.com/3725676/205886353-c1b801a9-6931-4f5c-89c6-1e8f1e86da1c.png">
5. Message appears clearly in v4 
<img width="183" alt="Screenshot 2022-12-06 at 11 23 58" src="https://user-images.githubusercontent.com/3725676/205886366-5fa7f36d-348b-4445-b786-0e2fe0f1f467.png">
