### ISSUE TITLE
Tchap web session will not exchange keys with iphone

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#202]
- user has an iphone 2.0.5 session (no other sessions)
- user starts Tartine session
 - Tartine requests keys from iphone 2.0.5.
→ KO. emoji exchange starts, then error on mobile : "la vérification a été annulée : motif unexpected message"

Edit : this does not happen every time. Sometimes it does work.

It was already a problem in web v2 (reproduced)

**Comment by mcalinghee** [comment]
the verification request seems to be sent to v4 but the iphone 2.0.5 does not seems to receive or to handle the request (cf. logs from v4 that seems to send the event)
```
Requesting keys for !PpyQAloFaIemKVNBFb:agent.dinum.tchap.gouv.fr / FWJyaBi3ZMtO/bGF4X7iYyaqfCm0mIbWvR1UZtIm7VI from [@maghen.key1-tchap.beta.gouv.fr:agent.dinum.tchap.gouv.fr:*,@maghen.calinghee-beta.gouv.fr:agent.dinum.tchap.gouv.fr:ATYFVDAOHJ](id m1663939866188.7)
rageshake.js:66 Looking for queued outgoing room key requests
rageshake.js:66 No more outgoing room key requests
rageshake.js:66 m.room_key_request from @maghen.key1-tchap.beta.gouv.fr:agent.dinum.tchap.gouv.fr:GYDWYOPABB for !PpyQAloFaIemKVNBFb:agent.dinum.tchap.gouv.fr / FWJyaBi3ZMtO/bGF4X7iYyaqfCm0mIbWvR1UZtIm7VI (id m1663939866188.7)
rageshake.js:66 room key request for unknown session !PpyQAloFaIemKVNBFb:agent.dinum.tchap.gouv.fr / FWJyaBi3ZMtO/bGF4X7iYyaqfCm0mIbWvR1UZtIm7VI
```

**Comment by odelcroi** [comment]
> the verification request seems to be sent to v4 but the iphone 2.0.5 does not seems to receive or to handle the request (cf. logs from v4 that seems to send the event

Is is not related to the issue https://github.com/tchapgouv/tchap-web-v4/issues/203 instead ?

**Comment by odelcroi** [comment]
A workaround seems to be : 
- start the verification from the iOs device : WORKS
- start the verification from the web device : does not work

**Comment by odelcroi** [comment]
There are still problems : 

### ❌  **Web 4.2.1 < iOs 2.2.3 (olivier)**
connect to iOs, ecrire quelque chose dans un salon chiffré
connect to Web
⚠️  Le web se plaint que l’appareil n’est pas vérifié, cela semble bloquant
Faire les verifications entre les deux appareils, en la lançant la verification depuis iOs. La verification fonctionne mais le web se plaint toujours de ne pas être vérifié.
Meme en essayant de clear les cache. Les verifications échouent.
⚠️   Il semble que le web n’arrive pas à se vérifier avec l’appareil iOs

**Comment by NicolasBuquet** [comment]
is it related now to cross-signing keys not trusted by the verifying device? 
See https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/helpdesk/articles/fr/371f9f37-92f1-4bcf-8730-1e0899049f27/

**Comment by odelcroi** [comment]
outdated issue
