### ISSUE TITLE
Reset password : backend says you will be logged out, but it's not compulsory any more

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#206]
When you reset your password, there is now a checkbox where you can chose to log out all sessions, or not.
Previously, you had to log out all sessions (no choice).

Obtained : messaging from the backend that says I will be logged out.
Expected : messaging from the backend that doesn't mention if I will be logged out or not (or that corresponds to my choice)

---
Screenshots:

The email you get still mentions you will be logged out :
![image](https://user-images.githubusercontent.com/911434/191998097-956c8306-9006-47a9-81ff-1fe0f8e69e6b.png)

And when you click the link, it also says you will be logged out :
![image](https://user-images.githubusercontent.com/911434/191998193-3cb9874b-9f11-4451-949e-f44819485f3b.png)

**Comment by estellecomment** [comment]
We could also hide the checkbox that allows you to chose whether to log out sessions or not. (is that what mobile clients have done ? @giomfo ? )

**Comment by estellecomment** [comment]
Edit : this checkbox is not displayed because the current prod backend does not support spec r0.6.1.
The mainlining will support it, so the checkbox will be displayed in prod after the mainlining is deployed.

**Comment by estellecomment** [comment]
Edit : this checkbox is not displayed because the current prod backend does not support spec r0.6.1.
The mainlining will support it, so the checkbox will be displayed in prod after the mainlining is deployed.

**Comment by jdauphant** [comment]
@estellecomment The serveur support it

**Comment by odelcroi** [comment]
@jdauphant do you have any input on where to find that the server supports it? 
From the source code, the version expected to enable this option is "r0.6.1" whereas the list of versions that our server returns is : ["r0.0.1", "r0.1.0", "r0.2.0", "r0.3.0", "r0.4.0", "r0.5.0", "r0.6.0"]

https://github.com/matrix-org/matrix-react-sdk/blob/09372fbe8c61ebf17852fac18bf92f1bee34a918/src/components/structures/auth/ForgotPassword.tsx#L150

**Comment by jdauphant** [comment]
@odelcroi 
It's here : https://github.com/matrix-org/synapse-dinsic/blob/1.31.0_dinum_2021_10_05-sygnalrewrite-frozendictfddd/synapse/rest/client/account.py#L289
https://github.com/matrix-org/synapse-dinsic/blob/1.31.0_dinum_2021_10_05-sygnalrewrite-frozendictfddd/synapse/handlers/set_password.py#L52-L66

**Comment by jdauphant** [comment]
You have the corresponded synapse version deployed in prod : https://github.com/tchapgouv/tchap-infra/blob/2ba0d36e9efeab8b3592996c69cc3fc670868ee4/ansible/inventory-agent/group_vars/agent/synapse#L34

**Comment by odelcroi** [comment]
- [ ] hack the react component to force the display of the checkbox, and test if it works well in production

**Comment by estellecomment** [comment]
> * [ ]  hack the react component to force the display of the checkbox, and test if it works well in production

Sounds good ! I'm starting the work today.

**Comment by estellecomment** [comment]
Element-web checks `/_matrix/client/versions` and looks for `r0.6.1` to know if logout devices is supported. 
It's in MSC2457 according to comments in element-web.

Our backend returns 
```
{
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0",
    "r0.6.0"
  ],
  "unstable_features": {
    "org.matrix.label_based_filtering": true,
    "org.matrix.e2e_cross_signing": false,
    "org.matrix.msc2432": true,
    "m.lazy_load_members": true,
    "uk.half-shot.msc2666": true,
    "io.element.e2ee_forced.public": false,
    "io.element.e2ee_forced.private": true,
    "io.element.e2ee_forced.trusted_private": true,
    "org.matrix.msc3026.busy_presence": false
  }
}
```

Looking for a way to check if server supports MSC2457 or logout_devices. If I don't find it, I'll just hard-code "true", but it's more fragile.

**Comment by estellecomment** [comment]
Delayed because Forgot password is broken for now.
https://github.com/tchapgouv/tchap-web-v4/issues/311

**Comment by estellecomment** [comment]
Design ticket for the backend templates : https://github.com/tchapgouv/tchap-design/issues/97

**Comment by odelcroi** [comment]
#310
