### ISSUE TITLE
Cannot scroll on the list of homeservers when choosing a public room

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#207]
When exploring the rooms, the list of homeservers is too long therefore we cannot scroll on the list : 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3725676/191999108-8c3e02d3-82e9-489d-af75-1ed24bb51a62.png">

**Comment by odelcroi** [comment]
Quick fix proposal @Caroline-lawson  @areox-net : 
![Capture d’écran 2022-09-27 à 13 05 17](https://user-images.githubusercontent.com/4077729/192509600-3020125f-54c9-4101-a50b-505912dbd6cd.png)

**Comment by odelcroi** [comment]
patch-name : public-room-server-list

**Comment by Caroline-lawson** [comment]
So the list is in a smaller font so it fits without having to scroll?

Do we need "Server" in front of each option?

**Comment by odelcroi** [comment]
what about : 
<img width="559" alt="Capture d’écran 2022-09-27 à 15 32 58" src="https://user-images.githubusercontent.com/4077729/192540599-c34e3fe6-dd84-47d4-ae58-7b85e9cb4eb8.png">
