### ISSUE TITLE
Améliorer le signalement d'erreur de v4

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#211]
Users cannot easily get help when they have a problem in v4.
There are problems with the In Settings > Help and About menu.

 - [x] You can open a github issue against element-web's repo. Expected : repo should be tchap-web-v4.
 - [x] Add the support email to contact, very visibly, this is the first action to take. Leave a smaller link to the github repo.
 - [x] Add a link to the known issues page for v4
 - [x] Submit bug report is broken (https://github.com/tchapgouv/tchap-web-v4/issues/213)
 - [ ] Optional : add a shortcut to "Help And About" directly in the first menu (the way Security and Privacy does) to make it easier to find help.

**Comment by jdauphant** [comment]
@estellecomment we have to modifi react-sdk, it's hardcoded

**Comment by estellecomment** [comment]
patch-package ! Patch patch patch patch patch patch

**Comment by estellecomment** [comment]
PR https://github.com/tchapgouv/tchap-web-v4/pull/212
