### ISSUE TITLE
Invite by email : dialog crashes unless you paste email

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#227]
Reproduce : 
 - Go to a room (private or forum)
 - Type an email (existing or non-existing user, intern or extern)
 - Type enter or space

Obtained : dialog disappears, no invitation.
An error occured :
```
Uncaught TypeError: Cannot read properties of undefined (reading 'userId')
    at InviteDialog.tsx:947:92
    at Array.map (<anonymous>)
    at ne.renderEditor (InviteDialog.tsx:946:44)
    at ne.render (InviteDialog.tsx:1221:24)
    at Ga (react-dom.production.min.js:187:188)
    at ja (react-dom.production.min.js:186:173)
    at Gs (react-dom.production.min.js:269:427)
    at Tl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at yl (react-dom.production.min.js:250:138)
```
Expected : invitation should happen (or be refused with an explanation, if appropriate)

Notes : 
 - Workaround : copy the email and paste it in the dialog. It appears displayed in a pill, and the invite flow works. I suspect a problem with creating the pill.
 - scope : this issue is about the invite dialog crashing and disappearing, not about problems with room creation after the dialog is successfully done)
- not seen in element-web 1.11.5, that current version is based on (4.0.1_1.11.5)

**Comment by mcalinghee** [comment]
There are 3 elements blocking this feature to work : 
- [ ] `_matrix/identity/v2/terms` does not exists and make it fails : https://github.com/tchapgouv/tchap-web-v4/issues/228
- [ ] `UIFeature.identityServer` is set to `false` => we can set this to `true` but we need to hide the dicovery panel
- [ ] `UIFeature.thirdPartyId` is set to `false` 
   - [ ] the `Go` button is not working as no `userId` has been defined : 
   ```
   Uncaught TypeError: Cannot read properties of undefined (reading 'userId')
    at InviteDialog.tsx:947:92
   ```
   => we can set this to `true`
