### ISSUE TITLE
Invite by email : Fails because of identity server Terms request

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#228]
Reproduce 
 - create user in v2
 - log into v4
 - create room
 - add a person by email (copy paste the email rather than typing it because of [this issue](https://github.com/tchapgouv/tchap-web-v4/issues/227))
 You can use an email for an internal or external account, corresponding to a user account that exists or not.
 
 Expected : person is added
 Obtained : 
![Screen Shot 2022-09-28 at 12 42 28](https://user-images.githubusercontent.com/911434/192759508-907a58db-281c-4a3a-a579-acaa0bf8bcd2.png)

----

Investigation

User interacts with the identity server, the logs say :

200 - POST https://matrix.agent.dinum.tchap.gouv.fr/_matrix/client/r0/user/< my test email >3%3Aagent.dinum.tchap.gouv.fr/openid/request_token
Responds with access token and other params

200 - POST https://matrix.agent.dinum.tchap.gouv.fr/_matrix/identity/v2/account/register
Response : access token and token

200 - GET https://matrix.agent.dinum.tchap.gouv.fr/_matrix/identity/v2/account
Response : {"user_id": "@< my test email >:agent.dinum.tchap.gouv.fr"}

403 - GET https://matrix.agent.dinum.tchap.gouv.fr/_matrix/identity/v2/terms
CORS request rejected (usually this means the endpoint is not implemented)

The error is repeatable with the same logs, if you go back and re-click "Invite".

Not seeing this issue on my personal account. 
Maybe when you use v2, v2 approves the terms of the id server silently, and so you don't see this issue.

**Comment by mcalinghee** [comment]
Example of response in _Element_
Request : 
```http
GET https://matrix.agent.dinum.tchap.gouv.fr/_matrix/identity/v2/terms
```
Response : 
```json
{
  "policies": {
    "privacy_notice": {
      "version": "1",
      "en": {
        "name": "Privacy Notice",
        "url": "https://vector.im/identity-server-privacy-notice-1"
      }
    }
  }
}
```
