### ISSUE TITLE
Track how many users are using which version of tchap-web (beta..)

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#236]
Change the user-agent to add the tchap-web version in order to re-use this in our stats
We could rely on the package.json :   `version": "4.0.2_1.11.5`

**Comment by odelcroi** [comment]
I guess the problem you want to solve is to track which versions is used by how many users : 
- as we already have users metrics based on the user-agent, we could add a version to the user-agent, I'm wondering what would be the side effects?
- is there any other way to track this information in a none intrusive way, maybe with tracking cookies on the nginx side

**Comment by jdauphant** [comment]
Changing user agent on the client side is on the way to be removed by all browsers (apparently it's already the case in Firefox)

**Comment by odelcroi** [comment]
The current not perfect solution is to track how many hits are logged to the url /join-beta.

It will not work when people will be migrated to v4 without hitting this url.

**Comment by odelcroi** [comment]
Could we track the cookie header "tchap_split_version=version_current" sur le endpoint "/"

**Comment by odelcroi** [comment]
https://github.com/tchapgouv/tchap-infra/pull/1702
