### ISSUE TITLE
Verification of 2 session with Verify button, keys are not exchanged automatically

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#239]
### Scope of the issue : 
- session A in v4 and session B in v4
- session A in v4 and session B in iOS
- session A in v4 and session B in android

### Steps to reproduce
1. user 1 has already a session opened : session A
2. user 1 is opening a new session by logging : session B
3. session B is not going through the verification process suggested when logging : session B is not verified
4. session A press `Verify` in `Security and Privacy settings` and trigger the verification process with session B
<img width="929" alt="Screenshot 2022-09-29 at 18 34 45" src="https://user-images.githubusercontent.com/3725676/193090425-46f9985b-1546-4803-9a2c-014256e44821.png">
5. session A waits for session B to respond
<img width="687" alt="Screenshot 2022-09-29 at 18 35 51" src="https://user-images.githubusercontent.com/3725676/193090649-e752bad6-9472-4f48-b681-ee29f74737a9.png">
6. on session B, a verification request dialog is displayed
<img width="270" alt="Screenshot 2022-09-29 at 18 35 57" src="https://user-images.githubusercontent.com/3725676/193090913-d2172c3b-755c-400f-a18d-4be5b8c96cf1.png">
7. session B press `Accept`

8. on session A, the verification start dialog is displayed
<img width="527" alt="Screenshot 2022-09-29 at 18 36 06" src="https://user-images.githubusercontent.com/3725676/193091089-8951a01b-1f94-44f1-83b4-0bd981bec45b.png">
9. on session B, the verification start dialog is displayed
<img width="677" alt="Screenshot 2022-09-29 at 18 36 11" src="https://user-images.githubusercontent.com/3725676/193091157-219cf3db-76e8-4719-b176-bede3ad1974b.png">
10. session B press `Start`

11. on session A, verification process dialog is displayed
<img width="516" alt="Screenshot 2022-09-29 at 18 36 20" src="https://user-images.githubusercontent.com/3725676/193091687-0585cc08-b7a2-4d65-96a7-3ee8aaf13b70.png">
12. on session B, verification process dialog is displayed 
<img width="669" alt="Screenshot 2022-09-29 at 18 36 24" src="https://user-images.githubusercontent.com/3725676/193091715-f7e74fa3-4c0b-4d90-8a85-4bd5f672a539.png">
13. session B press `They match` and waits for session A
<img width="528" alt="Screenshot 2022-09-29 at 18 36 32" src="https://user-images.githubusercontent.com/3725676/193091871-5bc253d2-bf3b-4ac7-8d29-6e6698790f09.png">
14. session A press `They match` 

15. on session A , a success dialog is displayed
<img width="667" alt="Screenshot 2022-09-29 at 18 36 46" src="https://user-images.githubusercontent.com/3725676/193092244-1bf69d9b-96dc-44d7-b98b-292cfabbf743.png">
16. on session B , a success dialog is displayed
<img width="508" alt="Screenshot 2022-09-29 at 18 36 52" src="https://user-images.githubusercontent.com/3725676/193092463-784fa5d6-6825-442f-853a-5aebf873053f.png">
17. session B cannot decrypt the messages
<img width="272" alt="Screenshot 2022-09-29 at 18 57 01" src="https://user-images.githubusercontent.com/3725676/193092613-8ae1cb74-1b44-4125-b4d0-dd8c850633e5.png">
18. on session B, settings shows verified devices
<img width="526" alt="Screenshot 2022-09-29 at 18 57 51" src="https://user-images.githubusercontent.com/3725676/193092963-fa85ef65-1fc1-4056-952c-fdd65fd92eda.png">
19. on session A, settings shows verified devices
<img width="721" alt="Screenshot 2022-09-29 at 18 59 20" src="https://user-images.githubusercontent.com/3725676/193093219-02d14bfc-4bf0-4c2f-97d3-9e7f745ce018.png">

### Actual
session A does not shared keys to session B

### Expectation
session A should share its keys to session B automatically after the verification process is a success

**Comment by odelcroi** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_47c14606-6e6f-42bc-b4c7-245a24ac2036/

**Comment by odelcroi** [comment]
outdated issues, some problems are still there but not those ones
