### ISSUE TITLE
what is this icon on crypted messages ?

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#240]
### Steps to reproduce

1. Dunno

#### What happened instead?
This icon appears on messages
<img width="470" alt="Capture d’écran 2022-09-30 à 18 27 38" src="https://user-images.githubusercontent.com/4077729/193315375-d5a6df11-a3d0-487a-b534-d60cc4a6d878.png">

with css selector
"mx_EventTile_e2eIcon mx_EventTile_e2eIcon_normal"

### Will you send logs?

No

**Comment by odelcroi** [comment]
With XSSS we get even more icons next to messages

- [ ] study UX impacts

**Comment by Delphgateau** [comment]
<img width="410" alt="image" src="https://github.com/user-attachments/assets/1b0736db-bd8a-4a79-a04b-da27872414bf">
