### ISSUE TITLE
Room avatars are blurry

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#250]
### Steps to reproduce

Un détail esthétique : les avatars (format *.jpg) s'affichent avec un léger flou dans le menu de la liste des Personnes / Salons et sur les bulles dans les discussions.

Problem seems to be related to the size of the image retrieved from the media repo.

**Comment by odelcroi** [comment]
On a 1280x800 screen, room avatars are blurry on the list of rooms : 
<img width="232" alt="Capture d’écran 2022-10-24 à 12 30 08" src="https://user-images.githubusercontent.com/4077729/197507388-97a90329-fa79-4260-8a8f-54b7993c3380.png">

Less blurry by increasing slightly the size of the avatar  (32px to 36px) : 
<img width="232" alt="Capture d’écran 2022-10-24 à 12 29 49" src="https://user-images.githubusercontent.com/4077729/197507675-6f790e9a-7950-4339-9452-cf9d0ffdeef5.png">

**Comment by odelcroi** [comment]
on a 1080p resolution, room avatars are not blurry

**Comment by odelcroi** [comment]
Oui, c'est parce que l'image source fat 30x30px. Pour qu'elle ne soit pas blurry sur retina, il faudrait qu'elle soit au moins 60x60px et redimensionnée en HTML+CSS

**Comment by revolunet** [comment]
Pareil pour la liste des personnes :/

Actuellement ca utile [une image de 30px](https://matrix.agent.dinum.tchap.gouv.fr/_matrix/media/v3/thumbnail/matrix.agent.dinum.tchap.gouv.fr/5f2734de5e161197e495d5c5c326814316190073?width=30&height=30&method=crop) mais apparemment on peut changer la taille facilement.

Par contre j'ai l'impression que cette info ne vient pas du client web mais de données des profils 🤔

**Comment by odelcroi** [comment]
> Pareil pour la liste des personnes :/
> 
> Actuellement ca utile [une image de 30px](https://matrix.agent.dinum.tchap.gouv.fr/_matrix/media/v3/thumbnail/matrix.agent.dinum.tchap.gouv.fr/5f2734de5e161197e495d5c5c326814316190073?width=30&height=30&method=crop) mais apparemment on peut changer la taille facilement.
> 
> Par contre j'ai l'impression que cette info ne vient pas du client web mais de données des profils 🤔

Je remarque ce bug sur mon écran Mac Retina mais pas sur un écran 1080. Est ce votre cas aussi?

**Comment by revolunet** [comment]
tout a fait, écran "retina" ici aussi

**Comment by estellecomment** [comment]
app.element.io does not have the problem.
