### ISSUE TITLE
Decryption Error : OLM.UNKOWN_MESSAGE_INDEX

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#251]
### Scenario to reproduce the issue
1. Log in with user1
2. Log in with user2
3. user1 sends a message A
4. user2 read the message A
5. user2 export its keys 
6. user2 logs out
7. user1 sends a message B
8. Log in with user2
9. user2 import its keys (step 5)
10. user2 can read message A
11. user2 cannot read message B (see screenshot)
An error is present : `OLM.UNKOWN_MESSAGE_INDEX`
<img width="1037" alt="Screenshot 2022-10-17 at 15 14 07" src="https://user-images.githubusercontent.com/3725676/196188171-82cb9abf-3047-4a2e-8240-25393d46eabe.png">

**Comment by estellecomment** [comment]
Isn't this expected behavior ? The imported keys only decrypt messages up
to when they were exported (so they decrypt A but not B).
To get message B, the client should get keys from another session, through
a key exchange.

**Comment by odelcroi** [comment]
Issue fermée car le composant a été mis à jour et ne reproduis plus l'erreur
