### ISSUE TITLE
Secure storage : 'Set up Secure Backup' is displayed

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#252]
### Scenario to reproduce the issue : 
Pre-requirement : use a new account to do not hijack your own account

1. Log in with user1
2. Send messages to user2
3. Clean your navigator cache (no logout)
4. Close your navigator
5. Open your navigator and login with user1
6. Go to "Security and Privacy Settings'
7. In the settings : "Sign out all devices" but keep "This device" 
You should have one verified device (see below screenshot)
<img width="751" alt="Screenshot 2022-10-17 at 15 39 42" src="https://user-images.githubusercontent.com/3725676/196192663-92c6546e-1a88-4e13-98cb-361f7d38e27e.png">

8. Logout with user1
9. Log in with user1 , the following pop up is happening
<img width="611" alt="Screenshot 2022-10-17 at 15 40 25" src="https://user-images.githubusercontent.com/3725676/196193123-f3b3dd7b-84f6-44a3-978a-a3a4181ad41e.png">

10. Click on "Proceed with reset"
<img width="609" alt="Screenshot 2022-10-17 at 15 21 15" src="https://user-images.githubusercontent.com/3725676/196190025-82677e13-6fd4-4f99-9d97-469ce7e757a0.png">

=> No setup of Secure Backup should be possible

**Comment by jdauphant** [comment]
@mcalinghee do you had cross-signing activated with this user ?

**Comment by mcalinghee** [comment]
> @mcalinghee do you had cross-signing activated with this user ?

No cross signing activated
