### ISSUE TITLE
Can not download files from a room

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#254]
### Steps to reproduce

- send a file to a person via DM
- try to download the file

> de mon côté, je n'arrive plus à télécharger les fichiers dans Tchap web beta ☹️
pour les images, je peux les ouvrir en affichage et le bouton de téléchargement fonctionne alors
mais pour les fichiers zip, par exemple, le bouton de téléchargement reste inactif

> Bonjour, j'ai vidé le cache sans succès. Du coup, j'ai paramétré mon compte Tchap sur un autre ordinateur sous Windows 11 avec Chrome et je rencontre le même problème : l'icône de téléchargement  est inerte

> Je rencontre le problème sur Edge mais pas sur Firefox

> Non, je le rencontre pour toutes les sortes de fichiers, y compris les images
Mais pour ces dernières,  on peut les agrandir dans le lecteur intégré,  le bouton de téléchargement de ce lecteur fonctionne bien.

### Outcome
What should happen
- the file is downloaded

What happens
- the button has no effect

### Operating system

MacOs 11.3.1 avec Chrome Version 106.0.5249.119 (Build officiel) (x86_64)
Windows 11 avec Edge

Not reproduced with
Firefox 
Version 106.0.5249.119 (Build officiel) (x86_64)

### Will you send logs?

No

**Comment by mcalinghee** [comment]
### Analysis

**Description of the issue :** 
When downloading a file, the process is happening in 2 steps : 
1. Request from tchap-web on : `GET https://www.tchap.gouv.fr/usercontent/`
Response : 
```html
<html>
<head>
    <!--
    Hello! If you're reading this, perhaps you're wondering what this
    file is doing and why your Element is using it.
    In short, this allows Element to isolate potentially unsafe encrypted
    attachments into their own origin, away from your Element.
    Stay curious!
    -->
<link rel="preload" href="/fonts/Inter/Inter-BoldItalic.2129bd0.woff2"><link rel="preload" href="/fonts/Inter/Inter-Bold.fc28dff.woff2"><link rel="preload" href="/fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2"><link rel="preload" href="/fonts/Inter/Inter-SemiBold.0802d48.woff2"><link rel="preload" href="/fonts/Inter/Inter-MediumItalic.8154ac2.woff2"><link rel="preload" href="/fonts/Inter/Inter-Medium.027d14e.woff2"><link rel="preload" href="/fonts/Inter/Inter-Italic.b791861.woff2"><link rel="preload" href="/fonts/Inter/Inter-Regular.4232a67.woff2"></head>
<body><script src="../bundles/2bc64c92a71bae258f08/usercontent.js"></script></body>
</html>
```

2. Then another request from tchap-web is happening : `GET https://www.tchap.gouv.fr/bundles/2bc64c92a71bae258f08/usercontent.js`
Response : `HTTP ERROR NOT FOUND 404 `

_______

**Infrastructure differences :** 
The same version of tchap in prod tchap-4.0.4_1.11.9-rc.2 has been deployed on scalingo : #260

1. On production : www.tchap.gouv.fr
=> we have an error HTTP ERROR 404
2. On scalingo : #260
=> no errors and we can dowload the file properly

**Comment by odelcroi** [comment]
solved by : https://github.com/tchapgouv/tchap-infra/pull/1487

**Comment by lcaylat** [comment]
Hi,
I have the file download problem again but only with Edge 108. I don't reproduce it with Chrome or Firefox.
I am using Tchap version 4.1.3_1.11.12.
Do I open a new issue?

**Comment by mcalinghee** [comment]
I have tested to download files on Edge 108 and this is working.

**Comment by odelcroi** [comment]
A user has reported errors at downloading files from Chrome 108,  I don't think this bug is related to browsers

**Comment by odelcroi** [comment]
Another user has reported problems at dowloading from firefox

**Comment by mcalinghee** [comment]
A suggestion of fix could be to release v4 to 100% of our users and remove all specific config on the load balancer depending on cookies.

**Comment by jdauphant** [comment]
> A suggestion of fix could be to release v4 to 100% of our users and remove all specific config on the load balancer depending on cookies.

I don't think that the solution. 

I will suggest to apply correctly the recommandation for caching : https://github.com/vector-im/element-web#caching-requirements

**Comment by mcalinghee** [comment]
**Temporary fix:** Ctrl+Shift+R seems to fix the issue

**Comment by mcalinghee** [comment]
> > A suggestion of fix could be to release v4 to 100% of our users and remove all specific config on the load balancer depending on cookies.
> 
> I don't think that the solution.
> 
> I will suggest to apply correctly the recommandation for caching : https://github.com/vector-im/element-web#caching-requirements

We have now opened an issue for this : https://github.com/tchapgouv/tchap-web-v4/issues/337

**Comment by odelcroi** [comment]
Fix on a chrome user : [x] allow third party cookie for all site

**Comment by odelcroi** [comment]
- [x] Investigate the error : Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.

**Comment by mcalinghee** [comment]
Can we close this issue in favor of : https://github.com/tchapgouv/tchap-web-v4/issues/344
