### ISSUE TITLE
[Sprint goal] perte de clés : Modifier le client web v2 pour aider à la compréhension

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#26]
Changements de texte surtout, peut etre des autres petites modifs ?
Se mettre au service de Caro.

 - faire des review apps sur les PRs de Caro pour regarder le resultat. (tache de dev)
 - pour implémenter la version anglaise aussi : ca va etre chelou d'avoir un fichier en.json avec des traductions anglais-element vers anglais-tchap. Est-ce qu'on peut eviter, au moins pour certaines translations ? Regarder si on peut trouver une solution d'implémentation plus propre.
 - documenter les changements, par ex avec des screenshots avant-apres (dans cette issue ou dans la PR ou ailleurs) pour pouvoir facilement implementer sur mobile ensuite.

**Comment by celiacheff** [comment]
Tasks so far:

- [x] Add a modal after signout
- [x] Various translations / wording
- [x] Change import keys behavior by closing all popups after import
- [ ] Show/hide password feature (need to check security concerns) 

Source: [Miro](https://miro.com/app/board/o9J_lxa1Nm0=/)

**Comment by celiacheff** [comment]
Addendum:
- [x] Add a link to upload keys to unlock messages

**Comment by Caroline-lawson** [comment]
Ressource Miro pour les captures d'écran et les textes : https://miro.com/welcomeonboard/WDRMMk9hbDBEUnVWWGNaS3lDOXZQNmhpbnEwZG9UQXRxT3M0QlM3RE15T0dXUkZyeEkza293RjNzMEh1bjRsOHwzMDc0NDU3MzQ4Nzg3NTYwODk3?invite_link_id=451176937770

**Comment by areox-net** [comment]
Voici ma proposition des 3 modales à proposer à la déconnexion et exporter ses Clé Tchap. Nous allons affiner les textes avec @Caroline-lawson et metre à jour les planches Figma.

1.Deconnexion
![Modale-LogOut](https://user-images.githubusercontent.com/1255251/162172064-3093e04e-94d5-4462-a874-aa57c4f5703a.png)

2. Sauvegarde des clés
![Modale-SaveKeys](https://user-images.githubusercontent.com/1255251/162172092-6e721db8-338e-4681-9e37-ea39e4b03b06.png)

3. Confirmation
![Modale-KeySaved](https://user-images.githubusercontent.com/1255251/162172115-fc9cff28-7563-4c2e-8967-714291ee7ad0.png)

**Comment by Caroline-lawson** [comment]
Changement de texte pour 1. Déconnexion :

**Sauvegardez vos Clés Tchap avant de vous déconnecter**

**Sans vos Clés Tchap, vous ne pourrez pas lire vos messages** à votre prochaine connexion parce qu'ils seront verrouillés. C'est une mesure de sécurité Tchap.

**Vous pouvez actuellement lire vos messages sur un autre appareil ?** 
Vous pouvez vous déconnecter. Cet autre appareil sauvegarde automatiquement vos Clés Tchap et vos messages.
[CTA bleu] Me déconnecter

**Vous n'avez pas d'autre appareil connecté à Tchap ?** 
Sauvegardez vos Clés Tchap. Ces clés déverrouilleront les messages actuels, mais pas ceux reçus après la sauvegarde.
[CTA bleu] Sauvegarder

**Comment by areox-net** [comment]
Maquette à jour sur Figma https://www.figma.com/file/3qu9dfXgLomL6u04mpaTip?node-id=0:1#177270696

![Modale-LogOut](https://user-images.githubusercontent.com/1255251/162436832-f447b594-6e26-4a9e-b888-48e2c0f9fff4.png)

**Comment by celiacheff** [comment]
Show/hide password feature (need to check security concerns) -> was added on the way, I won't do it in this sprint, it needs to be prioritized and re-added to backlog in needed
