### ISSUE TITLE
Desktop/browser notification disappeared 

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-web-v4#267]
### Steps to reproduce

I did not do anything but the problem started 10 days ago (approx)

### Outcome

- No more noise
- No more preview / popup 
- Did not manage to get it back, even when all the settings in Tchap and in the browser seem to be ok 

I am using Google Chrome Version 106.0.5249.119 (Build officiel) (x86_64)

### Will you send logs?

Yes

**Comment by JDixmier** [comment]
A user reported the same problem : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_1537d6d1-83dc-465f-a42b-6aed46cc3fd5/

**She's using google chrome / windows 10**

**Comment by estellecomment** [comment]
Maybe fixed by upgrade to element-1.11.10 ? https://github.com/tchapgouv/tchap-web-v4/pull/269
