### ISSUE TITLE
Choice of themes should be just "light" or "dark"

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#273]
Currently we have "light" "dark" and "tchap", which is weird.

**Comment by odelcroi** [comment]
Themes choices are defined statically in `[ThemeChoicePanel](https://github.com/matrix-org/matrix-react-sdk/blob/d599b1b206dba16fecdaf1824e2de38a302e4b60/src/components/views/settings/ThemeChoicePanel.tsx)`. To have only 2 themes, we need either to : 
- add tchap dark and tchap light custom themes while removing the standard ones from the choices list
- customize the standard themes while removing tchap custom theme


## How themes work
Themes are mainly post-css variables to define colors of the UI. For instance for the dark theme, the [dark.pcss](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/dark/css/dark.pcss) file defines variables :

`$primary-content: #ffffff;
`
Element defines dark and light themes in the folder matrix-react-sdk/res/themes. 

To handle custom themes (both dark and light), element uses a special [pcss](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/light-custom/css/light-custom.pcss) file where variables are defined with css variables like so : 

`$primary-content: var(--primary-content, $primary-content);`

Css variables are defined in the "custom-theme" of the config.json file . I wonder if it is possible to define them in plain css, from a tchap css file for instance.

I couldn't figure out how css variables are taken from the config file?

## solutions
1/ solution 1 (tested and working)
add a pcss file in dark.pcss and light.pcss to override pcss variables 
like so :  
```
@import "../../../../res/css/_font-sizes.pcss";
@import "_paths.pcss";
@import "_fonts.pcss";
@import "_light.pcss";
//:tchap: override css variables before their use
@import "../../../../../../res/themes/tchap/light/_tchap-light.pcss";
//:tchap: end
@import "_mods.pcss";
//@import "../../light-custom/css/_custom.pcss";
@import "../../../../res/css/_components.pcss";
@import url("highlight.js/styles/atom-one-light.css");
```

2/solution 2 (wip) 
add our pcss file in dark-custom.pcss and light-custom.pcss to override css variables

3/ solution 3 (wip)
create both tchap dark and tchap light theme that imports dark-custom and dark-light

**Comment by odelcroi** [comment]
relates to #130
