### ISSUE TITLE
Registration does not work with mainlining : "User ID cannot be empty"

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#281]
Tchap-web sends register requests with empty username, because the backend fills it in based on the email.
The mainlining backend seems to refuse empty usernames.

<img width="706" alt="Capture d’écran 2022-12-06 à 16 34 11" src="https://user-images.githubusercontent.com/4077729/205955391-075c9232-12b6-4e06-adcf-1af859266669.png">

---
On dev, tchap-web registration fails :
Request :
```
POST https://matrix.agent1.tchap.incubateur.net/_matrix/client/r0/register
{"username":"","password":"<password>","initial_device_display_name":"tchap-web-staging-v4-pr276.osc-secnum-fr1.scalingo.io (Firefox, macOS)"}
```

Response : blocks the rest of the register flow
`400 {"errcode":"M_INVALID_USERNAME","error":"User ID cannot be empty"}`

---
On prod, tchap-web registration works : 
Request : 
```
POST https://matrix.agent.dinum.tchap.gouv.fr/_matrix/client/r0/register
same payload
```

Response : expected in succesful register flow :
```
401 {"session":"<sessionId>","flows":[{"stages":["m.login.email.identity"]}],"params":{}}
```

**Comment by mcalinghee** [comment]
On mainlining version : 
- we have an error 400 - Bad Request
![image](https://user-images.githubusercontent.com/3725676/205956224-de16d390-6d52-466b-817b-c40330249011.png)

On production version (no mainlining)
- we have an error 401 - Unauthorized
![image](https://user-images.githubusercontent.com/3725676/205956658-077829df-ad02-4a79-be17-8b7d547b0b5d.png)


We can either fix this : 
1/ in v4 : if we fix this in v4 we might defer the code from element-web
2/ or in synapse
