### ISSUE TITLE
theme : room avatars take default colors

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#282]
Issue discovered in branch #277 

### Steps to reproduce

Open tchap

### Outcome

They should be gray : 
<img width="71" alt="Capture d’écran 2022-10-27 à 17 30 31" src="https://user-images.githubusercontent.com/4077729/198333229-f90a36a9-3062-44fd-bd77-093635afdf82.png">

They are colorful : 
<img width="69" alt="Capture d’écran 2022-10-27 à 17 31 37" src="https://user-images.githubusercontent.com/4077729/198333500-a99597db-3e16-43b0-8770-07b34f0a10ea.png">

### Will you send logs?

No

**Comment by odelcroi** [comment]
`Avatar.ts#defaultAvatarUrlForString `could be patched to use this : 
``const cssValue = getComputedStyle(document.body).getPropertyValue(cssVariable);``
instead of this
`` const cssValue = document.body.style.getPropertyValue(cssVariable); ``

**Comment by odelcroi** [comment]
Or another solution is to invoke `theme.ts#setCustomThemeVars` during application init

**Comment by jdauphant** [comment]
I have retry it : It's complicated
