### ISSUE TITLE
When creating account with unauthorized domain, interface is confusing

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#288]
create account with non allowed domain -> email is not sent, which is good, but :
- error message is in english, not translated ("Your email is not authorized to register on this server")
- "email has been sent" screen is briefly displayed, and then the user is returned to the login form with the error message. So it's confusing if the email has been sent or not. (it's not)

**Comment by odelcroi** [comment]
fixed :
![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/113fed1c-9f90-4584-b6e5-72bcfb0d16a5)
