### ISSUE TITLE
errors in log : 'map_style_url' missing from homeserver 

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#290]
#### What happened instead?
rageshake.ts?8b38:73 'map_style_url' missing from homeserver .well-known area, and missing from from config.json.

#### 
In disable location, we might use a feature flag to avoid this error in logs

**Comment by estellecomment** [comment]
The code is checking if map_style_url is present in config, so that it can
display the "share your location" buttons.
In our case it's not present.
See https://github.com/tchapgouv/tchap-web-v4/pull/271

It's annoying that it logs an error every time, yes, agreed

**Comment by estellecomment** [comment]
in discussion with element : https://github.com/matrix-org/matrix-react-sdk/pull/9481

**Comment by odelcroi** [comment]
This patch should not be necessary anymore thanks to new version of Element : https://github.com/tchapgouv/tchap-web-v4/issues/618
