### ISSUE TITLE
The new device manager (labs feature) verifies current session and doesn't work

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#295]
Tested in dev backend. 

Reproduce :
 - Activate feature in settings, in Labs/experimental (feature added in element-web 1.11.12)
 - Shows an extra section in settings, which prompts users to verify sessions : 
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/911434/200576947-0a3127a7-9634-43f4-86ce-a775b9f7b6dc.png">

Without cross-signing, can users verify sessions ? Should we just hide this until we have cross-signing deployed ?

**Comment by estellecomment** [comment]
Trying to verify the current session : UI gets stuck on spinner : 

<img width="1042" alt="Screen Shot 2022-11-08 at 2 35 02 PM" src="https://user-images.githubusercontent.com/911434/200578940-871cff51-222b-410c-920a-c23cc7b617dd.png">


14:33:08,610
XHR GET https://matrix.agent1.tchap.incubateur.net/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device
[HTTP/1.1 404 Not Found 52ms]

14:33:08,663 could not get dehydrated device M_NOT_FOUND: MatrixError: [404] No dehydrated device available (https://matrix.agent1.tchap.incubateur.net/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device) [bundle.js:2:2938614](https://tchap-web-staging-v4-pr285.osc-secnum-fr1.scalingo.io/bundles/4eb602d382d5ba17f139/bundle.js)

14:33:08,663
Uncaught (in promise) TypeError: i is null (in hasDevicesToVerifyAgainst)

**Comment by estellecomment** [comment]
Test in prod as well, same result (so it's unrelated to mainlining)

Note that the new device manager only allows verifying the current session, which does not work.
The previous settings allow verifying other sessions, which work.

**Comment by odelcroi** [comment]
Deactivate for now
