### ISSUE TITLE
v4<>v4 : no keys exchanged until sessions are verified

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#297]
On prod backend (no mainlining)
 - Create fresh account.
 - log in on edge. Send messages to DM and private room.
Tchap version: 4.0.5_1.11.9-rc.2
Olm version: 3.2.12
 - Log in on firefox private. 
Version de Tchap : 4.0.5_1.11.9-rc.2
Version de Olm : 3.2.12
 - No emoji request appears on either session. Messages in the new session appear encrypted. 
 - Click on “resend request” on an encrypted message. No emoji request appears on either session. Messages still encrypted.

-> expected : start an emoji request at login, and if it fails or is cancelled, then start an emoji request when clicking on "send request". Thus decrypt messages.

To fix it, sessions can verify each other :
 - Sessions appear unverified in security settings. Click on verify session.
 - emoji exchange happens. Messages are now decrypted.

**Comment by estellecomment** [comment]
Is this because of private window on firefox ? (no indexedDB on private window)

**Comment by odelcroi** [comment]
not reproduced with 4.2.0, closing...
