### ISSUE TITLE
Languages : we offer "English" and "English (US)", it's redundant

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#301]
Figure out if they are different, and remove one.
(it it because of our tchap_translations.json file ?)

**Comment by odelcroi** [comment]
For simplification and as Element works mainly on the EN_en translations, en_US should be removed

**Comment by odelcroi** [comment]
EN translation is not a priority for Tchap

**Comment by estellecomment** [comment]
closed at some point by patch only-fr-and-en
