### ISSUE TITLE
In settings, text for export/import keys is incoherent in french

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#307]
In settings > security and privacy : 

In french : import and export buttons use different words
<img width="560" alt="Screen Shot 2022-11-15 at 4 15 27 PM" src="https://user-images.githubusercontent.com/911434/201956250-40b0e0eb-6035-455b-9afe-da4fd74f03d4.png">

In english : same word :
<img width="400" alt="image" src="https://user-images.githubusercontent.com/911434/201956531-a1335af6-51fe-489b-b5d4-8dc26fbb77b9.png">

**Comment by odelcroi** [comment]
in V2 : 
<img width="732" alt="Capture d’écran 2022-11-23 à 15 24 53" src="https://user-images.githubusercontent.com/4077729/203571226-570a53ca-a691-40d5-b75d-5ce6a1733602.png">
