### ISSUE TITLE
Upgrade element-web to 1.11.17 or more (jump 3 versions)

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#308]
Right now we have 1.11.12

From the news channel :

1.11.13
hotfix including fixes for session restoration failing when the server cannot be reached as well as password reset not working

1.11.14
improvements around threads
fixes for room & space avatars

1.11.15
 fix for a soft crash around thread notifications

1.11.16
This version includes visual tweaks to replies, improvements to notifications especially around threads and a bug fix for screensharing in 1:1 calls; you can see the full changelog at https://github.com/vector-im/element-web/releases/tag/v1.11.16

1.11.17
more fixes, especially threads (still in beta)

**Comment by estellecomment** [comment]
- [ ] remove the patch `remove-authorization-header-in-reset-password` and check that the regression in https://github.com/tchapgouv/tchap-web-v4/issues/311 does not reappear

**Comment by odelcroi** [comment]
Those PR are quite interesting, we might wait for them : 
https://github.com/matrix-org/matrix-js-sdk/pull/2921 -> js-sdk 23.0.0, in 1.11.17
https://github.com/matrix-org/matrix-react-sdk/pull/9662 -> in 1.11.17

**Comment by odelcroi** [comment]
- [ ] this patch can be removed https://github.com/tchapgouv/tchap-web-v4/pull/326

**Comment by odelcroi** [comment]
- [ ] this PR is very interesting for us : https://github.com/matrix-org/matrix-js-sdk/pull/2920 BUT IT IS NOT IN matrix-js-sdk : 23

**Comment by odelcroi** [comment]
Updates will be : 
element web : 1.11.12 -> 1.11.17
"matrix-js-sdk": "21.0.0" -> 23.0.0
"matrix-react-sdk": "3.59.0" -> 3.63.00

https://github.com/vector-im/element-web/compare/v1.11.12...v1.11.17
https://github.com/matrix-org/matrix-react-sdk/compare/v3.59.0...v3.63.0
https://github.com/matrix-org/matrix-js-sdk/compare/v21.0.0...v23.0.0

**Comment by odelcroi** [comment]
matrix-js-sdk v21.2.0 is mainly about group calls

**Comment by odelcroi** [comment]
Warnings : 
- https://github.com/vector-im/element-web/issues/22346#issuecomment-1178623728
- https://github.com/matrix-org/matrix-js-sdk/pull/2907
- https://github.com/matrix-org/matrix-react-sdk/pull/9484 (sub space)
- https://github.com/matrix-org/matrix-react-sdk/pull/9549 (change avatar)
- https://github.com/vector-im/element-web/issues/22846 (search of rooms : private, private with externals, forum)

Good things we like : 
- https://github.com/matrix-org/matrix-js-sdk/pull/2921
- https://github.com/matrix-org/matrix-react-sdk/pull/9559
- https://github.com/matrix-org/matrix-react-sdk/pull/9706
- https://github.com/matrix-org/matrix-react-sdk/pull/9596
- vector-im/element-web#19074


UX breaking changes (check translation):
- https://github.com/matrix-org/matrix-react-sdk/pull/9501
- https://github.com/matrix-org/matrix-react-sdk/pull/9497
- https://github.com/matrix-org/matrix-react-sdk/pull/9487
- https://github.com/matrix-org/matrix-react-sdk/pull/9403 : check if we need to hide QR code section
- https://github.com/matrix-org/matrix-react-sdk/pull/9447
- https://github.com/matrix-org/matrix-react-sdk/pull/9539
- https://github.com/matrix-org/matrix-react-sdk/pull/8759
- https://github.com/vector-im/element-web/issues/19074
- https://github.com/matrix-org/matrix-react-sdk/pull/9596
- https://github.com/matrix-org/matrix-react-sdk/pull/9662
- https://github.com/matrix-org/matrix-react-sdk/pull/9717
- https://github.com/matrix-org/matrix-react-sdk/pull/9533

Not in release : 
- https://github.com/matrix-org/matrix-react-sdk/pull/9544 => not in release v3.63.0

**Comment by mcalinghee** [comment]
Next steps : Upgrade element-web on a new branch for testing "Warnings" and "UX impacts" by following : https://github.com/tchapgouv/tchap-web-v4/wiki/Upgrade-Element-Web

**Comment by odelcroi** [comment]
warning : 
- [ ] cherry pick this if not present https://github.com/matrix-org/matrix-js-sdk/pull/3029
