### ISSUE TITLE
When starting a DM, info message falsely says "Encryption is not enabled"

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#313]
Create a new DM. 
Before you write the first message, the DM is not actually created yet, you see (but maybe not every time ? todo : reproduce it)

![image(4)](https://user-images.githubusercontent.com/911434/203350489-c76fd6e5-31ff-46b5-a64d-88311afeecbc.png)

This is confusing because DMs should have encryption.
(to test : is the created DM encrypted or not ?)

**Comment by odelcroi** [comment]
Can not reproduce in dev or prod, closing for now, feel free to reopen
