### ISSUE TITLE
Device Verification v4-> iphone : Display QR Code

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#319]
1. Click on "Verify" on a new session with iphone :
<img width="1021" alt="Screenshot 2022-11-28 at 12 20 23" src="https://user-images.githubusercontent.com/3725676/204291011-dad25928-5be8-4c28-bbe6-0b1067ab724f.png">

2. A QR Code is suggested to verify the device
![image](https://user-images.githubusercontent.com/3725676/204291271-e585762e-ecf5-4cb9-8104-dc78ccb8cbfa.png)

3. When the verification is a success the pop "Verification Cancelled" is displayed (https://github.com/tchapgouv/tchap-web-v4/issues/318): 
<img width="748" alt="Screenshot 2022-11-28 at 12 34 31" src="https://user-images.githubusercontent.com/3725676/204268022-ab195779-f2d2-4dab-927d-067be6881abb.png">

Note that we have this setup on the cross-signing : 
<img width="363" alt="image" src="https://user-images.githubusercontent.com/3725676/206221029-3cbe94f2-5737-4ad3-ad2f-87c295d1eb44.png">

Devices: 
- iOS App Version : 2.0.5
- tchap-web-v4 : 4.1.0_1.11.10

**Comment by mcalinghee** [comment]
I did not have the cross-signing activated on this account and somehow I have : `Cross-signing public keys: | in memory`

**Comment by odelcroi** [comment]
can be duplidates of #202
