### ISSUE TITLE
CORS error when calling backend

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#32]
Probably when trying to get the list of rooms for the space, on the space home page (but could be somewhere else)

Error : 
Access to XMLHttpRequest at 'https://matrix.i.tchap.gouv.fr/_matrix/client/v1/rooms/!WchQQCfkUFCpZYmTGe%3Ai.tchap.gouv.fr/hierarchy?suggested_only=true&max_depth=1&limit=20' from origin 'https://app.preprod.tchap.incubateur.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by estellecomment** [comment]
This could be because we are calling a backend api which doesn't exist, so the default CORS settings are returned, which causes a CORS fail.

The dev backend is the first one to have these new APIs, see if the problem doesn't happen in dev.

**Comment by odelcroi** [comment]
I can't reproduce with Tchap Tartine, feel free to reopen if happens again
