### ISSUE TITLE
Url /login redirects to Login page even if a session is already opened

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#325]
**Steps to reproduce:**
- Take a test account to perform the following steps
- Open a session in Tchap web : you can see tchap-web opened as usual
- Open a new tab in your browser and go to /#/login (ie. https://www.tchap.gouv.fr/#/login)
- Login Page appears, sign-in into tchap-web again
- You have 2 sessions of tchap-web with the same base url and device
=> this might cause the replacement of E2E keys in the cookies of the first session by the second opened session and therefore the lost of E2E keys of the first session (this first session would have allow the decryption of all the historical messages)

**Comment by odelcroi** [comment]
This bug is not present on : https://app.element.io/#/login

**Comment by odelcroi** [comment]
Not reproduced on https://app-v4.prod.tchap.incubateur.net/#/login with Version de Tchap : 4.1.3_1.11.12
Version de Olm : 3.2.12

Not reproduced on https://www.tchap.incubateur.net/ with Version de Tchap : 4.1.1_1.11.12
Version de Olm : 3.2.12

Reproduced in : https://www.beta.tchap.gouv.fr/ with Version de Tchap : 4.1.0_1.11.10
Version de Olm : 3.2.12

**Comment by jdauphant** [comment]
Not reproduced in the last version in prod with version de Tchap : 4.1.3_1.11.12
Version de Olm : 3.2.12
Brave / Linux

**Comment by odelcroi** [comment]
> Not reproduced in the last version in prod with version de Tchap : 4.1.3_1.11.12 Version de Olm : 3.2.12

which browser/platform?

**Comment by jdauphant** [comment]
Not reproduced in the last version in prod with version de Tchap : 4.1.3_1.11.12
Version de Olm : 3.2.12
Firefox / Linux

**Comment by odelcroi** [comment]
Tested on firefox and chrome : 
Not reproduced on https://www.tchap.incubateur.net/ with Version de Tchap : 4.1.3_1.11.12
Version de Olm : 3.2.12

Not  Reproduced in : https://www.beta.tchap.gouv.fr/ with Version de Tchap : 4.1.3_1.11.12
Version de Olm : 3.2.12
