### ISSUE TITLE
Confirmation window when leaving a room for an admin

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#335]
### Step to reproduce
**In V4:**
1. Create a private room
2. Invite another user
3. Leave the room
4. A confirmation box should appears
5. The confirmation is not alerting that you are the last admin and that no one else can administrate the room

<img width="743" alt="image" src="https://user-images.githubusercontent.com/3725676/206457766-af12d94b-93f5-424c-a534-1d74f16dcfb3.png">

### More information 
**In V2 :** 
English:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3725676/206457804-dc8ff795-fd27-43ac-9b75-2a69ea72ed9a.png">

French:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3725676/206458526-433ca14f-ca4e-48f9-a89c-a7ae9e90d29a.png">

### Impact on users
Administrators can leave room without warning and no administrators is there anymore in the private room.

### Question
1. Do we need to implement this feature?
2. Should it be in tchap-web-v4 or in element-web directly?

**Comment by jdauphant** [comment]
Should be in Element Web.

Did you see : 
https://github.com/matrix-org/synapse-freeze-room
It's planned to be activated in mainlining
