### ISSUE TITLE
Clear browser cache when upgrading v4 

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#339]
Could it possible to clear browser cache when migrating from v2 to v4 ? 
This code is called : 
```
index.ts:
        if (needRefreshForV4) {
            queueClearCacheAndReload();
        }
```

**Comment by odelcroi** [comment]
- https://developer.mozilla.org/en-US/docs/Web/API/Location/reload : forceReload is only supported by firefox
- Firefox is 74%, Chrome is 22%, Safari 4% : https://stats.tchap.incubateur.net/question/83-repartitions-des-appareils-mois-dernier-avec-compte-double-pour-les-utilisateurs-qui-se-reconnectent
