### ISSUE TITLE
Text change when using general search

### ISSUE THREAD

**Issue by Caroline-lawson** [tchapgouv/tchap-web-v4#347]
### Your use case

When using the search box top left of the page:
![image](https://user-images.githubusercontent.com/78041311/207709269-60ece721-7aa9-458e-8230-6fe974978591.png)

#### What would you like to do?
Add a missing word to the sentence: "Pour chercher des messages, repérez cette icône en d'un salon".

#### Why would you like to do it?
Bcse it's incorrect.

#### How would you like to achieve it?
"Pour chercher des messages, repérez cette icône en haut à droite d'un salon"

**Comment by odelcroi** [comment]
suggestion made to Element https://translate.element.io/translate/element-web
