### ISSUE TITLE
Tchap Web is not loading on Firefox 68

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#349]
### Steps to reproduce

1. Go to : https://www.tchap.gouv.fr/

#### What did you expect?
I expect Tchap to load the welcome page
#### What happened instead?
Tchap is not loading and a blank page appears and a syntax error appears also
<img width="945" alt="image" src="https://user-images.githubusercontent.com/3725676/207906955-fb20f034-0a37-46ed-838e-34237a359353.png">

This is happening with Firefox 68.12.0esr (64 bits)

### Operating system

Windows

### Browser information

Firefox 68.12.0esr (64 bits)

### URL for webapp

tchap.gouv.fr

### Application version

Version de Tchap : 4.1.4_1.11.12 Version de Olm : 3.2.12

### Will you send logs?

No

**Comment by odelcroi** [comment]
This is an occurence of a s flag : https://github.com/matrix-org/matrix-react-sdk/blob/09372fbe8c61ebf17852fac18bf92f1bee34a918/src/utils/exportUtils/PlainTextExport.ts#L51

**Comment by mcalinghee** [comment]
More information on the error ` SyntaxError : invalid regular expression flag s`
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag
- https://bugzilla.mozilla.org/show_bug.cgi?id=1579867

It was seen in FF 68.0.2 and 69.0

**Comment by mcalinghee** [comment]
On Element , it is clear that the browser will not be supported : 
Snapshot with FF 68.0.2ESR : 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/3725676/208059709-f24049fe-5377-496c-8156-c6d80bc099f8.png">

**Comment by mcalinghee** [comment]
Firefox 68.12.0ESR : [End-of-life 68.x.x product line](https://wiki.mozilla.org/Release_Management/Calendar) on September 22, 2020 => Mozilla is not supporting these versions anymore.
More information on : https://en.wikipedia.org/wiki/Firefox_version_history#Firefox_68_through_77

We will not be able to support older browsers for security reasons.

**Comment by mcalinghee** [comment]
Update the readme to change "Element" towards "Tchap"

**Comment by odelcroi** [comment]
Define which are the required platforms : https://github.com/tchapgouv/tchap-web-v4/issues/351

**Comment by jdauphant** [comment]
@odelcroi we can send tchap V2 to firefox 68 from nginx
