### ISSUE TITLE
Enhance error message when encountering the UISI bug (or bug N..)

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#350]
https://github.com/tchapgouv/tchap-web-v4/blob/d395c733779cfbe095b4084ff9a4047cc04e26ea/src/components/views/messages/TchapUnknownBody.tsx#L18

This message say that "Decryption fail: Please open Tchap on an other connected device to allow key sharing." but there is also the case when the keys haven't been received from the recipient.

The crypto lib have the good error :
![image](https://user-images.githubusercontent.com/1238254/208550544-62ca162b-eb53-4a64-8d2a-13921364b841.png)
And following error with the same missing key : 
![image](https://user-images.githubusercontent.com/1238254/208550989-b71e7f83-0b17-490d-bd16-940b037c3184.png)

I recommand, remove the hack and translate the error message provided by the crypto lib.

**Comment by mcalinghee** [comment]
After some analysis and this is not as trivial as we could think.

Here are some suggestions on how to implement this translation :
**Solution 1 :** 
do the implementation with patch-package on the module matrix-js-sdk

benefits : easier solution than solution 2, and will take less time to have this in production
drawback : the code on the crypto layer is changing very often (every week) and conflict will happen often when upgrading our codebase

**Solution 2 :** 
do the implementation directly in project : https://github.com/matrix-org/matrix-js-sdk

benefits : this is more accurate and long term solution, should not cause regression
drawback : will take some time to get this done and also the crypto layer might change in the coming weeks/months
=> Issue that we could suggest to element : https://github.com/tchapgouv/tchap-web-v4/issues/357

**Solution 3 :** 
we can only translate static translation (as opposed to parameterized translation) or we could translate the most common errors to start with and add translation when they are coming through support.
benefits : easiest solution as we would have to add to only the translations(only tchap_translations.json) and quickest to implement, easier to maintain also 
drawback : we have a lot of translation which are parameterized and they cannot be covered in a generic way with this solution, and not all errors will be translated but we translate this when the english errors will be highlighted through the support channel
=> PR for this solution can be found here : https://github.com/tchapgouv/tchap-web-v4/pull/355

**Comment by estellecomment** [comment]
EDIT

Todo/ideas : 
 - [ ] this PR in tchap-web https://github.com/tchapgouv/tchap-web-v4/pull/355/files
 - [x] make some changes in element-web : https://github.com/tchapgouv/tchap-web-v4/issues/357 : element has done some work here
 - [x] add a link to a specific help page in the error message, for the user to find actions for solving : we cannot integrate url links through translations, also we have now a banner for Decryption Error in : https://github.com/matrix-org/matrix-react-sdk/pull/9544

**Comment by mcalinghee** [comment]
Element is changing the appearance of the Decryption Error : https://github.com/matrix-org/matrix-react-sdk/pull/9544
This should be there in the next release, in the meantime I suggest we try to review this PR as it is to give more clarity on the real source of the error

**Comment by odelcroi** [comment]
What's been discover impacting our two main use cases, the error is the
same :
- when user lost its key
- when the sender does not send the key (uisi bug)

Then we can not differentiate the UX between those two use cases :(

**Comment by mcalinghee** [comment]
- `The sender's device has not sent us the keys for this message.` can appear in 2 scenarios:
  - after logging into v4 and when **no** Tchap Keys/E2E Keys have been imported
  - when bug N occurs

**Comment by odelcroi** [comment]
this issue should be reopen in regards to the new component in 4.2
