### ISSUE TITLE
Cannot create a public room only visible by the source homeserver

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#353]
### Steps to reproduce

1. Go to tchap-web-v4 
2. Create a forum room (public room)

#### What did you expect?
We should expect an option to activate the federation or not
As it was in v2 or in mobile: 
![image](https://user-images.githubusercontent.com/3725676/209350031-0c000ae0-3fd9-4a28-ac3c-e5d2b384ef96.png)

#### What happened instead?
No option is there when creating a public room and therefore:
- the public room is always discoverable by all homeservers.
- we cannot create a public room which is only accessible by a specific homeserver

### Will you send logs?

No

**Comment by jdauphant** [comment]
It's not a bug, the visibility of this feature have been reduced.

**Comment by mcalinghee** [comment]
Closing this issue : we might want to adapt mobile clients

**Comment by mcalinghee** [comment]
Might wanna use the `Space` feature for this matter
