### ISSUE TITLE
Element Metadata still in the app

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#356]
### Steps to reproduce

Send a link with a tool that retreive link meta data : 
![image](https://user-images.githubusercontent.com/1238254/210218709-59899bd8-1c7c-4e18-9762-39205b451fe7.png)

#### What did you expect?
Tchap icon 

#### What happened instead?
Element icon

### Will you send logs?

Yes

**Comment by estellecomment** [comment]
Probably coming from https://www.tchap.gouv.fr/manifest.json
The icons with names like AAAxBBB.png are element icons.
