### ISSUE TITLE
When a patch fails during an upgrade, the error log is too hard to understand

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#361]
When we upgrade element-web, and run "yarn install", the postinstall runs after yarn install, which applies patches. We expect some patches to break, this is normal since matrix-react-sdk and matrix-js-sdk can have changed. 
In this case, we want the postinstall to crash and explain why it is crashing.

Expected : 
The log explains clearly what happened : the break comes from patch-package, and the patch that failed is <name of patch>.

Obtained :
The log messages from "apply_patches.sh" are missing, which makes the error hard to track down.

Notes : 
 - the process to figure it out is to remove the postinstall from package.json, so that yarn install runs fully (without postinstall) and then run postinstall separately, which gives understandable errors.
  - This is probably because the crash on error is "dirty", it doesn't exit cleanly and empty its log buffers ? Is this coming from "--exit-on-fail" ? 
 - We do need postinstall to crash, because we want to know there is a problem. Removing the crash completely is not a solution.

**Comment by jdauphant** [comment]
@odelcroi with the new script merge_patchs.sh , I think we can close this issue

**Comment by odelcroi** [comment]
when --exit-on-fail is removed, the patch fails silently but the log is not easier to read

**Comment by odelcroi** [comment]
> @odelcroi with the new script merge_patchs.sh , I think we can close this issue

No, this error happens when applying the patch, not merging them

**Comment by estellecomment** [comment]
One cause is that patch-package is not logging the right patch-dir, so we cannot tell which patch has errored.
I submitted the fix to patch-package : https://github.com/ds300/patch-package/issues/488

**Comment by estellecomment** [comment]
... and the corresponding fix for tchap-web : https://github.com/tchapgouv/tchap-web-v4/pull/683

This is a partial fix : postinstall seems to eat the logs in various ways, and sometimes it will output the patch-package log, in which case this fix will help (we'll get the right info from the log). When all logs are eaten by postinstall, it doesn't help.

(a better fix is to stop postinstall from eating logs...)

**Comment by estellecomment** [comment]
looks like #684 is a fix ! 🥳
