### ISSUE TITLE
Intradef users cannot invite in a private room users from other homeserver

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#370]
### Steps to reproduce

1. Go to tchap-web-v4 
2. Log in with Intradef account
3. Create a private room
4. Invite a user from another homeserver

#### What did you expect?
We should be able to invite a user from another homeserver

#### What happened instead?
An error is occuring when performing the invite.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3725676/211815720-bd2c7a20-93ea-4114-b766-0d3e339ff550.png">

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3725676/211815488-1f411706-49b7-4d43-8008-49aad5d5d461.png">

### Will you send logs?

No

**Comment by odelcroi** [comment]
is this linked? https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_7186aebe-9ad7-4e79-ba7d-5458ce34f3e8/

**Comment by odelcroi** [comment]
is there any other support case?

**Comment by jdauphant** [comment]
Close https://github.com/tchapgouv/tchap-support/issues/56

All Intradef room created by web are unfederated, they can't invite other instance to their room (including external users).
All private rooms created by web V4 need to be recreated.

**Comment by jdauphant** [comment]
Closed by #446
