### ISSUE TITLE
Activate XS and Secure Storage

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#378]
### Your use case
lister les actions à prendre pour reactiver le cross signing : 
- [x] modify patch : https://github.com/tchapgouv/tchap-web-v4/tree/develop_tchap/patches/disable-cross-signing-and-enable-logout-devices-when-changing-password
- [x] is this patch still necessary? https://github.com/tchapgouv/tchap-web-v4/blob/develop_tchap/patches/fix-key-request/matrix-react-sdk%2B3.57.0.patch
- [x] https://github.com/tchapgouv/tchap-web-v4/tree/develop_tchap/patches/hide-cross-signing-actions
- [x] https://github.com/tchapgouv/tchap-web-v4/tree/develop_tchap/patches/hide-secure-storage

- [x] Construire un plan de test en commun avec les mobiles

**Comment by estellecomment** [comment]
epic : https://github.com/tchapgouv/tchap-design/issues/100
