### ISSUE TITLE
Trying to launch mobile device verification after web login: no verification is shown

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#380]
### Steps to reproduce

Logout from your web session. 
Stay logged in on your mobile session. 
Write messages on 1 to 1 and closed group.
Login again on your web session.
You are not asked for an icon verification. 
Yet the messages are decrypted.

Tchap web : Version de Tchap : 4.1.4_1.11.17, on MacOs
Ios : ventura 13.0

Operating system
macOs

Browser information
Chrome 108.0.5359.94

URL for webapp
http://localhost:8080/

Application version
Version de Tchap : btchap

### Outcome

You are not asked for an icon verification. Yet the messages are decrypted.

### Will you send logs?

No

**Comment by odelcroi** [comment]
With a fresh newly created account on the review app attached to the [PR](https://github.com/tchapgouv/tchap-web-v4/pull/362) 
- not reproduced with 2 chrome sessions 
- not reproduced with 1 chrome session and 1 ios session
- not reproduced with 1 chrome session and 1 android session

When tested with fresh account beware of this bug : https://github.com/tchapgouv/tchap-web-v4/issues/333

**Comment by aulamber** [comment]
Bug not reproduced with a clean account
