### ISSUE TITLE
Update text for new Forgot password

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#384]
Since our upgrade to element-web 1.11.17, we have the new "forgot password" flow, which caused some new text to appear, and we need to make it tchap-compatible.

- [ ] "Se connecter à la place" sounds weird to me, we can find better I'm sure
- [ ] Title "Réinitialise le mot de passe" should be "Réinitialisez"
- [ ] "Pas reçues" should be "Pas reçu"
- [ ] do we use "e-mail", "email", "adresse mail", something else ?

Screenshots can be seen in this PR : https://github.com/tchapgouv/tchap-web-v4/pull/373

**Comment by Caroline-lawson** [comment]
**"Se connecter à la place" sounds weird to me, we can find better I'm sure**
How about "ou connectez-vous"?

On that same screen, could we talk about "votre mot de passe" rather than "le mot de passe" ? To make it more personal?

 **Title "Réinitialise le mot de passe" should be "Réinitialisez"**
or "Réinitialisez votre mot de passe"?

**"Pas reçues" should be "Pas reçu"**
I agree.

**do we use "e-mail", "email", "adresse mail", something else ?**
We use "adresse mail".

**Comment by estellecomment** [comment]
Thanks @Caroline-lawson . 
I made the changes, you can review with the screenshots below.

Another point : for email messages, element uses "e-mail" in french, as you can see on the screenshots. If Tchap has a different convention we can change. (if it's not important, then we can just keep the same words as element, it avoids having to maintain changes)

<img width="710" alt="Screen Shot 2023-01-24 at 10 21 31 AM" src="https://user-images.githubusercontent.com/911434/214255138-fc4feb4e-b98a-445d-9a9b-7878f16bfa12.png">
<img width="709" alt="Screen Shot 2023-01-24 at 10 21 48 AM" src="https://user-images.githubusercontent.com/911434/214255150-92e0230c-e9a8-4fb7-b19b-0db2d0b3dbfc.png">
<img width="711" alt="Screen Shot 2023-01-24 at 10 22 04 AM" src="https://user-images.githubusercontent.com/911434/214255154-f4838785-98b0-46f3-85c1-6c5eef0d8fa1.png">
<img width="766" alt="Screen Shot 2023-01-24 at 10 22 32 AM" src="https://user-images.githubusercontent.com/911434/214255157-af2c2e81-f656-4e63-9a2b-a7f2bd6e78f5.png">
<img width="716" alt="Screen Shot 2023-01-24 at 10 22 44 AM" src="https://user-images.githubusercontent.com/911434/214255161-4aa3e5b2-ff89-41cd-8d25-767f04342eda.png">
<img width="717" alt="Screen Shot 2023-01-24 at 10 23 50 AM" src="https://user-images.githubusercontent.com/911434/214255166-f12da9ab-ed14-4545-bce9-b640cdb5fdc5.png">

**Comment by Caroline-lawson** [comment]
We have been using "**mail**" in French for "e-mail" as much as possible throughout Tchap and FAQ. I think it's best if we stick to "mail" if it isn't too complicated to do.

![image](https://user-images.githubusercontent.com/78041311/214259495-f729c21e-ade2-4e4e-96ac-8f4ba0c51622.png)
"vos e-mail" should be "**vos mails**".

![image](https://user-images.githubusercontent.com/78041311/214260140-8d3a9d15-2fe6-497c-a243-14129a82393f.png)
"vos e-mail" should be "**vos mails**".
"Cliquer sur le lien dans l'e-mail" should be "**Cliquez sur le lien dans le mail**".

**Comment by estellecomment** [comment]
Alright ! final version ! I used "mail" instead of "email" everywhere.

<img width="715" alt="Screen Shot 2023-01-24 at 11 27 40 AM" src="https://user-images.githubusercontent.com/911434/214275531-23405276-cd2f-446f-ab91-1ba5a14ff416.png">
<img width="718" alt="Screen Shot 2023-01-24 at 11 27 57 AM" src="https://user-images.githubusercontent.com/911434/214275544-b2f27e70-e219-44c6-b8bb-5c344eb84a17.png">
<img width="711" alt="Screen Shot 2023-01-24 at 11 28 08 AM" src="https://user-images.githubusercontent.com/911434/214275554-25d61aab-e381-46db-b8d1-6efbac690353.png">
<img width="758" alt="Screen Shot 2023-01-24 at 11 28 28 AM" src="https://user-images.githubusercontent.com/911434/214275574-b76322b9-2883-4a11-8f8c-6e085ee11a1a.png">
<img width="719" alt="Screen Shot 2023-01-24 at 12 01 53 PM" src="https://user-images.githubusercontent.com/911434/214275582-348336e7-94ea-4cb4-801d-2b79bf5618e2.png">

**Comment by estellecomment** [comment]
ok to merge @Caroline-lawson ?
