### ISSUE TITLE
Move all tchap code in single dir - for linting, and because it's clearer

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#385]
Things would be simpler if all tchap code was in a single directory, so that we would only lint our own files. See this PR : https://github.com/tchapgouv/tchap-web-v4/pull/383

Also nice for devs to understand which code is which : element's code and ours are mixed so if you weren't the one to write the files, you don't know if they're tchap or element.

**Comment by odelcroi** [comment]
all js code has been moved to a single src/tchap single directory
