### ISSUE TITLE
Confusing error message when inviting a person already present in the room

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#394]
This issue happens when trying to invite **by its email** a person that is already in the room.

- Create a private room 
- invite a user
- wait for the user to enter the room
- invite the same user by EMAIL

error in logs
<img width="973" alt="Capture d’écran 2023-01-25 à 16 29 15" src="https://user-images.githubusercontent.com/4077729/214607715-bda6fad8-5d17-4cf5-b55c-a75a898585ca.png">

<img width="767" alt="Capture d’écran 2023-01-25 à 16 39 57" src="https://user-images.githubusercontent.com/4077729/214610082-eaa8e955-0e64-42ed-ad62-68b0e324a71a.png">

Version de Tchap : 4.1.4_1.11.12
Version de Olm : 3.2.12
url : www.tchap.gouv.fr

**Comment by mcalinghee** [comment]
More scenarios : 
**Scenario 2 :** As a consequence, invite by email of an user already in the room when inviting massively (comma separated list) cause the rest of the list of invitation unprocessed : the invitation of the rest of the users are not invited
**Scenario 3 :** invite by email of an external user(invited by education) in a external room(administrated by education) is not working properly : the same http error and the same gui `You do not have permission to invite` => we might need to create an issue in synapse-tchap to provide a fix

**Comment by Delphgateau** [comment]
Exemples tickets Crisp : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_28d39fa8-c496-4eda-9e63-4484becde129/
ou
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_7d5daa42-8af3-46d1-a3b3-45a3c0e53642/

**Comment by odelcroi** [comment]
> Scenario 3 : invite by email of an external user(invited by education) in a external room(administrated by education) is not working properly : the same http error and the same gui You do not have permission to invite => we might need to create an issue in synapse-tchap to provide a fix

This scenario seems a valid scenario, why would it break? Should it be another issue? Did you reproduce it?

**Comment by odelcroi** [comment]
- [x] Not reproduced on iOs 2.3.2 (2)
- [ ] android : TODO

![IMG_E24EF1BD5F8A-1](https://user-images.githubusercontent.com/4077729/219678111-1bb00260-8848-4daa-9cc2-55c9587b465c.png)

**Comment by odelcroi** [comment]
blocked user : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_f5cd496a-fa88-4462-a83e-06112d1cca46/

**Comment by odelcroi** [comment]
it seems that if the invitation is revoked the problem is the same : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_a4999d3a-a379-4145-810d-c90539dc5b9c/

**Comment by odelcroi** [comment]
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_79dc806e-8e3f-4b0c-8d20-72a38c70c647/

**Comment by jdauphant** [comment]
On n'a le même soucis dans Element ?
On peut le fixé dans Element ?

**Comment by odelcroi** [comment]
- Reproduced with element web on tchap dinum home server 
![Image](https://user-images.githubusercontent.com/4077729/222441034-a1733ae8-75b8-4828-813e-87c3f667d9ff.png)

- Not reproduced with element web and matrix home server

**Comment by odelcroi** [comment]
The behaviour from the home server is specified [here](https://matrix.org/docs/spec/r0.0.0/client_server.html#id39). It is what is expected from the endpoint
