### ISSUE TITLE
Améliorer la visibilité de la FAQ

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#395]
Par exemple, ajouter un lien vers le menu
![Capture d’écran 2023-01-26 à 16 36 14](https://user-images.githubusercontent.com/4077729/214879556-df3320de-8d7f-4e7e-92e9-aa33010a0f3e.png)

**Comment by areox-net** [comment]
For more clarity and consistency across platforms, the tab should be names "Foire Aux Questions". 
"Aide" could be understood as a link to Support.

**Comment by Delphgateau** [comment]
La FAQ n'est pas assez visible sur Tchap web

4 clics pour y parvenir via le bouton "engrenage" : paramètres -> plus d'options -> aide et à propos -> consulter la FAQ
ou 3 clics -> paramètres -> tous les paramètres -> consulter la FAQ
Proposition : 
1) Epingler un bouton "Foire aux questions" à la barre latérale des paramètres du symbole engrenage
2) Mettre la même vue pour les deux boutons qui donnent accès aux paramètres:  la vue des paramètres du haut (photo de profil) est mieux que celle du bouton des paramètres "symbôle engrenage"

**Comment by areox-net** [comment]
@Delphgateau Elle plus facilement accessible depuis la bouton **Profil** (photo avatar en haut à gauche).
![Screenshot 2024-01-22 at 10 47 12](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/f202ab7d-8323-4404-ac7d-7ce5fcc44aae)

Il s'agit peut-etre plus de revoir l'utilité du bouton **Parametres** en bas à gauche. Il apporte plus de confusion que de raccourcis utiles.

**Comment by Delphgateau** [comment]
@areox-net les utilisateurs ne pensent pas à cliquer sur leur photo de profil pour accéder aux paramètres. Ils cliquent sur le bouton engrenage qui est plus intuitif.
Peut-être qu'il faudrait qu'un seul bouton pour accéder aux paramètres, en haut ?

**Comment by areox-net** [comment]
@Delphgateau Oui, je pense qu'il faut un seul endroit. 
Je ne suis pas fan du clic sur la photo mais c'est un choix design Element qu'on retrouve sur mobile. 
Une solution peu couteuse pourrait etre d'ajouter une icone parametre au niveau de la photo profil.

**Comment by odelcroi** [comment]
Est-ce possible de cacher le bouton "parametres rapide", comme cela l'unique chemin est de cliquer sur la photo de profil?

**Comment by Nivann** [comment]
Malgré les évolutions récentes des clients, certains utilisateurs se plaignent de ne pas savoir comment : 

- Obtenir de l'aide
- Contacter le support 
- Accéder à un guide de prise en main

Quelques exemples de comportement utilisateur : 

Ne pas savoir qui contacter lorsque il rencontre une difficulté dans Tchap. 
Ne sait pas comment envoyer un rapport d'erreur.
Ignore l'existence de la FAQ. 

Solutions à tester : 

- Pouvoir créer un rapport d'erreur comme à la création d'une nouvelle privée : "commencer une nouvelle conversation privée // envoyer un rapport d'erreur"

- Pop-up "besoin d'aide ? Consulter notre guide de prise en main". 

- Rendre le menu des paramètres plus visible : bouton paramètres, ou réglages, en toutes lettres.

**Comment by areox-net** [comment]
@Nivann Je ne suis pas fan de la solution dans le bouton + . Ca peut faire penser que un message avec le support sera créé dans la liste des conversations. 

Je propose plutot cette solution: une icone "Aide" dans la barre bleue sur Web et en haut à droite sur mobile.
Au clic on affiche 3 liens: FAQ, Contacter le support, Prise en Main 

![Screenshot 2024-06-18 at 18 06 39](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/f1b2188c-2563-4e16-b374-09d7bb14442b)

![Screenshot 2024-06-18 at 17 27 16](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/36cb0566-8cad-4185-baea-35c109603582)

**Comment by Delphgateau** [comment]
J'aime beaucoup l'idée du bouton aide qui amène sur ces trois choix 👍

**Comment by julie-ri** [comment]
je propose de mettre le ticket dans le prochain sprint :) c'est super ta proposition @areox-net

**Comment by julie-ri** [comment]
est-ce que c'est un problème remonté uniquement sur web @Nivann @Delphgateau  ?

**Comment by Delphgateau** [comment]
@julie-ri oui surtout web mais on peut aligner sur les 3 clients, c'est bien les liens vers l'adresse support et le guide de prise en main

**Comment by julie-ri** [comment]
je propose qu'on le fasse deja sur web. Est-ce qu'on pourra reprendre ces ajustements sur les deux clients (@yostyle ?)  une fois qu'on sera sur Element X ? Je trouve que c'est un sujet vraiment important et je pense qu'on devrait faire ces ajustements car on fait de l'acquisition de  nouveaux users en ce moment

**Comment by areox-net** [comment]
@MarcWadai Je viens de voir en prod lab. C'est très bien, mais du coup je me demande s'il faut garder le lien "Aide" dans le menu au clic sur l'image profil. 
Je pense que à minima il faudrait renommer ce lien en "Foire aux Questions" pour cohérence.

@Delphgateau Penses-tu qui si on enleve le lien du menu user on perd des gens qui savent qu'il est là actuellement ?

**Comment by Delphgateau** [comment]
@areox-net non je ne pense pas que ça va chambouler tant. SI l'idée est de mettre une icône "?" en dessous de la photo de profil, ça me parait plus clair.

**Comment by areox-net** [comment]
@Delphgateau Je deconseille de bouger l'icone "?" sous l'avater. Ca casse la structure Element et le menu de droite. 

Par contre je trouve que maintenant on a trop d'accès différents à deux endroits:
![Capture d’écran 2024-07-17 à 10 57 48](https://github.com/user-attachments/assets/d409dfb1-a65b-4b5a-ab0a-c4b029b9901d)

Entre ce menu et le menu "?" on a:

- Commentaire, modale de feedback et remonté bug à l'équipe
- Aide, lien vers FAQ
- Foire aux Questions, doublon avec Aide
- Contacter le support, lien vers mail support@tchap.beta.gouv.fr (un peu doublon avec "Commentaire")
- Prise en Main

Je propose de tout rassembler dans le menu "?" avec le wording suivant:
- Foire aux Questions
- Prise en Main
- Partager un commentaire
- Contacter le support

@Delphgateau Penses-tu qu'on a besoin du commentaire ET du mail direct vers le support ? Le commentaire va déjà sur Crisp, non ? Je preferais avoir que 3 lliens.

**Comment by Delphgateau** [comment]
@areox-net oui j'avais pas vu que le menu ? était en bas, c'est top comme ça.
 Je suis d'accord, "commentaire" ne sert à rien on peut l'enlever. On peut mettre "Tous les paramètres", "Notifs", "Sécurité et vie privée" et "Se déconnecter" dans le menu du haut.
D'ailleurs je me demande si "Sécurité et vie privée" c'est parlant pour les users. On pourrait pas chercher des alternatives et demander aux utilisateurs leur avis ? Les ambassadeurs par ex.

**Comment by areox-net** [comment]
@Delphgateau Je suis d'accord. Il faudrait aussi étudier la necessité de laissrr "Se deconnecter" ici. je le verrais plutot dans les settings pour éviter que les gens se deconnectent trop facilement. On fait ça sur mobile.

**Comment by MarcWadai** [comment]
@areox-net @Delphgateau je propose de continuer cette tache/étude dans un nouveau ticket cf :arrow_up:  :)
