### ISSUE TITLE
when the secure storage is not configured, a warning shows every time i'm logging in

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#399]
steps to reproduce : 
- create an account 
- connect to tchap web xsss ready
- do not configure neither the secure storage nor the xs
- logout
- login
- the **key backup panel warning** is displayed each time

<img width="687" alt="Capture d’écran 2023-01-30 à 15 51 57" src="https://user-images.githubusercontent.com/4077729/215511381-1cec2bd2-e13e-45fd-8166-2cdb88bb95f6.png">

<img width="687" alt="Capture d’écran 2023-01-30 à 15 52 28" src="https://user-images.githubusercontent.com/4077729/215511434-81be73f3-9477-4384-b663-df85cedc2a42.png">

<img width="612" alt="Capture d’écran 2023-01-30 à 15 53 21" src="https://user-images.githubusercontent.com/4077729/215511507-96b1026f-d64c-4ada-a724-4f5c67e001d8.png">

<img width="735" alt="Capture d’écran 2023-01-30 à 15 52 55" src="https://user-images.githubusercontent.com/4077729/215511501-2e576bbd-c366-43bb-bbae-44ab6bc641a8.png">

<img width="337" alt="Capture d’écran 2023-01-30 à 15 52 38" src="https://user-images.githubusercontent.com/4077729/215511492-04408f9c-3eef-44e8-8dcb-8d0fd5d85b5e.png">

**Comment by odelcroi** [comment]
@giomfo It seems that the xs does not activate if I don"t want to activate the secure storage, is my understanding correct?

**Comment by odelcroi** [comment]
this bug is already present in the actual version 4.1.5_1.11.12

**Comment by giomfo** [comment]
> @giomfo It seems that the xs does not activate if I don"t want to activate the key backup, is my understanding correct?

I'm not sure to understand your question (we should sync in direct on this point)
But you have to know that you loose the cross-signing configuration when you logout on your unique session (if you did not configure the secure storage at the same time)

**Comment by odelcroi** [comment]
- this process happens in two cases when :
   - 0 configuration has been done on the xsss
   - or 0 other session

**Comment by areox-net** [comment]
Here are the wording @Caroline-lawson and I suggest:

**! Activez la sauvegarde automatique des messages**
Activez cette fonction pour toujours récupérer vos messages et ne jamais les perdre.
> Activez

![SS-01](https://user-images.githubusercontent.com/1255251/217011551-0176aaf8-2559-4c87-9da3-fa0ecc779ae6.png)

_____

**Etes-vous sur ?**
Sans sauvegarde automatique vous n’aurez pas accès à tous vos messages !

![SS-02](https://user-images.githubusercontent.com/1255251/217011979-2b55a2b3-d4ca-4e2a-ab7d-8b51a3b64284.png)

______

_"Vérifier" becomes "Synchroniser"_

**Synchroniser cet appareil**
Synchroniser vos messages sur cet appareil pour ne jamais les perdre. 
> Synchroniser

![SS-03](https://user-images.githubusercontent.com/1255251/217012085-e63eb782-285e-4976-94e2-1f1e27b00fb1.png)

![SS-04](https://user-images.githubusercontent.com/1255251/217012360-1dc221fe-8e7a-4a2d-b0aa-117350804733.png)
