### ISSUE TITLE
When connecting a new device, device verification does not start automatically anymore

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#400]
In new version we have this invite : 
<img width="754" alt="Capture d’écran 2023-01-25 à 14 31 41" src="https://user-images.githubusercontent.com/4077729/215519915-168551d0-df10-4d24-9b08-373af9dc5e76.png">

That leads to this panel
![Capture d’écran 2023-01-26 à 11 53 05](https://user-images.githubusercontent.com/4077729/215520070-144a9c91-adc8-42eb-9c2f-59536c0e76df.png)

From there the user can start the verification by selecting the device and clcking on "Verify'

Instead we would like to have : 
- the verification to be started automatically to avoid going to settings panel

**Comment by giomfo** [comment]
filed in Element-web: https://github.com/vector-im/element-web/issues/24490

**Comment by odelcroi** [comment]
A new mecanism has been implemented in Element, going to the device list is needed anyway to check that the device is correct. Closing this issue
