### ISSUE TITLE
when secure storage is getting configured, there is no success panel

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#404]
Currently when successfully configuring the secure storage, there is no positive feedback.

Currently :
- panel closes

What we want : 
<img width="413" alt="Capture d’écran 2023-02-01 à 15 14 04" src="https://user-images.githubusercontent.com/4077729/216067319-d91a9bc9-afd2-4567-a29b-d2def1341f05.png">

**Comment by giomfo** [comment]
filed in Element-web : https://github.com/vector-im/element-web/issues/24487

**Comment by weeman1337** [comment]
The upstream issue has been solved :partying_face:

**Comment by estellecomment** [comment]
We now see the element dialog in Tchap : 

<img width="674" alt="Screen Shot 2023-02-27 at 12 26 38 PM" src="https://user-images.githubusercontent.com/911434/221552088-53eeb45b-eccf-4956-8c72-7fe305920508.png">

I think the content of the dialog may be changed to follow tchap's planned design, but that will be done in another issue. Closing.

**Comment by estellecomment** [comment]
Thank you @weeman1337 :)
