### ISSUE TITLE
When disconnecting, even if I have secure storage, I'm warned to backup my Tchap keys

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#408]
Should be keep this screen when users have secure storage activated? 

![Capture d’écran 2023-02-06 à 16 55 01](https://user-images.githubusercontent.com/4077729/217020086-f37465ed-4bd1-49f7-b815-6fa5cd29ca55.png)

**Comment by odelcroi** [comment]
Idea : if the secure storage is not active, propose it to the users

**Comment by estellecomment** [comment]
annoying for users but not a blocker for using xsss, so P2

**Comment by odelcroi** [comment]
has been deactivated with beta phase
