### ISSUE TITLE
Change wording synchronize > verify

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#420]
Changer:
![](https://user-images.githubusercontent.com/6305268/217305914-b2ab2661-735e-4d3c-9319-6c40108cd317.png)
en 
![](https://user-images.githubusercontent.com/4077729/215511492-04408f9c-3eef-44e8-8dcb-8d0fd5d85b5e.png)

Changer:
![](https://user-images.githubusercontent.com/6305268/217306521-740727cd-850a-45ae-b54f-bf5a00a5f744.png)
en
![](https://user-images.githubusercontent.com/4077729/215511507-96b1026f-d64c-4ada-a724-4f5c67e001d8.png)

Changer:
![](https://user-images.githubusercontent.com/1255251/217311359-09eb75cf-3998-48b8-b21a-d685a46eb91d.png)
en 
<img width="649" alt="Screenshot 2023-02-16 at 11 02 35" src="https://user-images.githubusercontent.com/6305268/219333479-8fc09ee2-7c06-45cb-b73f-b68da037804b.png">

**Comment by areox-net** [comment]
@aulamber Tout me parait bien. Y a t-il des écrans où tu as besoin de input design? Vu qu'on reviens sur les textes Element je sais pas si j'ai besoin de faire des maquettes.

**Comment by estellecomment** [comment]
Pour le premier, on utilise "session" ou "appareil" ? Il me semble qu'on avait enlevé "session" partout, pour utiliser "appareil" a la place.
