### ISSUE TITLE
Remove download button in "save key" dialog

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#421]
Remove **download** button only **copy** button should be left

![Capture d’écran 2023-02-16 à 10 59 39](https://user-images.githubusercontent.com/4077729/219332854-9d4710c8-80b2-46eb-9845-c8fb3ccd21b2.png)

**Comment by estellecomment** [comment]
Already present in develop_tchap : 
<img width="614" alt="Screen Shot 2023-02-27 at 12 18 19 PM" src="https://user-images.githubusercontent.com/911434/221550351-2e467378-01a0-4de7-a836-e32a9f9ee4c8.png">

Done in the PR for activating cross signing #388
