### ISSUE TITLE
Show the confirmation flag in green instead of blue

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#432]
After a confirmation by QRCode the mobile app show a green shield and the web app show a blue shield.
There is a question that said : do you see the same shield ?
Should be no because the shield haven't the same color.

To Do : use green color for the shield (maybe it should be patched in Element)

**Comment by estellecomment** [comment]
On web :
<img width="769" alt="Screen Shot 2023-02-27 at 11 16 00 AM" src="https://user-images.githubusercontent.com/911434/221536580-8f6798bd-692b-49d2-9bee-5685df5c8b58.png">

On android : 
![Photo on 2-27-23 at 11 16 AM](https://user-images.githubusercontent.com/911434/221537193-410fdbd3-8ae8-4776-8d6a-1b38add3a84e.jpg)
