### ISSUE TITLE
Missing translation : Envoyez votre premier message

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#434]
<img width="852" alt="Screen Shot 2023-02-23 at 2 34 41 PM" src="https://user-images.githubusercontent.com/911434/220922335-db7d9d31-51aa-4891-bc05-cf308ae1c84d.png">

When starting a DM.
Then when DM is created : 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/911434/220922589-03786d3f-1405-423d-8156-13de5ac2930a.png">

**Comment by odelcroi** [comment]
not reproduced, closing..
