### ISSUE TITLE
Cross signing UX : No way of exiting when shown the recovery key

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#435]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/911434/220928458-2733afee-204d-4353-a0dd-7e2ca5c78765.png">

No back button, no cross to close the modal. 
(you can still click outside the modal to exit)

**Comment by estellecomment** [comment]
not a blocker, P2

**Comment by odelcroi** [comment]
Agreed P3
