### ISSUE TITLE
study UX improvements for xsss

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#442]
We should adopt : 
- "Sauvegarde automatique des messages"
- "Code de récupération"

version : 4.1.7

- [x] adopt the wording mentionned earlier
- [x] maybe change the description also

<img width="713" alt="Capture d’écran 2023-03-01 à 10 11 55" src="https://user-images.githubusercontent.com/4077729/222094780-b8c65e66-0b2c-4655-bce3-228de0ead7a4.png">

----

- [x] "vérifier" or "vérifiez", choose one?

<img width="713" alt="Capture d’écran 2023-03-01 à 10 21 41" src="https://user-images.githubusercontent.com/4077729/222096972-9bd9e4d6-bd40-463c-88fa-8261a3580eb9.png">

----

- [x] Button "Envoyer" is not necessary (it is used for sending a FILE) as we do not propose to download a FILE it could be hidden.

<img width="787" alt="Capture d’écran 2023-03-01 à 10 23 47" src="https://user-images.githubusercontent.com/4077729/222097660-3d9d2ce0-415f-4665-968e-00e54b9aa473.png">

**Comment by odelcroi** [comment]
@areox-net @Caroline-lawson

**Comment by areox-net** [comment]
@odelcroi 
Apart the "Sauvegarder voc Clé Tchap" that needs to be fixed, something else gets my attention in the first screenshot.
I didn't notice the button "Connecter cette session à la sauvegarde des clés" before. 
In which scenario is this button displayed? The SS is active but the session is not verified? Why the session is not "connected"?? "Connecter une session" is yet another concept!

**Comment by odelcroi** [comment]
- [x] both buttons "Configurer" and "Activer la sauvegarde automatique des messages" leads to the same dialog (sauvegarder votre clé de récupération). Yet they are not named the same way
<img width="652" alt="Capture d’écran 2023-03-01 à 16 02 55" src="https://user-images.githubusercontent.com/4077729/222179032-d1f3e5d4-3d28-4f71-8cea-fcbe730c79a6.png">

**Comment by odelcroi** [comment]
> @odelcroi Apart the "Sauvegarder voc Clé Tchap" that needs to be fixed, something else gets my attention in the first screenshot. I didn't notice the button "Connecter cette session à la sauvegarde des clés" before. In which scenario is this button displayed? The SS is active but the session is not verified? Why the session is not "connected"?? "Connecter une session" is yet another concept!

- [x] Yes indeed, if xsss is configured from another session, and you haven't verified this one, you get this button "Connecter cette session à la sauvegarde des clés"

## Session A connected to the secure storage

![Capture d’écran 2023-03-01 à 16 08 33](https://user-images.githubusercontent.com/4077729/222180506-d4681fee-a4ef-4067-88e7-d2fc7d2bdf26.png)

## Session B *NOT* connected to the secure storage

![Capture d’écran 2023-03-01 à 16 08 48](https://user-images.githubusercontent.com/4077729/222180619-44ffd60a-6d9c-48ab-ae5d-267eb1e659f7.png)

**Comment by areox-net** [comment]
@odelcroi Then, it should simply be "Vérifier cette session" as it's in the Signature Croisée section.

**Comment by areox-net** [comment]
> * [x]  both buttons "Configurer" and "Activer la sauvegarde automatique des messages" leads to the same dialog (sauvegarder votre clé de récupération). Yet they are not named the same way
> 
> <img alt="Capture d’écran 2023-03-01 à 16 02 55" width="652" src="https://user-images.githubusercontent.com/4077729/222179032-d1f3e5d4-3d28-4f71-8cea-fcbe730c79a6.png">

Here I don't understand at all why in the Signature Croisée section it says 'Activer la Sauvegarde..". Both button should simply be "Activer"

**Comment by areox-net** [comment]
Le texte au dessous de "Sauvegarde automatique des messages" devrait etre un générique:

Cette fonction vous permet de sauvegarder automatiquement vos messages et de les récupérer à tout moment à l’aide d’un Code de récupération.
