### ISSUE TITLE
Wrong label when searching a person in Tchap directory

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#448]
When searching a person through the directory, Label says "Message Direct" whereas "Personne" seems to be more appropriate

![recherche pesronne](https://user-images.githubusercontent.com/4077729/222419607-9d268eb9-ea17-43b2-ab6e-dbb5d1c6c0fe.jpg)

<img width="465" alt="Capture d’écran 2023-03-02 à 16 53 15" src="https://user-images.githubusercontent.com/4077729/222480866-9ee9d1b1-1b3a-4af6-a8bc-8aca907e0b1b.png">

**Comment by odelcroi** [comment]
This issue could be processed at the same time : https://github.com/tchapgouv/tchap-web-v4/issues/440

**Comment by odelcroi** [comment]
All those files should be checked : 
![Capture d’écran 2023-03-02 à 17 04 26](https://user-images.githubusercontent.com/4077729/222483591-96de5927-cbc0-4f73-b3d4-ba35d39136ca.png)

**Comment by jdauphant** [comment]
@odelcroi @areox-net do we discuss with Element on that ?

**Comment by areox-net** [comment]
"Personnes" or "Members" would be better. However, at the end of the day I think that "Message direct" is not so shocking, since the final result of this search will be a direct message. 
On the other hand, the tag "Salon public" is not correct. It should be "Forums".

@jdauphant If we modify it, I think it should be through Element.

**Comment by odelcroi** [comment]
@jdauphant Direct Messages is our modification, Element shows "Personne" instead

**Comment by aulamber** [comment]
> @jdauphant Direct Messages is our modification, Element shows "Personne" instead

Et du coup, on rechange a Personne ?

**Comment by areox-net** [comment]
> @jdauphant Direct Messages is our modification, Element shows "Personne" instead

Indeed, to be clear if we ask a modification to Element, it would be to use "Direct Messages" for 1-to-1 conversations, but keeping "People" in this search tag.

**Comment by jdauphant** [comment]
C'est quoi l'original en anglais ?
Dans Element la traduction française est communautaire, on peut proposer mieux directement dans l'outil de traduction

**Comment by odelcroi** [comment]
Ce n'est pas un problème de traduction. Element utilise "Personne" pour de nombreux usages notamment les DM et d'autres labels. Comme nous avons décidé de changer le nommage des DM, cela a introduit des effets de bords non désirable, c'est la raison de ce ticket. A mon avis, on doit garder notre approche et corriger uniquement les effets de bords. 

Optionnel : nous pouvons pousser comme modification dans Element d'identifier séparément les labels pour les DM et les autres usages.
