### ISSUE TITLE
Emphasize that recovery code is unique

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#464]
Retour d'UX sur l'écran actuel 

![image](https://user-images.githubusercontent.com/4077729/225643774-e50b54d5-3e0f-4746-8995-4f19bc879291.png)

Actuellement : 
Pas clair que c’est un code unique
Pas clair que c’est la dernière fois qu’il le voit
Pas clair si les colonnes sont importantes
Pas clair si les majuscules sont importants
Pas clair si les espaces sont importants

**Comment by areox-net** [comment]
Voici une nouvelle proposition qui prend en consideration surtout les points:
- Pas clair que c’est la dernière fois qu’il le voit
- Pas clair si les colonnes sont importantes (en gérant mieux les espacements)


___

Ce code vous permettra de toujours récupérer vos messages.  

**Attention: c’est la seule fois que ce code est affiché !** 
Pensez à le conserver dans un endroit sûr, par exemple dans votre gestionnaire de mot de passe, sur un papier dans une armoire ou un tiroir fermé à clé.

![Screenshot 2023-03-16 at 16 28 08](https://user-images.githubusercontent.com/1255251/225666404-f4398069-2b0b-49dd-bb66-5c2609d96a82.png)

**Comment by aulamber** [comment]
Fix https://github.com/tchapgouv/tchap-web-v4/pull/473
