### ISSUE TITLE
Confusing clé de session

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#465]
Dans les parametres de sécurité on a.

Nous avons expérimenté que certains utilisateurs peuvent penser que c'est le code de récupération

<img width="695" alt="Capture d’écran 2023-03-16 à 09 09 15" src="https://user-images.githubusercontent.com/4077729/225661229-267b0480-89a5-49cd-8bc0-041c31a5f416.png">

A changer en :

Title : 
"Cles tchap"

Description :
"Ces cles ne concernent que la session en cours.
Attention ceci n'est pas votre clé de recuperation pour votre sauvegarde automatique."

Ajouter une session Afficher avec fleche (comme Avancé)
et dessous : "identifiant de session" et "cle tchap" (au lieu de "cle de session")

**Comment by odelcroi** [comment]
Clé de session, pourrait s'appeler "identifiant de session" pour éviter la confusion avec les autres clefs

**Comment by odelcroi** [comment]
same pour 👍 
- [ ] ios
- [ ] android

**Comment by areox-net** [comment]
Je propose de le cacher une fois le XSSS activé. Ca rend la page complexe et on risque de confondre les clés avec le code de récupération.

@jdauphant Que en penses tu ?

**Comment by jdauphant** [comment]
Si on n'a aucune utilité, on peut la cacher partout et supprimer la procédure de validation manuellement avec cette clé.

**Comment by jdauphant** [comment]
Il faut transmettre l'info à Element
