### ISSUE TITLE
sécurité settings : "recherche de message" n'est pas à la bonne place

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#466]
Ne devrait'on pas le supprimer directement? 

![Capture d’écran 2023-03-16 à 16 17 38](https://user-images.githubusercontent.com/4077729/225663432-fd949ace-a08f-49c8-af55-3aa718baeeb4.png)

**Comment by jdauphant** [comment]
+1 pour la suppression
