### ISSUE TITLE
UX issues : J'ai perdu mon code de récupération, je veux en générer un nouveau 

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#467]
(réinitialise mon code de récupération)

Steps : 
- Aller dans les paramètres de sécurité sur un appareil dont la sauvegarde est activée

![Capture d’écran 2023-03-16 à 14 29 19](https://user-images.githubusercontent.com/4077729/225667342-d8583df3-900e-4636-934d-77f59ef74492.png)

L'écran suivant est directement le nouveau code 

![Capture d’écran 2023-03-16 à 15 10 48](https://user-images.githubusercontent.com/4077729/225708758-e7ebbb12-5200-444b-bd95-dcda17999f85.png)

Probleme : 
- [ ] "Réinitialiser" n'est pas parlant
- [ ] certains users cliquent sur "réinitialiser" de la signature croisée au lieu de "réinitialiser" de sauvegarde automatique des messages
- [ ] que se passe-t-il si je ferme l'écran du nouveau code?

**Comment by odelcroi** [comment]
Réinitialiser should be named : "Générer un nouveau code unique"

UX improvment : https://github.com/tchapgouv/tchap-web-v4/issues/436

**Comment by odelcroi** [comment]
@areox-net @Caroline-lawson What do you think?

**Comment by areox-net** [comment]
@odelcroi I think it should be shorter: "Générer un nouveau code"

Also: do we really need "Supprimer la sauvegarde" ??

**Comment by odelcroi** [comment]
@areox-net I don't see a usecase where "Supprimer la sauvegarde" is necessary... we could hide it

**Comment by areox-net** [comment]
@odelcroi I would hide it as well. 
I can't see a use case where a user would want to stop using SS or delete their saved messages. 
Even if your Recovery Code as been stolen, you can always generate a new one for security reasons. 

@jdauphant Are we missing something or do you agree on hiding this button as well?

**Comment by Caroline-lawson** [comment]
Agree to hide "Supprimer la sauvegarde" because not sure what it actually does (does it delete my messages or the process of automatically saving my messages?).

"Réinitialiser" is scary: users tend to think it will delete all their messages. Therefore I agree to change it to "Générer un nouveau code" or even "Code perdu"  (a bit like "mot de passe oublié")?
