### ISSUE TITLE
UX issues : je me re-connecte à ma session web sans avoir de sauvegarde

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#470]
v4.1.7

steps : 
- sur un compte uniquement web
- se déconnecter sans avoir configuré de sauvegarde automatique
- se connecter

1)
![image](https://user-images.githubusercontent.com/4077729/225738016-6b315dee-bed5-4504-968d-e8df15d6f6a7.png)

2)
![image](https://user-images.githubusercontent.com/4077729/225738096-c9496afb-3f6e-4d6f-bccf-074dee676f89.png)

3)
![Capture d’écran 2023-03-16 à 20 55 45](https://user-images.githubusercontent.com/4077729/225738555-991919c7-8903-46e7-a488-78d959fb99fa.png)

- [ ] nous ne voulons pas inciter la sauvegarde auto pour le moment, il faudrait étudier de changer l'écran 2 
- [ ] les users ont peut etre sauvegardé leur clefs Tchap

**Comment by odelcroi** [comment]
@areox-net @Caroline-lawson 
I'm wondering if this flow is a blocker for the beta. I will affect people that are using the beta but have not configure xsss

**Comment by Caroline-lawson** [comment]
If it affects just our beta-testers, couldn't we tell them to configure xsss so this case won't happen?

**Comment by areox-net** [comment]
@odelcroi Si on ne veut pas pousser à la sauvegarde, il ne faudrait pas afficher cet écran du tout et revenir à l'ancien scenario:
- on se connecte 
- on arrive dans l'interface 
- les messages sont verrouillés.
