### ISSUE TITLE
reset password : some buttons are not working

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#477]
4.1.7
Those buttons have not effect
<img width="466" alt="Capture d’écran 2023-03-20 à 15 44 56" src="https://user-images.githubusercontent.com/4077729/226376231-fefbe174-1061-40f9-b183-23ab67ae6185.png">

**Comment by NicolasBuquet** [comment]
In fact, it is the DIV `<div role="button" tabindex="0" class="mx_AccessibleButton mx_AuthBody_resend-button mx_AccessibleButton_hasKind mx_AccessibleButton_kind_link">` which has its property `display: none`.

When `display` is not to `none`, the resend button is displayed : 

![image](https://user-images.githubusercontent.com/18608158/226411618-f3734905-bcf8-4dae-8678-ef0201f9815f.png)

**Comment by odelcroi** [comment]
Not blocking but a annoying regression and quick to fix then P1
