### ISSUE TITLE
[Sprint Goal] User testing demarches-simplifiees

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-web-v4#48]
User-tester et peaufiner le formulaire Démarches Simplifiées pour les nouvelles conventions

**Comment by JDixmier** [comment]
Je propose de centraliser les retour utilisateurs ici : 
https://www.notion.so/User-Tests-du-Formulaire-d-ouverture-91f15f3ec2c146d5ac831cca90daa5b5
