### ISSUE TITLE
web_only users: when xsss is not active, verify button lead to xsss nudge

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#483]
- [ ] warning toast leads to a dead end
- [ ] verify button from the device list leads a screen pointing to device list

Steps to reproduce
- get an account with only one device : web
- no xsss configured
- Disconnect from web
- Reconnect to web

1) login

2) soft nudge about xsss
![Capture d’écran 2023-03-22 à 11 45 00](https://user-images.githubusercontent.com/4077729/226880601-ac3d3776-8ddc-40c3-bbdb-561a8aa60171.png)

3) warning toast
![Capture d’écran 2023-03-22 à 11 50 45](https://user-images.githubusercontent.com/4077729/226881551-a30edf37-0d3e-4e31-99ad-1d3b5e6da767.png)

4.1) if click on "Verify"
![Capture d’écran 2023-03-22 à 11 52 31](https://user-images.githubusercontent.com/4077729/226881935-f9208cab-0094-463f-865a-e4d3b083d00a.png)

4) close toast, go to device list
<img width="702" alt="Capture d’écran 2023-03-21 à 14 53 56" src="https://user-images.githubusercontent.com/4077729/226628314-6af2087e-1aec-4a0d-b7e3-f2b6c763e0c0.png">

5) a dialog opens, click on "continue" button
<img width="774" alt="Capture d’écran 2023-03-21 à 14 55 53" src="https://user-images.githubusercontent.com/4077729/226628611-e1f12ba3-14bf-4917-aab6-51cc7c219c2b.png">

**Comment by odelcroi** [comment]
@areox-net this flow is a bit problematic, what do you think

**Comment by areox-net** [comment]
@odelcroi Indeed, we should be able to differentiate the soft nudge message from the other Verification messages.
To be sure, this is the case when the only way to verify the session is to reset XSSS? 
If so, the verification button should redirect to XSSS. I don't see other options.

**Comment by odelcroi** [comment]
> @odelcroi Indeed, we should be able to differentiate the soft nudge message from the other Verification messages. To be sure, this is the case when the only way to verify the session is to reset XSSS? If so, the verification button should redirect to XSSS. I don't see other options.

Sure, @jdauphant what you think?

**Comment by jdauphant** [comment]
I don't get all the implication. 
What's have we changed ?
Can we skip 4 ?
