### ISSUE TITLE
remove reinit button in error message

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#487]
steps to reproduce : 
- connect to an account without xsss
- in a room with locked messages this window should show :

FLOW : 
1) login 
2) warning message
![Capture d’écran 2023-03-22 à 10 12 27](https://user-images.githubusercontent.com/4077729/226855301-0a659518-b123-4fd5-9e89-50a8a68be4e5.png)

3) error message in room 
![Uploading Capture d’écran 2023-03-22 à 10.16.56.png…]()

todo : 
- [ ] adapt UX in step 3
- [ ] idea : instead open settings

**Comment by odelcroi** [comment]
I think the error message should be linked with the first warning screen
titre : "Activez la nouvelle fonctionnalité de Tchap : la sauvegarde automatique des messages"
body : "Pour éviter la perte de vos messages, vous pouvez activer la sauvegarde automatique des messages dans les paramtres de sécurité"
bouton : <ouvre les parametres de sécurité>

![Capture d’écran 2023-03-22 à 10 29 14](https://user-images.githubusercontent.com/4077729/226859664-af30c61e-68c8-4cdc-9ae3-6faa80cb9eaf.png)



@areox-net any suggestion?

**Comment by areox-net** [comment]
I think the title could be shorter:
title : "Activez la sauvegarde automatique des messages"
body : "Pour éviter la perte de vos messages, vous pouvez désormais activer cette nouvelle fonctionnalité Tchap dans les paramètres de sécurité"

About the action button, if we direct the user to settings why can't we directly activate XSSS from here ? At this point we are already pushing the user to activate it anyway.
