### ISSUE TITLE
Rework securirty privacy settings

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#497]
### Your use case

Open security settings : 
![Capture d’écran 2023-03-27 à 16 01 11](https://user-images.githubusercontent.com/4077729/227962402-63b6f71e-0d94-405b-9e00-c2564e82ced1.png)

Would that be better to put first the Secure Backup section and then the device list

**Comment by jdauphant** [comment]
@odelcroi what user problem do you want to solve ? can you explain in the ticket ?
Also, there is a new session manager that put "session" in other part of the settings

**Comment by odelcroi** [comment]
Some feedbacks have been gathered to improve security configuration and understanding
- "Sauvegarde automatique des messages“  at the top in the settings
- Some rewording
