### ISSUE TITLE
Reset Password via Settings

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#503]
### Steps to reproduce

Se connecter avec un compte (agent ou externe) sur au moins 2 appareils (dont l’un correspond à la cible si la cible est un client)
1- Aller dans les paramètres effectuer un changement de mot de passe (en utilisant la cible si la cible est un client)

#### What did you expect?
Une alerte est affichée avant de valider le changement de mot de passe pour indiquer que le compte sera déconnecté sur les autres appareils
Et qu’il est préférable d’exporter ses clés. 
Poursuivre le changement de mdp.

Le compte est désactivé sur l’autre appareil. L’utilisateur est redirigé sur l’écran de connexion.
#### What happened instead?
Pas de fenêtre d’alerte.
Une fenêtre “Succès…”
Pas de déconnexion automatique sur le client Android.
Pas de déconnexion automatique sur le client Web.

NOTE : We have to check what element is doing there to know if we do the same

### Will you send logs?

No

**Comment by odelcroi** [comment]
Is it a bug or an acceptable behaviour? I would say it is acceptable

**Comment by odelcroi** [comment]
- [x] update functionnal tests
