### ISSUE TITLE
Quand les services ne sont pas accessibles, j'aimerais qu'on m'indique quoi faire

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#507]
Epic ticket : 
https://github.com/tchapgouv/tchap-support/issues/83

When the service is down or very slow we have this : 

![20230329_132235](https://user-images.githubusercontent.com/4077729/228585771-c8e43f9d-87e3-44bb-a4a4-05e5f9c66662.jpg)

![Sans titre](https://user-images.githubusercontent.com/4077729/228586013-da54e1bb-a8df-4882-8d9c-b7a24d34ec9a.jpg)

<img width="739" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/bb4a6f97-06fb-4371-aafe-d1a355588970">

**Comment by odelcroi** [comment]
@areox-net I think Tchap web should only say : Le serveur semble saturé ou inaccessible, veuillez réessayer plus tard
@Nivann should be talk about twitter announcements?

**Comment by Caroline-lawson** [comment]
How often does this occur? Do we need to say that we are working on it?

Suggestion: "Tchap n'est pas accessible pour le moment. Merci de réessayer plus tard."

**Comment by areox-net** [comment]
I agree with @Caroline-lawson suggestion.
If we need to say more, we could create an FAQ article about this error.

**Comment by NicolasBuquet** [comment]
Don't make assumption about the server :
"Your device can't connect to the server. Try again later."

**Comment by Nivann** [comment]
@odelcroi we should not mention Twitter as we would only use it to inform the users if all of Tchap is totally unavailable (wich was not the case recently). 

Beside, i dont think that we should rely on a private owned, non EU social media, to comunicate in case of a crisis

**Comment by odelcroi** [comment]
<img width="626" alt="Capture d’écran 2023-06-07 à 09 51 44" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/590a6c7b-02a5-4a35-bb9b-42e25d54bbd1">

**Comment by areox-net** [comment]
> How often does this occur? Do we need to say that we are working on it?
> 
> Suggestion: "Tchap n'est pas accessible pour le moment. Merci de réessayer plus tard."

@odelcroi Je pense qu'il faut changer le message avec cette proposition de Caroline. 
La seule question qui reste à voir est si il faut completer cela par une FAQ "En cas de problème..."

**Comment by odelcroi** [comment]
Proposition : 
- [ ]  créer une FAQ avec l'état des serveurs (voir ci-dessous), cette page peut etre mise à jour à la main depuis crisp
- [ ] créer une redirection www.tchap.gouv.fr/etat-des-serveurs vers cette page FAQ
- [ ] inclure ce lien dans les erreurs au login
- [ ] inclure ce lien dans les erreurs quand on perd la connection serveur

Exemple : 
- Instance intérieur : RAS
- Instance agriculture : RAS
- Instance xxx : RAS
- Instance yyy : RAS 

@areox-net @mcalinghee @Delphgateau

**Comment by areox-net** [comment]
@odelcroi Cet article de FAQ serait mise à jour à la main ou avec un bot ? 
Elle a pas besoin d'etre une page de FAQ en fait, mais simplement une page web avec n'entête Tchap comme sur https://tchap.beta.gouv.fr

**Comment by odelcroi** [comment]
Ça serait trop dur de la mettre à jour de manière automatique. On peut la
mettre à jour à la main lors d'incident.
Je propose de la mettre dans Crisp car c'est simple à mettre a jour pour
tout le monde

**Comment by areox-net** [comment]
@odelcroi Oui, si c'est à faire à la main, mieux vaut Crisp.

**Comment by odelcroi** [comment]
On peut le faire sur Notion égalemen, à l'image de cette page qui est publique : https://mercurial-timer-ec4.notion.site/Feuille-de-route-Tchap-2e-semestre-2023-e52c9f69edf14f5faac1a9da349a46fe

**Comment by jdauphant** [comment]
Je proposais de changer status.beta.tchap.gouv.fr par une page de status avec des messages d'alerte, il y a pleins de SaaS dispo, des logiciels open-source propre qui existe.
Ça peut être un quickwin à mettre en place.
On reproduit les mêmes indicateurs qu'updown et si on choisit bien, on pourra sûrement les améliorer ensuite.

**Comment by odelcroi** [comment]
Le besoin est que une personne non technique soit autonome pour mettre un message ou un avis 
Est ce qu'on peut mettre un texte en en tete de cette page ? https://status.tchap.beta.gouv.fr/ 
@pseudonyme21 @mcalinghee ?

**Comment by odelcroi** [comment]
Crisp propose de personnaliser [une page de status](https://app.crisp.chat/settings/status/). Cette solution est basée sur le package [open source Vigil](https://github.com/valeriansaliou/vigil). Cela pourrait être une bonne option, je vais regarder. @jdauphant @mcalinghee @Delphgateau

**Comment by odelcroi** [comment]
Ca a l'air de faire le job : https://tchap.crisp.watch/fr/
- seul bémol, la présence du chat alors que nous voulons prioriser l'email pour nous contacter

![Capture d’écran 2023-07-19 à 10 35 50](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/3a06ca64-3c0d-4dca-9778-2ab874b3f80c)

**Comment by odelcroi** [comment]
>Bonjour Olivier !
En effet ce message-ci "contactez le support" n'est pas directement modifiable,
en revanche, nous avons l'option d'utiliser du custom code sur la page de status, et c'est quelque chose qui vous permettrait de faire cela sans trop de souci.
Le custom code accepte le javascript, qui vous permettrait d'éditer directement les textes ou actions associées à la partie que vous avez mentionné

**Comment by areox-net** [comment]
Très bien. Pour l'instant j'ai caché le bouton chat du footer en CSS.

**Comment by odelcroi** [comment]
> Vous pouvez par exemple utiliser quelque chose comme ceci pour modifier le label du lien et envoyer un email au lieu d'ouvrir la chatbox:
```
<script>
 window.addEventListener("load", function() {
    document.querySelector('.css-home-status-text-label-line a').innerHTML = "contactez nous";
    document.querySelector('.css-home-status-text-label-line a').href = "mailto:contact@domain.com";
    document.querySelector('.css-home-status-text-label-line a').target = "";
  })
</script>
```

**Comment by jdauphant** [comment]
> Crisp propose de personnaliser [une page de status](https://app.crisp.chat/settings/status/). Cette solution est basée sur le package [open source Vigil](https://github.com/valeriansaliou/vigil). Cela pourrait être une bonne option, je vais regarder. @jdauphant @mcalinghee @Delphgateau 
> 

Pour info, Vigil est développé par le CTO de Crisp !
C'est très bien d'avoir l'app hébergé par Crisp.

**Comment by mcalinghee** [comment]
> Le besoin est que une personne non technique soit autonome pour mettre un message ou un avis Est ce qu'on peut mettre un texte en en tete de cette page ? https://status.tchap.beta.gouv.fr/ @pseudonyme21 @mcalinghee ?

Desole de repondre apres coup, je n'ai pas forcement les elements a cette question. 
@jdauphant : ou se trouve l'hebergement de cette page ? et a t-on un repos pour ceci? a-t-il un lien avec updown? 
EDIT : j'ai eu la reponse a mes questions => c'est sur updown



> Crisp propose de personnaliser [une page de status](https://app.crisp.chat/settings/status/). Cette solution est basée sur le package [open source Vigil](https://github.com/valeriansaliou/vigil). Cela pourrait être une bonne option, je vais regarder. @jdauphant @mcalinghee @Delphgateau

C'est une idee top de centraliser sur Crisp et cela a l'air d'etre une tres bonne piste surtout si on peut customiser!

**Comment by mcalinghee** [comment]
Une autre option : on peut aussi se rapprocher de la communauté Beta pour savoir si il n'existerait pas d'autres solutions? peut-etre demander a Chaïb ? 
Cependant la solution Crisp a l'air d'etre pas trop mal : @odelcroi  la mise en place est-elle facile?

**Comment by mcalinghee** [comment]
Autre fonctionnalite de la page de status heberge sur Crisp : il semblerait que l'on ait aussi un message dans Crisp (partie support) si on a un soucis
![image](https://github.com/tchapgouv/tchap-web-v4/assets/3725676/48ca8086-0593-4ca2-bf57-8b0848d835f6)

**Comment by odelcroi** [comment]
> Autre fonctionnalite de la page de status heberge sur Crisp : il semblerait que l'on ait aussi un message dans Crisp (partie support) si on a un soucis ![image](https://user-images.githubusercontent.com/3725676/254815597-48ca8086-0593-4ca2-bf57-8b0848d835f6.png)

Oui, je testais l'alerte par email

La page est éditable ici : https://app.crisp.chat/settings/status/

**Comment by odelcroi** [comment]
url : https://status.tchap.numerique.gouv.fr/
