### ISSUE TITLE
En tant qu'administrateur d'un espace, je souhaite rendre accessible un salon aux membres de mon espace

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#511]
Avant :
![image](https://user-images.githubusercontent.com/1238254/228834777-6c02792a-f385-4f0f-9bed-a903fadd5fa7.png)

Après :
![image](https://user-images.githubusercontent.com/1238254/228834496-6dfeafec-3904-40ad-a780-862b71506756.png)

**Comment by odelcroi** [comment]
What does Mise-à-jour nécessaire means? Should it be explained to users?

**Comment by jdauphant** [comment]
It's explained when you clic on it.

Also if we push room level 9 in prod, we will have not the necessity of that.

This setting is only visible to admin of space.

**Comment by jdauphant** [comment]
The upgrade will remove access to external

**Comment by odelcroi** [comment]
> The upgrade will remove access to external

Do you mean that upgrading rooms to level 9 will remove access to external users? If that so, do you have a reference link?

**Comment by jdauphant** [comment]
> > The upgrade will remove access to external
> 
> Do you mean that upgrading rooms to level 9 will remove access to external users? If that so, do you have a reference link?

Yes : 
- https://github.com/tchapgouv/tchap-infra/issues/1775
