### ISSUE TITLE
When downloading a large file, nothing shows it is actually doing it

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#516]
### Steps to reproduce

1. Enter a private room
2. Send a large file (less than 10Mo)
3. Download it after

If the connection is slow, it can take one minute. Nothing shows that the file is downloading

#### What did you expect?
A loader or anything kind of feedback

#### What happened instead?
After clikcing on the file, nothing happens
But the file is getting downloaded

### URL for webapp

tchap.gouv.fr

### Application version

4.2.1

### Will you send logs?

No

**Comment by aulamber** [comment]
I verified with a slow connection, there is a loader, it works.

**Comment by odelcroi** [comment]
closed as not able to reproduce
