### ISSUE TITLE
Remove "Send" button on restore with the recovery key

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#520]
![image](https://user-images.githubusercontent.com/1238254/229287375-7e33da72-20c9-414b-8576-d664a2324bef.png)
"Sent" or "Envoyer" button is confusing with the call to action "continuer" : we can remove it

**Comment by jdauphant** [comment]
Also "Tout réinitialiser" : the user don't know it's only the messages that will be reintialised. We can put "Réinitialiser la sauvegarde de mes messages" instead

**Comment by odelcroi** [comment]
This panel escaped from us, we'll tryed to find it, any hints on how to reproduce?

**Comment by odelcroi** [comment]
I can not reproduce on : 
Version de Tchap : 4.2.1-1.11.25
Version de Olm : 3.2.12

**Comment by jdauphant** [comment]
Sur tchap.gouv.fr, je viens de faire
- "se déconnecter" on the loading page
- login page
![image](https://user-images.githubusercontent.com/1238254/230681706-d062509b-b5a6-49f2-8614-9ac83747285e.png)
![image](https://user-images.githubusercontent.com/1238254/230681729-a6f824f0-1d2e-4032-afb9-f86e84dab6d8.png)
![image](https://user-images.githubusercontent.com/1238254/230681776-1643c7b3-20bf-447a-b02b-1d250a7e26bf.png)
et je ne repproduits pas :thinking:

**Comment by odelcroi** [comment]
Closing for now, feel free to reopen if it happens again
