### ISSUE TITLE
Create Room à la Tchap

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#53]
#### What would you like to do?
As a logged user, I would like to create a new room within Tchap environment

#### Why would you like to do it?
Tchap users can only create 3 types of rooms : 
- private room : encrypted, only invite, federated
- private room with external users : same than private room but "external users" can be invited
- public room (called forum) : not encrypted, users can join, share the room with the tchap federation is optional

#### How would you like to achieve it?
Replace the create room dialog component within the project tchap-web-v4. 
Note : the concept of external users is handle by a custom event already installed in the tchap hs.

### Have you considered any alternatives?
No

### Additional context
linked to ticket #46 

_more details on federate:
les salons sont tjs federated=true (c'est a dire les users de toutes les instances peuvent les rejoindre)
les forums laissent federated au choix de l'utilisateur : on peut limiter à l'instance de l'utilisateur, ou non.
exception pour les utilisateurs de l'instance agent qui n'ont que des forums federated (??? a verifier) Edit : parce que les users de "agent" ne comprenaient pas l'option, à cause du nom "agent" qui n'est pas clair, et apres ils contactaient le support parce que ca ne faisait pas ce qu'ils pensaient._

_more details on existing implementation
_Join_rule : salon=invite, forum=public.
Access_rule : pour salon sans externe et forum : restricted. Pour salon avec externes : unrestricted
Encryption : true pour salon, false pour forum
Preset : public_chat pour forum (ca met guest_access=true, mais on peut le override)
History_visibility : shared pour forum, joined ou invited (?) pour salon
Guest_access : disable partout_

**Comment by estellecomment** [comment]
Done
