### ISSUE TITLE
Simplify access rights to private room for admin

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#532]
Cf. issue https://github.com/tchapgouv/tchap-web-v4/issues/511

### Steps to reproduce

- go to a private room where you are an admin.
- click on the info icon at the top right corner
- click on Paramètres du salon > Sécurité et vie privée

**1. I find the button "Mise à jour nécessaire" unclear et unnecessary. Its purpose is to ask the admin user of a room to modify the room rights in order to allow anyone in a space inside.**

- unclear because the label is not self explanatory.
- unnecessary because when the user clicks on the radio option "Membres de l’espace", it also opens the modal that would have been opened by clicking on the "Mise à jour nécessaire" button, which is located next to the radio option.

<img width="872" alt="Capture d’écran 2023-04-12 à 15 59 20" src="https://user-images.githubusercontent.com/6305268/231483748-08a4925c-6fa9-4123-869e-54bdbd722339.png">

My suggestion is to get rid of the "Mise à jour nécessaire" button.

**2. I also suggest, in the subsequent modal, to get rid of the sentence "Vous allez mettre à niveau ce salon de 1 vers 9" because it doesn't mean anything to the end user. It is just confusing.**

<img width="650" alt="Capture d’écran 2023-04-12 à 14 55 11" src="https://user-images.githubusercontent.com/6305268/231483663-141ef184-41cb-4bc8-b386-e7679c79741c.png">

**Comment by odelcroi** [comment]
@areox-net @Caroline-lawson UX feedbacks needed here

**Comment by areox-net** [comment]
On one side I agree with @aulamber about the unnecessary button; on the other side I question if we even need to make this feature available on existing private rooms. The operation is too complex and the outcome is dangerous (loosing the existing room content). I'm sure 80% of the user won't even bother reading the content of the modal and few will understand what it says. 
If we keep the button/label, I suggest that we change the text to "Avancé" to show that it's a complex feature/operation.

**Comment by odelcroi** [comment]
@areox-net le contenu du salon n'est pas perdu, il est archivé et accessible depuis le nouveau salon.
Par contre, il faut ajouter un warning : "mettre à jour le salon supprime l'accès aux externes, ils ne seront pas réinvité dans le nouveau salon. Si vous avez besoin d'un accès au externe, il faut recréer un nouveau salon", c'est un bug actuellement

**Comment by areox-net** [comment]
@odelcroi Merci, depuis mon commentaire j'ai remarqué cela à l'usage en effets.

Du coup faut-il proposer la MAJ pour les salons avec externes? j'ai peur que cela ne soit pas compris et que ça surcharge le support.
Si on a pas le choix, je mettrais le message à la fin de la modale, après le toggle "inviter automatiquement le membres..." :

_"Les membres externes ne pourront pas être réinvités. Si vous avez besoin d'un accès aux externes, il faudra créer un nouveau salon"_

**Comment by Caroline-lawson** [comment]
_"Les membres externes ne pourront pas être réinvités. Si vous avez besoin de donner accès aux externes, il faudra créer un nouveau salon"_
