### ISSUE TITLE
En tant que membre, je ne veux pas voir les changements d'avatar par défaut

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#541]
Solution, "Afficher le changement d'avatar" par défaut à faux.
![image](https://user-images.githubusercontent.com/1238254/232030854-7ea38b7c-a1e9-4b76-a444-47541784dc95.png)

**Comment by NicolasBuquet** [comment]
Created same ticket on iOS (https://github.com/tchapgouv/tchap-ios/issues/806) and Android https://github.com/tchapgouv/tchap-android/issues/904.

**Comment by MarcWadai** [comment]
PR https://github.com/tchapgouv/tchap-web-v4/pull/1103
