### ISSUE TITLE
Change recovery code display from columns to a line

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#547]
### Steps to reproduce

Current display:

<img width="689" alt="Capture d’écran 2023-04-17 à 15 45 27" src="https://user-images.githubusercontent.com/6305268/232502837-4405bed3-b120-415d-a518-a17220b45c64.png">

Cf. https://www.notion.so/mercurial-timer-ec4/R-sultats-Sauvegarde-Automatique-47755e5334ed45cfb51a3a21928e1f0e

**Comment by areox-net** [comment]
I think we should try to display the code in one line, by reducing the space between words.

![Screenshot 2023-04-17 at 17 58 24](https://user-images.githubusercontent.com/1255251/232543405-24b01315-2147-47c4-839f-cc7ffe8e2ac9.png)

**Comment by odelcroi** [comment]
It is important to mention that : 
- the character case is important 
- whereas "white spaces" do not matter

**Comment by MarcWadai** [comment]
Done in newer versions :)
