### ISSUE TITLE
Error message for wrong recovery code needs to be more precise and display the wrong code

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#548]
### Steps to reproduce

Cf. https://www.notion.so/mercurial-timer-ec4/R-sultats-Sauvegarde-Automatique-47755e5334ed45cfb51a3a21928e1f0e

On this screen:
<img width="735" alt="Capture d’écran 2023-04-17 à 15 49 40" src="https://user-images.githubusercontent.com/6305268/232504774-a07bdaa8-c402-4c0b-9baf-6da8bc9c59fe.png">

The initial issue is:
- ⭐ S’il y a un message d’erreur, il n’y a pas moyen de **voir le code** pour savoir où est l’erreur (ex : espace ajouté par erreur en début ou fin de code).

Suggestion:
Inside the input (in the right side of it), add an eye icon and when the user presses on it, show the previously hidden password (attention: when the user presses, not click, so that when the user stops touching the eye icon, the password is hidden once again).

**Comment by areox-net** [comment]
The code could be visible by default, if this would not be a security issue.

**Comment by jdauphant** [comment]
Mettre un bouton qui l'affiche à la demande, si on relache le bouton, ça redevient masqué

**Comment by areox-net** [comment]
> Mettre un bouton qui l'affiche à la demande, si on relache le bouton, ça redevient masqué

Si on fait ça on peut seulement controler s'il y a une faute, mais on ne peut pas la corriger.

**Comment by jdauphant** [comment]
C'est la réponse de nos correspondants sécurités.

**Comment by odelcroi** [comment]
This should be proposed to Element web directly

**Comment by odelcroi** [comment]
@jdauphant Merci de ton commentaire, tu préconises cette solution des raisons de sécurité. Est-ce que le principe que tu proposes respecte l'accessibilité sur le web? @Caroline-lawson @areox-net

**Comment by Caroline-lawson** [comment]
C'est un code qui n'a aucun sens, donc ne peut pas être appris.
Si on peut afficher le code, mais pas le corriger, c'est un casse-tête potentiel : si on ne sait pas où est l'erreur, on fait plusieurs essais, et se souvenir des différentes variantes qu'on a essayé est quasi impossible. On a besoin de voir le mot de passe et de le changer sans le retaper en entier à chaque fois.

**Comment by jdauphant** [comment]
@frculie
