### ISSUE TITLE
Find a way to indicate to users that only the latest recovery code works

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#549]
### Steps to reproduce

Cf. https://www.notion.so/mercurial-timer-ec4/R-sultats-Sauvegarde-Automatique-47755e5334ed45cfb51a3a21928e1f0e

On this screen:
<img width="735" alt="Capture d’écran 2023-04-17 à 15 49 40" src="https://user-images.githubusercontent.com/6305268/232504060-f0be6f3f-3e06-4275-a9dd-1566c0d2f5f1.png">

The initial issue is:
⭐ Les participants avec **plusieurs clés sauvegardées** (code de récupération et clés Tchap) ne savent pas quelle clé utiliser, donc ils les essaient toutes.
    - Suggestion : on pourrait dater ou numéroter les codes et préciser aux users de n’utiliser que le code de récupération le plus récent ?

### Will you send logs?

Yes

**Comment by areox-net** [comment]
@aulamber I think you have already change the error message text in your recent PR:
Le Code de Récupération n’est pas valide. Vérifier que c’est le plus récent et qu’il comprend des espaces.

I think the message is good. I'm not sure how we can solve the problem of people mistaking this code with old Tchap Keys.
