### ISSUE TITLE
Redirection to old FAQ instead of new

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-web-v4#559]
### Steps to reproduce

In the 4.3.0-1.11.28 version, when you click on Consultez la FAQ, you are redirected to the old URL (https://tchap.beta.gouv.fr/faq) instead of the new. Here:

<img width="606" alt="Capture d’écran 2023-04-20 à 14 39 23" src="https://user-images.githubusercontent.com/6305268/233368628-ea76eda3-30f1-4b6e-8691-5237716adb4a.png">

Instead it should redirect to https://aide.tchap.beta.gouv.fr/fr, like it does on the menu, here:

<img width="292" alt="Capture d’écran 2023-04-20 à 14 41 32" src="https://user-images.githubusercontent.com/6305268/233369086-adaf9243-c514-4cb4-a68b-c5463a94ca96.png">

**Comment by jdauphant** [comment]
Les issues sont en français.

Il ne doit pas y avoir de mention d'url en tchap.beta.gouv.fr dans le code source des clients normalement.
L'url de référence est https://tchap.gouv.fr/faq
