### ISSUE TITLE
En tant que membre, j'aimerai avoir la possibilité de voir mon mot de passe lors de la saisie

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#563]
Problème adressé: 
- les utilisateurs peuvent faire une erreur de saisie

Sur l'écran de login, on ne peut pas voir la valeur du mot de passe saisie : 

<img width="731" alt="Capture d’écran 2023-04-21 à 15 50 49" src="https://user-images.githubusercontent.com/4077729/233653794-16c4b484-e62d-48b8-a575-aa327bdccbfe.png">

**Comment by jdauphant** [comment]
Retour SSI : Le faire par appui, si l'utilisateur lache : le mot de passe disparait

**Comment by odelcroi** [comment]
@jdauphant Merci de ton succinct commentaire, tu préconises cette solution des raisons de sécurité. Est-ce que le principe que tu proposes est accessible? @Caroline-lawson @areox-net

**Comment by Caroline-lawson** [comment]
Non, malheureusement il n'est pas accessible de le faire par appui parce que souvent la souris suit ce que font les yeux, donc là on demande à l'user de faire 2 choses au lieu d'une. Ca ajoute de la complexité.

**Comment by Caroline-lawson** [comment]
Je m'entraîne à reformuler les user stories, donc ici ce pourrait être :

Quand je me connecte, / Quand je crée mon mot de passe,
je veux voir le mot de passe que je tape, 
pour m'assurer qu'il ne contient pas d'erreur.

**Comment by jdauphant** [comment]
@frculie

**Comment by jdauphant** [comment]
Quel est le retour du nombre d'impacts utilisateurs ? (Pour prioriser par rapport aux autres sujets)

**Comment by odelcroi** [comment]
Le nombre de personne qui "perde" ou "pense perdre" leur mot de passe est assez conséquent, les aider dans cette étape parait être une bonne idée

**Comment by Caroline-lawson** [comment]
Ca marche déjà sur Android quand on crée son compte.

Je n'ai pas de chiffres, mais améliorer l'accessibilité dans ce cas, cela concerne les personnes qui ont des difficultés de lecture, de mémoire, d'attention et de mobilité. Ces difficultés peuvent être également rencontrées quand on est distrait ou stressé.

Pour info - l'affichage en appui ne fonctionne pas pour les personnes qui utilisent seulement un clavier.
