### ISSUE TITLE
Study new Element nginx configuration recommendation 

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#574]
From README : 
<img width="1506" alt="Capture d’écran 2023-04-27 à 18 42 53" src="https://user-images.githubusercontent.com/4077729/234932029-78c2111c-259f-4332-a255-cf9eaa9aad87.png">

**Comment by odelcroi** [comment]
@seb-ol @pseudonyme21

**Comment by odelcroi** [comment]
One thing to have in mind : when downloading a file, tchap web opens an iframe. 
It conflicted with our version cookie. We had issues where the cookie was not transfered to the iframe resulting in a 404 and a failing download.
This issue : https://github.com/tchapgouv/tchap-web-v4/issues/344

**Comment by ethan-0l** [comment]
It seems we just need to be sure that connexion don't go to other domain, in this case we should add those domains to the list in addition to "self"

**Comment by odelcroi** [comment]
@seb-ol est ce que notre configuration nginx a besoin d'être mise à jour? sinon ce ticket sera fermé
