### ISSUE TITLE
Spaces - Masquer le bouton "Mise à jour nécessaire"

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#578]
#### What would you like to do?
Nous souhaitons masquer le bouton "Mise à jour nécessaire" pour eviter que tous nos utilisateurs fassent cette mise a jour
<img width="676" alt="image" src="https://user-images.githubusercontent.com/3725676/235883695-b38c364e-5f06-4163-b8bb-4fea8a1f6369.png">

#### Why would you like to do it?
Lors de l'activation des spaces, nous devons mettre a jour les rooms en version 9.
Il est possible de faire cette mise a jour via le bouton dans les parametres du salon.
Cependant, cette upgrade de room peuvent causer la perte d'utilisateur externe et augmenter le support.

**Comment by odelcroi** [comment]
si la room n'est pas en version 9, est ce qu'on devrait montrer l'option pour l'ajouter à un space?

**Comment by odelcroi** [comment]
link to https://github.com/tchapgouv/tchap-web-v4/issues/532
