### ISSUE TITLE
When having the N  bug, the error message is wrong

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#585]
"Utiliser un autre appareil..." ne résoud pas le problème.

Ce bug arrive lorsqu'un message d'un interlocuteur n'est pas déchiffré. 

Les causes sont multiples et variées. 

La seule solution est que cet interlocuteur rafraichisse son cache. 

<img width="752" alt="Capture d’écran 2023-05-05 à 09 37 24" src="https://user-images.githubusercontent.com/4077729/236401814-3748e6af-e59b-4bf3-9fb1-6782d02ee52d.png">

**Comment by odelcroi** [comment]
adding P1 to this bug, it is the most annoying bug in Tchap still

**Comment by aulamber** [comment]
@odelcroi 
My suggestion:
- write another error message instead of "Utiliser un autre appareil...", like "Pour déverrouiller vos messages, veuillez vider votre cache en suivant cette procédure : *lien vers page crisp correspondante*"
- write a crisp question & answer to describe how to clear the cache in a browser, with screenshots to illustrate.

What are your thoughts, good with you?

**Comment by odelcroi** [comment]
Un problème est que le message d'erreur actuel s'affiche dans deux cas : 
1 - Alice a tous les messages qui sont chiffrés, cela peut etre du à ce que Alice s'est déconnectée, ell doit se synchroniser avec un autre appareil pour récupérer ses messages
2 - Alice n'arrive pas lire un ou quelques messages de Bob car ils sont sont chiffrés : c'est le bug N dont il est question. Le message d'erreur cité dans ce ticket n'est pas adapté dans ce cas.

Il semble nécessaire de travailler sur la distinction entre ces deux cas. 
Si le cas 2 arrive, je suis d'accord avec le fait de renvoyer un lien vers la FAQ et expliquer ce qu'il faut faire. 

PS : C'est Bob dont les messages sont chiffrés qui doit vider son cache pour renvoyer les clefs de chiffrement à Alice. Par mesure de précaution, Alice devrait vider son cache également

**Comment by aulamber** [comment]
> Un problème est que le message d'erreur actuel s'affiche dans deux cas : 1 - Alice a tous les messages qui sont chiffrés, cela peut etre du à ce que Alice s'est déconnectée, ell doit se synchroniser avec un autre appareil pour récupérer ses messages 2 - Alice n'arrive pas lire un ou quelques messages de Bob car ils sont sont chiffrés : c'est le bug N dont il est question. Le message d'erreur cité dans ce ticket n'est pas adapté dans ce cas.
> 
> Il semble nécessaire de travailler sur la distinction entre ces deux cas. Si le cas 2 arrive, je suis d'accord avec le fait de renvoyer un lien vers la FAQ et expliquer ce qu'il faut faire.
> 
> PS : C'est Bob dont les messages sont chiffrés qui doit vider son cache pour renvoyer les clefs de chiffrement à Alice. Par mesure de précaution, Alice devrait vider son cache également

Pas si simple donc, il faut arriver à trouver comment différencier les deux cas d'erreur

**Comment by jdauphant** [comment]
@aulamber 

Dans le cas où on ne m'a pas envoyé de message :

![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/136a5bac-e481-4e6a-841f-8175dcdd3516)
J'ai l'impression que l'app distingue les cas :
"Unable to decrypt: DecryptionError: The sender's device has not sent us the keys for this message." quand quelqu'un nous a pas envoyer la clé.

j'ai vu d'autres messages quand on a les clés sur un autre appareil.

My 2 cents à vérifier.

**Comment by jdauphant** [comment]
Après une reconnexion, j'ai le même message d'erreur :(
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/867e04c7-f7f0-4aaf-8bad-c2cdaceca24e)
On ne peut pas différentier sur ce message
