### ISSUE TITLE
Vérifier le plan test minimal pour un upgrade de version element web

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#586]
Il doit prendre en compte les spécificités de tchap : 
- [ ] créer un nouveau compte agent A
- [ ] A. login avec un email
- [ ] A. inviter avec un interne par email dans un salon, vérifier qu'il peut rejoindre le salon
- [ ] A. rechercher par prenom,nom un autre interne (si possible d'une autre instance) et l'inviter dans ce meme salon, verifier qu'il peut rejoindre le salon
- [ ] A. creer une room disponible pour les externe, inviter un externe E
- [ ] E. créer un nouveau compte externe suite à l'invitation
- [ ] E. login avec email
- [ ] E. envoyer un fichier à travers l'anti-virus
- [ ] E. vérifier que les externes n'ont pas accès à la création de salon et l'annuaire
- [ ] A. exporter les participants de la room
- [ ] A. supprime son compte

**Comment by odelcroi** [comment]
Ca serait intéressant de l'implémenter dans cypress (automatisation web) pour gagner une bonne heure

**Comment by estellecomment** [comment]
- [ ] faire la procédure "Oublié mon mot de passe"

**Comment by estellecomment** [comment]
- [ ] expirer le compte, vérifier que les clients affichent un truc cohérent, et qu'on peut réactiver le compte 

(chepa si c'est indispensable pour la checklist minimale, chepa trop comment on définit ce qui est indispensable)

**Comment by estellecomment** [comment]
- [ ] envoyer un message au support (vérifier que les boutons sont tjs au bon endroit dans l'interface, et que le message est bien arrivé)

**Comment by odelcroi** [comment]
> * [ ]  expirer le compte, vérifier que les clients affichent un truc cohérent, et qu'on peut réactiver le compte
> 
> (chepa si c'est indispensable pour la checklist minimale, chepa trop comment on définit ce qui est indispensable)

Oui, quand on aura reactiver l'expiration de compte

**Comment by estellecomment** [comment]
A la création des trois types de room, verifier que l'avatar de la room a le bon icone (dans la sidebar, dans le header, dans les settings de la room) et que la mention "ouvert aux externes" est présente dans le header

(bon c'est ptet pas indispensable comme feature à tester, chepa)

**Comment by estellecomment** [comment]
Je crois que cette issue ne bouge plus. Je copie la checklist dans le wiki.
@odelcroi si tu vois rien d'autre tu peux fermer l'issue ?

**Comment by mcalinghee** [comment]
Page wiki : https://github.com/tchapgouv/tchap-web-v4/wiki/Upgrade-Element-Web#manually-testing-the-new-upgrade

J'ai cree une page Notion pour les tests minimaux : https://www.notion.so/mercurial-timer-ec4/Tests-minimaux-60606ab4404049c9b6d600b3f16c995e

Je vais me baser sur les scenarios ecrits sur web pour faire du generique sans specificite web

**Comment by odelcroi** [comment]
thank you, closing issue
