### ISSUE TITLE
J'aimerais inviter tous les membres d'un autre salon

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#593]
Why : 
Actuellement, on peut inviter en masse dans un salon à partir d'une liste de membres (en format csv, ou colonne)

Des membres de tchap aimerait créer un salon à partir des membres d'un autre salon
Des membres de tchap aimerait exporter la liste des membres d'un salon (email) pour une utilisation externe

Solution : 
- Ces deux use cases pourraient être résolu par l'ajout d'un bouton exporter les membres en csv
- exemple : 
![Capture d’écran 2023-05-10 à 14 31 48](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/27d1564b-f6e6-4966-9681-9d207b8e0bdc)

**Comment by odelcroi** [comment]
@Caroline-lawson @areox-net qu'en pensez-vous?

**Comment by areox-net** [comment]
@odelcroi C'est une solution un peu technique pour créer un nouveau salon. Mais elle a l'avantage de rendre la fonction disponible rapidement pour les membres qui la demandent.

**Comment by Caroline-lawson** [comment]
Je suis d'accord avec Angelo. On pourrait penser à une fonctionnalité plus simple dans un deuxième temps ?

**Comment by odelcroi** [comment]
export members email in csv could have RGPD issues

**Comment by Caroline-lawson** [comment]
Tchap members can use other members' emails anyway, whether we help with exporting the emails or not.

**Comment by odelcroi** [comment]
I can see your matrix Id but I can not see your email

**Comment by Caroline-lawson** [comment]
I'd say it's easy to figure out your email address based on your matrix ID...

**Comment by estellecomment** [comment]
Implemented with the matrixIds, not the emails : 
`@prenom.nom-beta.gouv.fr:agent.dinum.tchap.gouv.fr,@autreprenom.autrenom-machin.gouv.fr:agent.interieur.tchap.gouv.fr`

It's not possible to get the emails from the server (see [security considerations](https://spec.matrix.org/unstable/identity-service-api/#security-considerations) in id server spec)

@Caroline-lawson it's ALMOST easy to guess the email.
Take this case : `@aaa-bbb-ccc.gouv.fr:agent.dinum.tchap.gouv.fr` could be `aaa-bbb@ccc.gouv.fr` or `aaa@bbb-ccc.gouv.fr`. There's no way of knowing...

**Comment by Caroline-lawson** [comment]
True
