### ISSUE TITLE
Feat : Hide new DM until both user accounts are created ("U no write befor fren join")

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#63]
Description of the problem :
User1 has an account. User2 does not.
User1 invites user2 by email into a DM. DMs in Tchap are always encrypted.
User1 starts writes a message. It is encrypted, but user2's account does not exist yet.
User2 creates their account and joins the DM. They cannot decrypt the message.
-> we need to stop user1 from writing before user2 has joined, to avoid the creation of un-decryptable messages.

Screenshots :
User1 sees: 
![Screen Shot 2022-06-13 at 17 28 41](https://user-images.githubusercontent.com/911434/173390775-96c6be5f-b42b-4a6b-8686-f6668f5a448e.png)

User2 sees:
![Screen Shot 2022-06-13 at 17 28 52](https://user-images.githubusercontent.com/911434/173390596-00eb74bf-0315-4193-8e72-210e85469fa9.png)
 

Discussion on how to add this feature in Tartine.
Details : https://www.notion.so/mercurial-timer-ec4/f0b25ecf9b3145899090a3f82db9474a?v=f7f59371ae05431980c5e02ae4683552

So far, Tartine is based on element-web 1.10.10.

**Comment by estellecomment** [comment]
Rebasing Tartine to element-web 1.10.14 (PR https://github.com/tchapgouv/tchap-web-v4/pull/62) we see :

User1 sees :
![Screen Shot 2022-06-13 at 17 35 53](https://user-images.githubusercontent.com/911434/173391371-f78c9dc5-6c1d-4eae-bce8-1c2695363622.png)

User2 sees :
![Screen Shot 2022-06-13 at 17 36 08](https://user-images.githubusercontent.com/911434/173392536-08a7b996-2092-4c6f-81df-99ec1ad935ff.png)


Less weird errors, but doesn't solve the problem either.

**Comment by estellecomment** [comment]
Question : for the user experience, is it better or worse to display the DM but block the writing (with a message explaining why you can't write), instead of not displaying the DM at all ?

**Comment by estellecomment** [comment]
Interesting files to look at in element-web : [MessageComposer.tsx](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MessageComposer.tsx) (the component where the user types text) and [RoomView.tsx](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/RoomView.tsx) (the middle part of the screen, which displays all the messages for the room, and contains the MessageComposer)

Possible implementation :
 - Create a `BlockedMessageComposer` which displays an explanation message (“waiting for other user to join, you will be notified”) Work with design to show something non-irritating yet clear.
 - [In RoomView where we build the MessageComposer](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/RoomView.tsx#L2010), add a check for `isEncrypted && isDM && OtherUserHasNotJoinedYet`, and in that case display the `BlockedMessageComposer` instead of the `MessageComposer`.
   - How do we know the room is encrypted ?
     - Event : m.room.encryption
     - In RoomView we can use this.context.isRoomEncrypted(roomId)
   - How do we know the room is a DM ? 
     - Events : `m.room.encryption` and `im.vector.room.access_rules` (custom tchap event)
     - Boolean to check :`isRoomEncrypted && (roomAccessRules == DIRECT || (roomAccessRules == null && roomSummary.isDirect) )`
     - Reference implementation in Android client : https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/core/utils/RoomUtils.kt#L31
   - How do we know the other user has not joined ?
     - In RoomView : room.getJoinedMemberCount() or room.getJoinedMembers()
 - When other user joins, trigger a notification and change to normal MessageComposer.
   - How do we listen to the other user joining ?
     - RoomView has updateRoomMembers called by onRoomStateUpdate
   - How to trigger a notification ? 
     - todo
 - If necessary, tweak the display name of the room, if it looks weird before the full DM setup.
 - If necessary, add an icon next to the room name (or some other equivalent change) to show that the room exists but is not ready yet.

**Comment by giomfo** [comment]
@estellecomment FYI https://github.com/vector-im/element-meta/issues/372 is the related issue where I discuss about this topic with Element team

**Comment by estellecomment** [comment]
Proposed interface which still allows for multi-user DM (which is a feature in Element, but not allowed in Tchap). This is not final, it's a just a bunch of copy-pasted screenshots :) 

Before the two invited users have created their account : message bar disabled, replaced by an explanatory message (inspired by the interface for previewing a room, which also blocks writing messages)
![blocked_DM_1](https://user-images.githubusercontent.com/911434/174630718-a1058330-771f-4500-892c-c6d99c5c5775.png)

One user has created their account, still waiting for the 2nd user :
![blocked_DM_2](https://user-images.githubusercontent.com/911434/174630726-da459ba2-a879-4987-9660-d8fd334f7867.png)

When both users have created their account, we go back to the normal DM interface, with a message bar enabled.

**Comment by estellecomment** [comment]
@areox-net

**Comment by areox-net** [comment]
@estellecomment I think the idea is good. The message could also simply be "Waiting for .... to accept invitation".
Long text may not fit on mobile.

**Comment by estellecomment** [comment]
Note : this would cause no visible changes for users of element-web, because element-web does not create encrypted DMs in this case.

**Comment by estellecomment** [comment]
Sent a clean proposition : https://github.com/vector-im/element-meta/issues/372#issuecomment-1183301711

**Comment by jdauphant** [comment]
We can implement hiding room at low cost using this : https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/customisations/RoomList.ts

**Comment by odelcroi** [comment]
Or for the sake of the beta we can disable the invitation by email

**Comment by jdauphant** [comment]
> Or for the sake of the beta we can disable the invitation by email

Better idea, we can disable this kind of feature to reduce the time to beta

**Comment by mcalinghee** [comment]
> Sent a clean proposition : [vector-im/element-meta#372 (comment)](https://github.com/vector-im/element-meta/issues/372#issuecomment-1183301711)

@gaelledel has been notified but not available at the moment. she might come back to us next week according to @yostyle

**Comment by giomfo** [comment]
This use case should be handled by https://github.com/vector-im/element-web/issues/23133

**Comment by odelcroi** [comment]
This has been included with the upgrade of Element, well done!
