### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#641]
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1238254/c9e1651f-3923-488a-b1c3-2cc93954e108)

**Comment by jdauphant** [comment]
Correction en cours sur l'infra

**Comment by mcalinghee** [comment]
Apres test en preprod avec @jdauphant, l'erreur est presente quand on est en beta et a 20%
La release web a 100% des utilisateurs semble corriger le soucis.
Release en cours

**Comment by mcalinghee** [comment]
la release 4.3.6 a ete effectue a 100%

**Comment by odelcroi** [comment]
Quelle était la valeur du cookie tchap_split_version lors de la detection du probleme?

Si je comprend bien l'issue, on soupçonne que le problème est présent lorsque qu'une version de tchap web est déployé sur les valeurs 'version_beta' et 'version_new' ?

**Comment by odelcroi** [comment]
seems outdated. Closing
