### ISSUE TITLE
Element's CI checks are broken

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#65]
Our tchap customisation files break some of element's CI checks on PRs. See for example : https://github.com/tchapgouv/tchap-web-v4/pull/62

 - type check : our files contain sdk.getComponent instead of imports (which seem not to work in customisations), and getComponent is not found.
  - i18n check : our files add custom translations, which we implement in tchap_translations.json, to keep them cleanly separated from element's translations and avoid merge problems and lost translations. Therefore, the translation checker fails because it sees missing strings in en_EN.json (because we have placed them in tchap_translations.json instead)
  
 Would be nice to have a working translation check, at least...

**Comment by celiacheff** [comment]
Should we report this back to Element's team ?

**Comment by estellecomment** [comment]
We can. The CI works for element-web, but not with customisations added. So I guess it's a problem with customisations+CI.

**Comment by estellecomment** [comment]
We should think in terms of what checks we need, and not necessarily copy those that element has.
We can reopen if we get into that level of detail.
