### ISSUE TITLE
Bug: css has gone in About page

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#694]
### Steps to reproduce

regression due to #618 

<img width="1025" alt="Capture d’écran 2023-09-12 à 15 38 21" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/9700aabc-fbc7-4dae-921f-4b670a73980e">

### Will you send logs?

Yes

**Comment by odelcroi** [comment]
@areox-net on a perdu le css lors de l'upgrade :(

**Comment by areox-net** [comment]
@odelcroi On remarque cela que sur cette page ? Pour info, il me semble qu'il avait pas de custom sur cette page? On dirait plus un comportement different du span qui sert de titre. 

Il suffit de mettre cela pour le réparer:
```
span.mx_SettingsTab_subheading {
    display: block;
    margin-bottom: 4px;
}
```

**Comment by areox-net** [comment]
Ah, c'est vrai que les titres ne sont pas au bon format non-plus. Bizarre.
Où dans les autres page on utilise h2 et h3, ici c'est des div et span. Pas très logique.

**Comment by areox-net** [comment]
Après meilleure analyse, c'est ce code qui répare ce bug:

```
.mx_SettingsTab_heading {
    color: var(--timeline-text-color);
    font-size: 1.5rem;
    font-weight: 600;
    margin-bottom: 10px;
    margin-right: 100px;
    margin-top: 10px;
}
.mx_SettingsTab_subheading {
    color: var(--timeline-text-color);
    display: block;
    font-size: 1rem;
    font-weight: 600;
    margin-bottom: 10px;
    margin-right: 100px;
    margin-top: 12px;
}
```
