### ISSUE TITLE
La section experimental ne devrait pas être visible

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#706]
### Steps to reproduce

La section Experimental de Element devrait être cachée des utilisateurs

### Outcome

la section est visible
<img width="171" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/57096e20-88b8-44a7-a83c-f6428419bcd0">

### Browser information

version alpha interne (develop_tchap)

### URL for webapp

https://app-v4.prod.lab.tchap.incubateur.net/

### Will you send logs?

No

**Comment by estellecomment** [comment]
Ca vient du code dans UserSettingsDialog.tsx
```
        // Show the Labs tab if enabled or if there are any active betas
        if (
            SdkConfig.get("show_labs_settings") ||
            SettingsStore.getFeatureSettingNames().some((k) => SettingsStore.getBetaInfo(k))
        ) 
  ```
Nous on voudrait plutot
`        // Show the Labs tab if enabled AND if there are any active betas`
