### ISSUE TITLE
Patch "in-invite-dialog-add-text-indicating-that-we-can-invite-multiple-people" is suspiciously short

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#708]
<img width="1125" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/ba3e0dd8-af5f-4ded-b1c3-492a2f4a59dc">

Is the patch actually doing what its title says ?

**Comment by estellecomment** [comment]
(also its name is suspiciously long, maybe we could rename it :) )

**Comment by odelcroi** [comment]
The name is longer that the actual patch haha
This patch 'includes' i18n texts also 
But if it's only pcss, it could be in a custom theme

**Comment by estellecomment** [comment]
With patch : 

<img width="752" alt="Screen Shot 2023-09-22 at 4 43 59 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/e64fd93f-6f6c-46ce-b854-0eef48820c8e">


Without patch : 
<img width="759" alt="Screen Shot 2023-09-22 at 4 45 03 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/ff9bcd41-15e1-4c1a-a48a-80a5eb7860db">


The only difference I can see is that the patch introduces a visual bug : the button is not rounded any more.
I vote for deleting the patch.
