### ISSUE TITLE
Disable spaces creation

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#71]
- [x] #104
- [x] disable : le bouton de creation de space
- [x] fix bug in element-web : remove the remaining space-creation button : https://github.com/matrix-org/matrix-react-sdk/pull/9129
- [x] #107

**Comment by odelcroi** [comment]
Found a path to create a space **from an existing space**. 
**EDIT : it is a subspace that is being created, not a new space**


> go into a space
> click on menu 
![Capture d’écran 2022-07-15 à 13 46 12](https://user-images.githubusercontent.com/4077729/179217122-d2c57a1a-f8de-4cca-8d6f-a3e2989516b2.png)
> click on "Add existing room"
![Capture d’écran 2022-07-15 à 13 48 48](https://user-images.githubusercontent.com/4077729/179217451-42cce499-7e0a-4f85-a36f-f661ea48cf17.png)
> click on "Adding spaces has moved"
![Capture d’écran 2022-07-15 à 13 47 44](https://user-images.githubusercontent.com/4077729/179217280-a07197de-217e-4bdc-ab65-849838477929.png)
A button displays : "Create a new space"


- [ ] Should it be considered as an issue as ? : https://github.com/matrix-org/matrix-react-sdk/pull/9002

**Comment by odelcroi** [comment]
- [x] To be considered, Spaces are mentionned in user settings. Not tragic, but annoying as users will not understand what it is about:

1. Settings>Preferences
![Capture d’écran 2022-07-15 à 14 28 48](https://user-images.githubusercontent.com/4077729/179223355-eca13bd3-ae4e-4c2c-b5a1-7285bd5fe267.png)


2. Settings>Barre latérale
![Capture d’écran 2022-07-15 à 14 31 30](https://user-images.githubusercontent.com/4077729/179223527-b70f445f-d1dd-4891-87e7-016d431ca26c.png)

- [x] Spaces are mentionned in room settings also:

1 Room settings>privacy
![Capture d’écran 2022-07-15 à 14 32 48](https://user-images.githubusercontent.com/4077729/179223846-985914f1-8e30-45fb-b487-fc7c41b37ae8.png)

**Comment by jdauphant** [comment]
![image](https://user-images.githubusercontent.com/1238254/179393436-b3054913-24d5-4391-9276-45a14f51f512.png)
Is only visible in case, you are admin of a room in a space.

**Comment by jdauphant** [comment]
I thinks we can keep "space" mentions in settings, as if you have space, they will be visible anyway.

**Comment by estellecomment** [comment]
Filed https://github.com/tchapgouv/tchap-web-v4/issues/112 and https://github.com/tchapgouv/tchap-web-v4/issues/111 to get these minor issues sorted out later. They are not blocking for beta. Marking the checkboxes as done in this issue.

**Comment by mcalinghee** [comment]
released on production
