### ISSUE TITLE
Members of room appear greyed out because everybody is considerated offline

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#72]
~~je pense que c’est les couleurs qu’on a mal définies, on doit pouvoir fixer sans trop de pb~~ (en fait non)
![Screen Shot 2022-07-06 at 11 50 27](https://user-images.githubusercontent.com/911434/177523474-a2a5787b-dbc2-4955-ab1f-0078b9214354.png)

Lorsqu'on affiche les membres d'un salon, les utilisateurs sont affichés en gris. C'était une feature qui n'était pas dans V2. On pourrait la laisser tomber pour le moment.
Il faut aussi l'enable dans la config du client : https://github.com/tchapgouv/tchap-web-v4/blob/develop_tchap/config.sample.json#L49

**Comment by estellecomment** [comment]
Est-ce que les users sont expirés, ou désactivés ? Dans Tchap V2 ont a grisé les comptes expirés.
Edit : a priori non, c'est la presence.

**Comment by jdauphant** [comment]
En regardant le DOM, c'est une class css "offline" qui affiche le nom de la personne en grisé.

La solution je pense est de mettre la liste des homeserveurs dans https://github.com/tchapgouv/tchap-web-v4/blob/develop_tchap/config.sample.json#L49 avec "false".

Pour info, la présence a été coupé côté serveur pour des problèmes de performance.
Il y a des travaux backend en cours pour la restaurer : https://github.com/matrix-org/synapse/issues/9478

**Comment by jdauphant** [comment]
I test a fix in Dev
