### ISSUE TITLE
TBD : pourquoi certains salons ont un cadenas rouge et pas d'autres

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#726]
### Steps to reproduce

Ces salons sembent identitiques dans leurs parametres, néanmoins certains affichent le cadenas rouge du salon privé et pas d'autres

![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/c89de4bc-b5f5-489f-8bfc-9775a1bc8e31)

### Will you send logs?

Yes

**Comment by estellecomment** [comment]
ya un rapport avec les spaces ? Ils ont été créé dans le cadre d'un space ?

**Comment by estellecomment** [comment]
duplicate of https://github.com/tchapgouv/tchap-web-v4/issues/758
