### ISSUE TITLE
Welcome flow on web needs changing to be tchap-specific

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#744]
Premier ecran, pas tres adapté au milieu du travail :
<img width="875" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/5e376502-a212-45a5-9e3f-bc13246086b4">

Je clique "Passer", j'obtiens :

<img width="1645" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/6d1d2a10-c957-4e5f-b62e-c5915bc428e2">

"des amis" -> collègues

"paramétrer votre profil" -> En pratique ya que la photo qu'on puisse changer sur tchap. 

"Télécharger les applications" -> les QR codes et liens pointent vers les applis element

**Comment by estellecomment** [comment]
First one is not obviously customizeable : https://github.com/tchapgouv/tchap-web-v4/blob/313aebfeba94d018224be5690dc8643384cc1a3d/src/components/structures/MatrixChat.tsx#L1324-L1325
We could set the settings to a default value to get rid of that screen.

Second one : 
useUserOnboardingTasks, and https://github.com/tchapgouv/tchap-web-v4/blob/313aebfeba94d018224be5690dc8643384cc1a3d/src/components/views/user-onboarding/UserOnboardingPage.tsx#L42
Not customizeable either. Sigh.

**Comment by odelcroi** [comment]
Elle est belle cette page de welcome 👍 
@areox-net qu'en penses-tu?

>We could set the settings to a default value to get rid of that screen.

Je comprend qu'on peut la desactiver, c'est ca?

**Comment by areox-net** [comment]
@odelcroi @estellecomment Je pense qu'elle est très bien, notamment pour la deuxième qui évite le "empty state". Par contre il faudra la modifier pour que ça vehicule les features et le contexte Tchap.

**Comment by estellecomment** [comment]
>   We could set the settings to a default value to get rid of that screen.

@odelcroi On peut faire un patch qui simule le fait que le user ait déja cliqué une des trois options, du coup la page de choix n'est pas affichée puisque c'est déja choisi.

**Comment by estellecomment** [comment]
Du coup je propose :
Indispensable :
 - [x] mettre les bons liens et QR codes dans "Télécharger l'application" (c'est un vrai pb que les users soient envoyés vers l'appli element) (fixed in https://github.com/tchapgouv/tchap-web-v4/pull/755)
 
Nice to have :
  - [x] enlever la premiere page qui n'est pas utile pour tchap, en auto-selectionnant "collegues et equipes" (mais si elle est présente c'est pas très grave pour le moment, c'est un peu bizarre mais ca casse rien)
 - [x] changer "amis" pour mettre "collègues" dans la deuxieme page

Ca vous va ?

**Comment by areox-net** [comment]
@estellecomment Oui, je valide. 
Si c'est simple à changer, je peux aussi faire une image de Tchap avec dans les mockup téléphones.

**Comment by odelcroi** [comment]
looks good to me

**Comment by odelcroi** [comment]
- [ ] les titres devraient être à l'impératif, les boutons à l'infinitif. 
- [ ] revoir les textes, @Caroline-lawson ?

**Comment by estellecomment** [comment]
Pour info (Caroline !), on a maintenant ca :

![image](https://github.com/tchapgouv/tchap-web-v4/assets/911434/35d6aba6-7336-4b77-a5a4-6664cb106da4)

**Comment by odelcroi** [comment]
sujet lié : **https://github.com/tchapgouv/tchap-product/issues/200#issuecomment-1748322537**

**Comment by areox-net** [comment]
@odelcroi @estellecomment Y-a-t-il un build où l'on peut tester ça? C'est déjà sur lab?

**Comment by estellecomment** [comment]
Pas encore déployé officiellement mais tu peux regarder sur [app-v4.prod.tchap.incubateur.net](https://app-v4.prod.tchap.incubateur.net/)
C'est le dernier code sur develop_tchap, donc c'est dedans.

Pour voir la feature il faut te login avec un nouveau compte, donc creer un nouveau compte. (tu peux supprimer un ancien et le recréer)

**Comment by areox-net** [comment]
Merci @estellecomment Dans mon test j'arrive ps à reproduire le cas avec l'image avec les deux téléphones. Mais j'ai bien récuperée l'autre pour proposer une alternative.
Sinon je pense que plutot que dire "Parametrer votre profil" on pourrait juste dire "Ajouter une image de profil"

**Comment by areox-net** [comment]
- [x] @estellecomment on peut remplacer l'image de Element avec celle là. Je voulais faire un truc plus cool, mais à ce stade je préfère aller vite avec les visuels qu'on a déjà.

![tchap-welcome](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/dfb58d0c-a907-4393-b074-6034da0f9f87)

**Comment by estellecomment** [comment]
Autre tache possible : ajouter une etape pour ajouter la sauvegarde automatique https://github.com/tchapgouv/tchap-web-v4/issues/795

**Comment by estellecomment** [comment]
- [x] We need to change the text, we don't have voip and video calls yet : https://github.com/tchapgouv/tchap-web-v4/issues/796

**Comment by estellecomment** [comment]
Closing this ticket, the screen has been tchapified. Other tickets are open and will be dealt with separately.
