### ISSUE TITLE
Disable Location (fr: Localisation)

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#75]
Because we have no map server.
We do not use the default map server, because we need to own all data exchanges for security.

Mobile clients have disabled it as well.

**Comment by estellecomment** [comment]
We have added etalab's map server as an experiment in #81 . https://openmaptiles.geo.data.gouv.fr/

Their service gives no guarantees of performance/availability, and is not homologué. 
Etalab thinks it would make more sense if IGN provided this service.
Documentation and links to IGN services : https://guides.etalab.gouv.fr/apis-geo/3-tuiles-vecteur.html#comment-utiliser-les-tuiles-vectorielles-d-etalab

**Comment by jdauphant** [comment]
It's not possible to disable localisation, we have some edition in react-sdk to do that apparently

**Comment by estellecomment** [comment]
We can add a UIFeature for location, and check it here :
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MessageComposer.tsx#L473

**Comment by estellecomment** [comment]
What happens if we just remove the mapserver from the config ? 
Is the feature properly hidden ?

**Comment by jdauphant** [comment]
We got an exception if map_style_url is undefined : https://github.com/matrix-org/matrix-react-sdk/blob/1397652f526cada5b87cc8dccaa76fa49e39d0cb/src/utils/location/findMapStyleUrl.ts#L37
