### ISSUE TITLE
Be sure that people Liste rouge aren't visible

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#78]
If you cannot change your liste rouge status, but the search results do respect the liste rouge status, then this is good enough for a beta version.
Investigate.

**Comment by odelcroi** [comment]
tested : 
- user 1 switches to liste rouge in V2
- user 2 search for user 1 with v4 : user 1 is suggested IF user 2 has already "seen" user 1 (ie user 1 is a contact of user 2)
- user 2 search for user 1 with v2 : user 1 is not suggested

explanation : in v4, suggested users are a mix of local contacts and users discovery. 

it has been tested via API that discovery does not include "liste rouge" users even in v4. It is server side.

**Comment by odelcroi** [comment]
if we consider that the behaviour of V4 is not what tchap wants, we can consider fixint it. Removing beta tag
