### ISSUE TITLE
chiffrement : sur web la barre de "déchiffrement" ne s'affiche plus

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#793]
### Steps to reproduce

1. write messages on a private room
2. disconnect
3. connect
4. go to private room
5. messages are locked, will not be unlocked

### Outcome

When messages are locked, the client tries to unlock them. A status bar is displayed on the top bar of the room. This one : https://github.com/tchapgouv/tchap-web-v4/pull/495

But nothing is displayed 

![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/9b29d345-9d83-4847-bf3d-91a4075e7c5b)

### Impacts

Les mécanismes liées aux chiffrements apportent de la confusion. Cette top bar permet d'expliquer à l'utilisateur ce qu'il se passe et permet de renvoyer vers la FAQ.

**Comment by estellecomment** [comment]
Actuellement la tchap translation est tjs la, mais le code est parti.
- [ ] retrouver à quelle upgrade d'element ca a disparu
- [ ] retrouver la PR d'element qui l'a supprimé, et pourquoi

**Comment by estellecomment** [comment]
PR : Remove DecryptionFailureBar : https://github.com/matrix-org/matrix-react-sdk/pull/11027
In element-web 1.11.34, which Tchap got by upgrading 1.11.30 -> 1.11.39, released in [tchap-4.3.8](https://github.com/tchapgouv/tchap-web-v4/releases/tag/tchap-4.3.8)

Why : "it does not really provide any more benefit to users." 
https://github.com/vector-im/element-meta/issues/1358#issuecomment-1572049548

**Comment by estellecomment** [comment]
Decryption bar was added in element-web 1.11.18. 
Tchap got it in [tchap-4.2.0-1.11.25](https://github.com/tchapgouv/tchap-web-v4/releases/tag/tchap-4.2.0-1.11.25)

**Comment by estellecomment** [comment]
Whatsapp fait ca pour info : 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/911434/72b56f97-701d-4b52-86ce-ae62f9b6242e)

Le message "attends un peu tout va bien" est bcp mieux que "impossible de deverrouiller". Il suffirait de changer de string.
Edit : filed in https://github.com/tchapgouv/tchap-product/issues/221

**Comment by estellecomment** [comment]
I don't think element will re-add something they voluntarily removed.
I don't really want to re-add it in a patch and have to maintain something tricky (element had a lot of problems with it, that's why they removed it)
So I'm not really going to do anything here.

We could open an issue in element-web if we have a simpler need that could be adressed? I don't know. 

Closing.
