### ISSUE TITLE
We advertise features we don't yet have in Welcome page

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#796]
Appels audio et videos illimités, tout à fait oui...
Related : https://github.com/tchapgouv/tchap-web-v4/issues/744
![image](https://github.com/tchapgouv/tchap-web-v4/assets/911434/19e3f527-cde9-4df4-b644-100454507953)

**Comment by Caroline-lawson** [comment]
Je propose, mais à voir avec les BizDev @Nivann @Delphgateau @Raphaelrobert65 

Votre messagerie sécurisée pour le travail
Tchap est le moyen de rester en contact avec vos collègues, grâce à sa messagerie instantanée sécurisée de bout en bout et gratuite.
