### ISSUE TITLE
[web] Slider in "off" position looks disabled

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#810]
On image below, sliders are : disabled, off, off, on. 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/911434/202751837-503621cc-6e10-4d18-8613-2e6e91eef76d.png">

"Off" looks almost the same as "disabled", and I have confused it with disabled. So did Amel, and so did a person who emailed customer support about it.
Grey is commonly used for disabled.

**Comment by odelcroi** [comment]
@areox-net what do you think?

**Comment by areox-net** [comment]
@estellecomment @odelcroi Which version are we talking about? On my Tchap Web i have these for 
Off
Disabled
On

![Screenshot 2023-11-03 at 12 38 20](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/4e2e9b04-4c98-4552-862d-ce03d04c7b81)

**Comment by areox-net** [comment]
For the design mentioned above I would suggest using blue for On, red for Off and faded Grey for Disabled. It's quite heavy visually but it would clear to the users.

**Comment by estellecomment** [comment]
Since this issue was open a year ago the colors have changed, as Angelo has mentioned. 
I find these new colors easy enough to distinguish, and there's also a 🚫 mouse pointer on hover for the disabled case.
I think it's clear enough and doesn't need work.
