### ISSUE TITLE
Change text : "Impossible de déverrouiller le message" -> "Veuillez patienter, les messages sont en cours de déverrouillage..."

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#814]
+ FAQ link
There was a link to the FAQ in the "decrypt" bar that has been broken with the upgrade.

see main issue : https://github.com/tchapgouv/tchap-product/issues/221

**Comment by estellecomment** [comment]
filed in element-web https://github.com/vector-im/element-meta/issues/2191
