### ISSUE TITLE
[Dev] - Change of DNS of homeserver

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#821]
#### What would you like to do?
We need to change https://github.com/tchapgouv/tchap-web-v4/blob/develop_tchap/config.dev.json in order to add the new homeserver : 
https://matrix.dev01.tchap.incubateur.net
https://matrix.dev02.tchap.incubateur.net
https://matrix.ext01.tchap.incubateur.net

#### Why would you like to do it?
The change of DNS was done in dev in order to be ISO with preprod and prod

**Comment by NicolasBuquet** [comment]
Hello @mcalinghee.

Je trouve ça dans les config iOS-dev : 
```
    // Tchap servers
    static let serverUrlPrefix = "https://matrix."
    static let preferredIdentityServerNames = [
        "agent1.tchap.incubateur.net",
        "agent2.tchap.incubateur.net"
    ]
    static let otherIdentityServerNames: [String] = [
        "externe.tchap.incubateur.net"
    ]
    ```

Par contre, j'ai aussi ça : 
```
    // MARK: -  Public rooms Directory
    // List of homeservers for the public rooms directory
    static let publicRoomsDirectoryServers = [
        "agent1.tchap.incubateur.net",
        "agent2.tchap.incubateur.net"
    ]
```

et 
```
static let bugReportDefaultHost = "agent1.tchap.incubateur.net"
    ```

Je peux tous mettre à jour avec vos nouvelles urls ? Vos endpoints gèrent tous les services précédents ?

**Comment by mcalinghee** [comment]
> Hello @mcalinghee.
> 
> Je trouve ça dans les config iOS-dev :
> 
> ```
>     // Tchap servers
>     static let serverUrlPrefix = "https://matrix."
>     static let preferredIdentityServerNames = [
>         "agent1.tchap.incubateur.net",
>         "agent2.tchap.incubateur.net"
>     ]
>     static let otherIdentityServerNames: [String] = [
>         "externe.tchap.incubateur.net"
>     ]
>     ```
> 
> Par contre, j'ai aussi ça : 
> ```
> 
> ```
> // MARK: -  Public rooms Directory
> // List of homeservers for the public rooms directory
> static let publicRoomsDirectoryServers = [
>     "agent1.tchap.incubateur.net",
>     "agent2.tchap.incubateur.net"
> ]
> ```
> 
> ```
> 
> et 
> ```
> 
> static let bugReportDefaultHost = "agent1.tchap.incubateur.net" ```
> 
> Je peux tous mettre à jour avec vos nouvelles urls ? Vos endpoints gèrent tous les services précédents ?



@NicolasBuquet 
Du coup il faudrait changer pour :
agent1.tchap.incubateur.net => dev01.tchap.incubateur.net
agent2.tchap.incubateur.net => dev02.tchap.incubateur.net
externe.tchap.incubateur.net => ext01.tchap.incubateur.net
