### ISSUE TITLE
activer les appels AUDIO sur web pour les users DINUM

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#844]
- [x] Uniquement pour les DM
- [x] Uniquement les appels Audio 
- [ ] Tests liés aux appels

## RoomHeader has been reworked in Element 

`RoomHeader.tsx` and `LegacyRoomHeader.tsx`
the new RoomHeader can be activated with the option : 
```
    "features": {
        "feature_new_room_decoration_ui" : true
..

```

## Activating only the audio button only for DM for Dinum
1/
A patch can be made to filter the render of the button is room is a DM and the user is part of the homeserver dinum

What is the UX difference between both  : 

###  LegacyRoomHeader
<img width="862" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/0818bc6f-3f06-4a85-af9f-22dbc22926db">

### RoomHeader
- DM
<img width="929" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/b9a87549-3ab6-4778-a821-dcfce656e5d6">

- Room
<img width="663" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/db94bc35-b892-4c5b-a382-bdcba536c8e0">

## Throughts

- The new version is lighter
- It is way easy to customize RoomHeader.tsx than LegacyRoomHeader
- LegacyRoomHeader is flagged as deprecated in the code

> it seems to be a good idea to activate the new RoomHeader.tsx

## Questions
- [ ] what is the status of the new version in terms of development?
- [ ] is there dramatic UX impacts if we activate it? 
- [x] activate new room header in tchap labs

**Comment by estellecomment** [comment]
Would be nice to do the modifications (buttons to hide, etc) as a module if possible. 
Modules should allow us to have no regressions (or less regressions :)) in the future, since element will know about the module's hooks in element-web, and won't break them.

**Comment by odelcroi** [comment]
added desc on RoomHeader and LegacyRoomHeader

**Comment by odelcroi** [comment]
regresionns : 
- external room header is not displayed
- forum icon is displayed
