### ISSUE TITLE
Encrypted messages : display helpful actions next to the message

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#85]
We had made changes in v2 for the problem of lost keys, based on user reasearch.
v4 changes the UX around keys, compared to v2.

Based on our previous user research, make a list of changes to v4 to mitigate the problem of lost keys.
Evaluate if these changes should be pushed into element, or be custom tchap code.

**Comment by odelcroi** [comment]
This panel could be migrated to the current version

![Capture d’écran 2022-10-24 à 16 53 03](https://user-images.githubusercontent.com/4077729/197556795-6d4da1e6-448e-4681-8186-912ada8c3da9.png)

**Comment by estellecomment** [comment]
Currently that panel shows :
<img width="675" alt="image" src="https://user-images.githubusercontent.com/911434/200641693-ef1191a9-ca83-40cc-b395-1b56aa7c4081.png">
Missing "import from file".

Once you click on "re-request" you see : 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/911434/200641856-ce7c150e-8c6f-4752-84e2-2df7dbaa9ea5.png">
Missing "resend". (refreshing the page gets you back to the previous state, with which you can resend)

**Comment by estellecomment** [comment]
v2, version francaise, avec le help tip ouvert : 
<img width="627" alt="Screen Shot 2022-11-10 at 2 19 29 PM" src="https://user-images.githubusercontent.com/911434/201102451-4404db87-ff70-4d78-913f-5691a970411d.png">

**Comment by estellecomment** [comment]
v2, apres avoir cliqué sur "renvoyer une demande à un autre appareil":
<img width="615" alt="Screen Shot 2022-11-10 at 3 01 12 PM" src="https://user-images.githubusercontent.com/911434/201111711-7e970abf-67c6-4174-8c85-48c5cc187f9b.png">
