### ISSUE TITLE
"Se connecter à la place" is not clickable anymore

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#860]
### Steps to reproduce

<img width="701" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/c18df4f5-b980-4017-b15c-a1105d3bd976">

### Outcome

"Se connecter à la place" is not clickable

### Will you send logs?

No

**Comment by estellecomment** [comment]
It's a translation problem : https://github.com/element-hq/element-web/issues/26457
Solved by upgrades normally

**Comment by estellecomment** [comment]
Fixed by upgrade to 1.11.46
https://github.com/tchapgouv/tchap-web-v4/pull/846 (when it's merged)
