### ISSUE TITLE
Les messages reçus pendant une déconnexion ne se déverrouillent pas après reconnexion

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-web-v4#861]
### Steps to reproduce

Situation remontée par le correspondant pôle emploi. Ecran partagé avec lui pour faire le test
1. Historique de message visible pour Sylvain
2. Déconnexion de Sylvain de sa session web (3mn environ)
3. Envoi de trois messages pendant la déconnexion par Delphine
4. Reconnexion de Sylvain avec code de récupération
5. L'historique est visible sauf les 3 messages envoyés pendant la déconnexion
6. Envoi d'un nouveau message par Delphine -> lisible 

#### What did you expect?
Que les messages envoyés pendant la déconnexion soit déverrouillés après la reconnexion puis copier/coller du code de récupération ?

### Operating system

Windows

### Browser information

Chrome

### Application version

dernière version

### Will you send logs?

Yes

**Comment by yostyle** [comment]
Si il n'y a aucun autre appareil qui a recu et déchiffré les messages ils seront verrouillés sur le "nouvel appareil" lors de la reconnexion.

Pour éviter cela il faut conserver les données du sites dans le navigateur même après un redémarrage du PC.
