### ISSUE TITLE
Warn users that they should NEVER be disconnected from Tchap Web

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#863]
## Why 
Users don't understand that being disconnected from Tchap web implies negativces side effects with locked messages. 
Being disconnected from an app usually does not have negative side effect but as Tchap is client-side based, it does.

## What
We should warn them that if they got disconnected from their Tchap Web, they face dramatic consequences
We should warn them to not disconnect intentionnaly
We should warn them that if they got disconnected automatically (for isntance by a browser security policy) they should fix this problem

Since now we propose a FAQ : https://aide.tchap.beta.gouv.fr/fr/article/pourquoi-dois-je-me-connecter-regulierement-a-tchap-web-sur-ordinateur-cookie-web-18f48zi/

## How
Ideas :
- a warning message when they login to Tchap (ie maybe they got disconnected before this login)
- a warning message when they try to disconnect

**Comment by MarcWadai** [comment]
Warning messages are included in recent element updates
