### ISSUE TITLE
"Vous n'avez pas la permission de démarrer un appel audio"

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#868]
L'icone appel est grisée avec ce messaage hovertext. (sur firefox) Je ne peux pas appeler.
Je n'ai pas les permissions. 
On m'appelle, je décroche, l'appel audio et video marche. Les permissions sont maintenant présentes au niveau du browser. 
L'icone appel est tjs grisée, meme apres refresh.

**Comment by odelcroi** [comment]
Due to this condition to be falsy : 
        room.currentState.mayClientSendStateEvent(ElementCall.CALL_EVENT_TYPE.name, room.client),

**Comment by odelcroi** [comment]
In Tchap DM, only one participant is an admin, only this person can fire an audio call
In Element, both participants of a DM are admin so default permission allow audio call

This might be a BUG

**Comment by odelcroi** [comment]
The person who initiates the DM is admin. The other is not.
Reproduced on : 
- web
- ios
- android

**Comment by odelcroi** [comment]
backend issue : https://github.com/tchapgouv/tchap-backend/issues/18

**Comment by odelcroi** [comment]
quick fix : https://github.com/tchapgouv/tchap-web-v4/pull/869
