### ISSUE TITLE
Impossible to limit new forum to federation or not

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#87]
#### What would you like to do?
In Tchap v2 : 
![image](https://user-images.githubusercontent.com/1238254/177528481-0adeadd9-08e7-4fff-9b15-48a84ded5960.png)

#### What is the current implementation ?
In Tchap v4 : 
![image](https://user-images.githubusercontent.com/1238254/177528672-ffbddad6-79be-4926-8a21-1d8dcb51869e.png)

**Comment by estellecomment** [comment]
You have shown what v2 and v4 currently do.
What is the problem you want to solve ?

**Comment by estellecomment** [comment]
Currently v4 hides the switch for all servers except intradef, because it is difficult to understand and makes users confused. We had decided this with Design.

We show it for intradef because in the past the correspondant explicitly asked for it. But we could revisit with them, to remove the switch for intradef as well.

Code : https://github.com/tchapgouv/tchap-web-v4/blob/5ed99d7d15e74f2890a284a2280077a967aebb3c/src/util/TchapUtils.ts#L29

**Comment by jdauphant** [comment]
> Currently v4 hides the switch for all servers except intradef, because it is difficult to understand and makes users confused. We had decided this with Design.
> 
> We show it for intradef because in the past the correspondant explicitly asked for it. But we could revisit with them, to remove the switch for intradef as well.
> 
> Code :
> 
> https://github.com/tchapgouv/tchap-web-v4/blob/5ed99d7d15e74f2890a284a2280077a967aebb3c/src/util/TchapUtils.ts#L29

Ok I didn't know that. Interieur may use it too. We will need to test/discuss with users to see if they need it.
It's not urgent.

**Comment by estellecomment** [comment]
@jdauphant can we close this ? If users have a problem, we can reopen.

**Comment by jdauphant** [comment]
if it's visible for intradef, it's good, we can close.

@JDixmier and @Nivann will need to know about it

**Comment by JDixmier** [comment]
So the point is to remove the feature that allows users to create a forum opened to only one instance ?
And to make an exception for intradef and maybe interieur ?

indeed some support cases have shown that this feature (and the fact it was setup by default) was very confusing

**Comment by estellecomment** [comment]
Yes. Intradef users see the switch, they can choose. All other users don't see the switch, so they create public rooms that are federated by default.

**Comment by odelcroi** [comment]
I'm closing this conversation as everyone agrees that V4 complies with what is required for Intradef users
