### ISSUE TITLE
I would like to open a link on a room description

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#873]
### Steps to reproduce

1. Go to a room
2. When room description has a link, I would like to open it

#### What did you expect?
- Click on the link

#### What happened instead?
- Link is not clickable

![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/a5e236fd-82f6-475a-b435-c63243fbc35b)

### Will you send logs?

Yes

**Comment by estellecomment** [comment]
fixed with element upgrade
