### ISSUE TITLE
Translation : "Forgot password" en francais

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-web-v4#874]
### Your use case

Sur la page d'accueil, lorsqu'on clique sur "se connecter", on a l'option "forgot password". Pourrait-on mettre le message en français ?
<img width="577" alt="Capture d'écran 2024-01-19 151108" src="https://github.com/tchapgouv/tchap-web-v4/assets/121094938/242750e0-7dbd-4786-aabe-bf850e57df60">

**Comment by estellecomment** [comment]
Caused by an upgrade, because the translations are missing in element : https://github.com/element-hq/element-web/issues/26456
Should be solved by more upgrades (or adding translation by hand)

**Comment by estellecomment** [comment]
Will be fixed in 1.11.58
