### ISSUE TITLE
Retirer la possiblité de crééer des espaces public

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#878]
![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/13c599fa-8c7a-442e-bfd8-603e762f1044)

**Comment by MarcWadai** [comment]
@areox-net dans ce cas là, au lieux même de retirer le bouton "Public" est-ce qu'on ne mettrait pas la prochaine page directement ? C'est à dire directement sur la création d'un espace privé : 

![Image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/8d0eb530-a2b1-46f2-96ef-53c0c03a7a6d)

Ou est-ce qu'on perdrait de l'information dans ce cas ? Car il y a effectivement une première explication des espaces dans l'entête. Il est aussi possible de modifier l'entête de cette deuxième si on arrive directement sur celle-ci

**Comment by areox-net** [comment]
@MarcWadai Oui, c'est bien ce qu'on avait envisagé sur mobile au début des reflexions sur les Spaces: sauter la première étape et bouger titre et texte d'intro dans la deuxième. 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/4ea4d47f-2419-48ae-a72f-cc4dcedba22a)

**Comment by MarcWadai** [comment]
Si on laisse la possibilité de créer des sous-espaces https://github.com/tchapgouv/tchap-web-v4/issues/1064, il faudra aussi retirer l'option public de cette liste

**Comment by MarcWadai** [comment]
@areox-net  Dans la phrase de description je rajouterais bien "En savoir plus" avec le lien vers la FAQ
