### ISSUE TITLE
Nouveau code de récupération (juste généré sur Android) non accepté par le client web

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-web-v4#884]
## pour reproduire
- connecter et vérifier un appareil Android
- connecter et vérifier un appareil Web
- se déconnecter de Web
- se connecter à Web
- renouveller le code de recup Android
- rentrer ce code sur Web

## Description
Ce matin (05/02/2024) Delphine était déconnectée de son Tchap web sur Chrome (hypothèse : nettoyage des local data par manque de place sur l'ordinateur ?).

Au login, le client web lui demande son code de récupération pour accéder à ses messages.

Elle le régénère sur Android et le copie sur web.

Ce dernier accepte le code mais le redemande ensuite en boucle.

Il semble en fait que, bien qu'il le redemande, la première saisie ait été acceptée, car les messages finissent par se déverrouiller malgré le message d'erreur.

https://github.com/tchapgouv/tchap-web-v4/assets/18608158/93c2aa0b-fa0c-435e-b31f-35581010cbba

<img width="1358" alt="Screenshot 2024-02-05 at 10 16 04" src="https://github.com/tchapgouv/tchap-web-v4/assets/18608158/668775d9-2587-45c4-abac-ebb491a8ab1e">
<img width="1352" alt="Screenshot 2024-02-05 at 10 16 58" src="https://github.com/tchapgouv/tchap-web-v4/assets/18608158/759a7fe2-8283-4ff8-a7ef-4a41dfc92ea9">

**Comment by odelcroi** [comment]
lié avec https://github.com/tchapgouv/tchap-ios/issues/951 ?

**Comment by odelcroi** [comment]
Merci pour le ticket,
est ce que cette FAQ a résolu le problème : https://aide.tchap.beta.gouv.fr/fr/article/mon-code-de-recuperation-est-refuse-b7suxq/

**Comment by Delphgateau** [comment]
@odelcroi non, on a tenté en live de déconnecter la session ayant besoin du Code de Récupération mais cela n'a rien changé. Pour rappel ma session mobile est sur Android

**Comment by yostyle** [comment]
Ajouter les infos de debug

**Comment by odelcroi** [comment]
@Delphgateau tu utilises quel URL de tchap web et quelle version de l'appli Android?

**Comment by Delphgateau** [comment]
web : https://app-v4.prod.lab.tchap.incubateur.net/
mobile : 2.10.0

**Comment by Delphgateau** [comment]
[Console bug Delphine.docx](https://github.com/tchapgouv/tchap-web-v4/files/14220746/Console.bug.Delphine.docx)

**Comment by estellecomment** [comment]
Dans notre dernière upgrade massive (14 versions youhou), ya un bug similaire (mais pas clairement pareil) qui a été fixé : 
https://github.com/element-hq/element-web/issues/26321

Je vais tester si je peux le reproduire post-mega-upgrade.

**Comment by estellecomment** [comment]
Login avec email et mot de passe. On arrive ici (SetupEncryptionBody): 

<img width="662" alt="Screen Shot 2024-03-11 at 3 36 03 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/5ef6d594-131d-492b-904a-072df57ff8bc">

A ce stade, deux flows possibles : 

FLOW 1 qui fail 🟥 
 - a. click "Verifier avec un code de recuperation" : ca ouvre le dialogue suivant pour input le code (AccessSecretStorageDialog)

<img width="582" alt="Screen Shot 2024-03-11 at 3 38 15 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/2786d955-f58c-49c0-98ed-31d4c68aaf13">

 - b. changer le code de recup sur android
 - c. input le code

On obtient : 
<img width="588" alt="Screen Shot 2024-03-11 at 3 39 16 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/0208c0ea-788d-4619-856d-5ee0357a0ebb">

On est coincé, "Continuer" est bloqué.

FLOW 2 : presque pareil mais dans le desordre, et qui marche  🟩 
 - b. changer le code de recup sur android
 - a. click "Verifier avec un code de recuperation" pour ouvrir AccessSecretStorageDialog
 - c. input le code
 
 On obtient :
<img width="591" alt="Screen Shot 2024-03-11 at 3 42 17 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/b5e9133d-398a-40c6-a4b1-89836055ad79">

Et on peut continuer, les messages sont bien decryptes.

Note : apres flow 1, on peut annuler, et du coup on se retrouve dans flow 2 : le code est deja créé, on ouvre AccessSecretStorageDialog, on input le code, et c'est bon.


--> Donc **il y a un workaround simple : cliquer "Revenir en arriere" et recommencer : "Verifier avec un code de recuperation"**

**Comment by estellecomment** [comment]
Il y a sans doute qq chose qui est initialisé quand on clique "Vérifier avec un Code de Récupération" ("encryption|verification|verify_using_key"), et qui n'est pas refreshed quand on input le code, donc qui n'a pas le nouveau code.
Je vais voir si on peut reproduire sur element-web, pour jeter cette balle de l'autre coté de la barrière :)

**Comment by estellecomment** [comment]
Filed in element-web : https://github.com/element-hq/element-web/issues/27155

**Comment by odelcroi** [comment]
@estellecomment @MarcWadai  De notre coté, mentionner ce workaround dans nos FAQ clot cette tache ?

**Comment by estellecomment** [comment]
Trop difficile de suivre le fil d'execution du code sans documentation pour comprendre comment il est organisé. J'abandonne.

Du coup, pour compenser, FAQ mise à jour : https://aide.tchap.beta.gouv.fr/fr/article/mon-code-de-recuperation-est-refuse-b7suxq/
