### ISSUE TITLE
Web : Voip : signalier une anomalie avec logs après un appel

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#888]
voir ticket master

**Comment by estellecomment** [comment]
J'ai investigué comment savoir si ya un casque BT. On peut le savoir que sur Chrome, ya pas les API dispo sur firefox et edge. 
Donc je vais faire 3 valeurs du champ audio_input : "headset_bluetooth", "device" et "unknown". 
Parce que ya qd meme pas mal de unknown et ca va fausser les stats.

**Comment by estellecomment** [comment]
En fait non, je peux meme pas forcement faire la difference entre "device" et "unknown". 
Donc ca sera "headset_bluetooth" et "device", mais "device" peut vouloir dire un peu n'importe quoi.
