### ISSUE TITLE
Etudier l'usage de OIDC sur Tchap Web 

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#891]
P1 : etq new user, je veux me connecter à Tchap par AC
P1 : etq user legacy, je veux me connecter par AC
P1 : etq user ac, je veux me connecter par AC

## Description 

Flow a implémenter pour présenter le bouton Agent Connect à partir de l'email : 

vu avec @yostyle : 
- Avoir un premier écran où on demande uniquement l'email de l'utilisateur.
- On requête le backend pour récupérer le homeserver qui correspond à l'email.

API spécifique à Tchap :
https://github.com/matrix-org/sydent/blob/dinsic/docs/info.md
https://github.com/tchapgouv/email-matching-api

- Le front requête le backend pour savoir si un FI (Agent Connect) est configuré. Quand on configure le homeserver dans les clients ca se fait automatiquement

- Le bouton "se connecter avec agent connect" s'affiche si c'est bien supporté.

- On doit proposer une fallback pour pouvoir saisir son mot de passe Tchap si l'utilisateur ne peut pas s'authentifier par le SSO

## Annexes OIDC
Explication de comment marche oidc sur un client matrix : https://areweoidcyet.com/client-implementation-guide/

Issue sur le login OIDC on Element Web : https://github.com/element-hq/element-web/issues/25392

Documentation web : https://github.com/element-hq/element-web/blob/develop/docs/oidc.md

Présenter un bouton custom de oidc provider "Agent Connect" dans Tchap Web : https://github.com/element-hq/element-web/issues/26936#issuecomment-1914206121

Oidc Flow : https://spec.matrix.org/v1.9/client-server-api/#client-login-via-sso

**Comment by MarcWadai** [comment]
## Uses cases to tests : 
- [ ] J'ai pas de compte legacy, je me connecte directement avec AC
- [ ] J'ai un compte legacy et je me connecte avec AC -> je récupère bien les même infos qu'avec mon compte legacy
- [ ] Mes codes de sécurité marche toujours bien même avec un double compte legacy et AC
- [ ] Le flow de reset password marche toujours avec mon compte legacy
- [ ] Quand je me connecte avec AC, j'arrive sur le bon homeserver

**Comment by odelcroi** [comment]
from @yostyle : 

- Avoir un premier écran où on demande uniquement l'email de l'utilisateur.
- On requête le backend pour récupérer le homeserver qui correspond à l'email.

API spécifique à Tchap :
https://github.com/matrix-org/sydent/blob/dinsic/docs/info.md
https://github.com/tchapgouv/email-matching-api

- Le front requête le backend pour savoir si un FI (Agent Connect) est configuré. Quand on configure le homeserver dans les clients ca se fait automatiquement

- Le bouton "se connecter avec agent connect" s'affiche si c'est bien supporté.

- On doit proposer une fallback pour pouvoir saisir son mot de passe Tchap si l'utilisateur ne peut pas s'authentifier par le SSO

**Comment by odelcroi** [comment]
closing in favor of #1094 ?
