### ISSUE TITLE
Rollout progressively the new Rust crypto SDK

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#901]
See : https://github.com/element-hq/element-web/blob/develop/docs/labs.md#use-the-rust-cryptography-implementation-feature_rust_crypto-in-development

This new crypto SDK is on by default but can be deployed progressively, what should we do?

**Comment by estellecomment** [comment]
From docs : 

For administrators looking to transition existing users to the new stack, the `RustCrypto.staged_rollout_percent` configuration is available.
This configuration allows for a phased migration of users, represented as an integer percentage (0 to 100). By default, this value is set to `0`,
which means no existing users will be migrated to the new stack. If you wish to migrate all users, you can adjust this value to `100`.

This configuration should be placed under the `setting_defaults` section as shown:

```
    "setting_defaults": {
        "RustCrypto.staged_rollout_percent": 20
    },
```

**Comment by estellecomment** [comment]
From comments in https://github.com/matrix-org/matrix-react-sdk/blob/v3.92.0/src/MatrixClientPeg.ts#L331
"At some point, we'll allow the user to *enable* the setting via labs, which will migrate their existing
        // device to the rust-sdk implementation"

**Comment by estellecomment** [comment]
Tests I made on tchap with 1.11.58 for behavior of flag : 

- [x] add flag to disable crypto in config and test behavior
   - [x] set flag to false : no changes in crypto (according to Aide et A propos), still olm
   - [x] set flag to true, reload page : no changes in crypto, still olm
   - [x] logout, login : crypto is now rust. Messages in various channels take a few seconds to arrive, but not long enough for me to do something about it.
   - [x] set flag to false, reload page : current device stays in rust crypto.
   - [x] logout, login (flag is still false) : crypto is back to olm
   
Any existing devices keep their crypto type (rust or olm), even if the server flag changes.
When the flag is true (or absent : default = true), any new logins will create a rust-crypto device.
When the flag is false, any new logins will create a olm-crypto device.

(this is exactly what the docs say, happily :) )

**Comment by MarcWadai** [comment]
Don't start the rollout until this issue is fix on element side:  https://github.com/element-hq/element-web/issues/27165

This problem has flooded our server. CPU charge of main worker works at 120% due to Element Web users in instance "social" and "finance"

**Comment by odelcroi** [comment]
Matrix JS sdk 33 fixes the problem : https://github.com/matrix-org/matrix-js-sdk/pull/4216

https://github.com/matrix-org/matrix-js-sdk/releases/tag/v33.0.0

**Comment by MarcWadai** [comment]
- [ ] Check the stats to see how many people have activated secure backup in web. To mitigate risk of messages loss during migration
- [ ] Check no more blocking issues are open about rust crypto
