### ISSUE TITLE
Why is 'Experimental' available on app-v4

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#906]
### Steps to reproduce

1. Login to [app-v4.prod.tchap.incubateur.net](https://app-v4.prod.tchap.incubateur.net/)

#### What did you expect?
Experimental section should not be visible

#### What happened instead?
![Capture d’écran 2024-02-15 à 10 44 22](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/72a1b116-e198-47d3-9547-6b71e416fb48)

### Will you send logs?

Yes

**Comment by odelcroi** [comment]
[app-v4.prod.tchap.incubateur.net](https://app-v4.prod.tchap.incubateur.net/) uses[ 'prod' config ](https://dashboard.scalingo.com/apps/osc-secnum-fr1/tchap-v4-prod/environment)

Can not reproduce locally with 'prod' config : 

![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/9d4d76de-a675-4467-8140-0e2b454c864b)

**Comment by estellecomment** [comment]
it's because Developer Options is activated for your account. Since the last upgrade (1.11.53)
I can't find where that's activated any more though, and I don't know what it does. :)

**Comment by estellecomment** [comment]
Ah yes, it's in `\devtools`

<img width="757" alt="Screen Shot 2024-02-15 at 3 18 20 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/6bbb14c2-ebb1-4e7b-b6ee-864eeb0c4891">

**Comment by odelcroi** [comment]
closed as will not fix
