### ISSUE TITLE
Check experience as an external, lot of things should be forbidden

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#91]
### Your use case

As external, I can't :
- Invite
- Create Room/Space
- Be an admin
- Join a public room
- [edit Estelle] modify room settings

**Comment by jdauphant** [comment]
It looks more easy from what I thinking first

**Comment by jdauphant** [comment]
Inspiration on react-sdk-v4 to determine if an user is external : https://github.com/tchapgouv/matrix-react-sdk-v3/blob/develop/src/tchap/Tchap.ts#L146-L191

**Comment by mcalinghee** [comment]
Note : An alternative of this ticket is to forbid external users to login

**Comment by pseudonyme21** [comment]
Try  to log with an external account is ok :
<img width="771" alt="Capture d’écran 2022-09-22 à 18 01 34" src="https://user-images.githubusercontent.com/11921231/191797963-ede1007b-bc68-454b-8d59-4b38ae1697f2.png">

I have to select my homeserver
<img width="717" alt="Capture d’écran 2022-09-22 à 18 02 06" src="https://user-images.githubusercontent.com/11921231/191798191-75553714-0d43-4b3c-8081-07e78565dcc4.png">

I can't find any public room to join
[edit maghen: upload proof that we cannot find any public room to join]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/3725676/191996267-dbcb6eab-3e68-468b-82fb-87bb95334360.png">

I can't start and find a user for a DM
<img width="1050" alt="191798537-653a92ea-9286-42fc-8b50-2cb15af6575e" src="https://user-images.githubusercontent.com/3725676/192224063-81f55af2-7eaa-49a3-a07c-2be8cd7da3d8.png">


I can't create, public, private or private with external rooms
<img width="703" alt="Capture d’écran 2022-09-22 à 18 06 21" src="https://user-images.githubusercontent.com/11921231/191798808-a86c2251-0bdd-4581-83e8-8367461eab79.png">

**Comment by jdauphant** [comment]
@pseudonyme21 
![image](https://user-images.githubusercontent.com/1238254/191919310-d213f251-24aa-4c89-8df3-ff214f05830f.png)
You test isn't valide : you need to change the homeserver : 
![image](https://user-images.githubusercontent.com/1238254/191938050-2156a178-bcab-4d37-bc32-66d4cca53203.png)

**Comment by estellecomment** [comment]
Added another test suggestion : when you are in a room, or in a DM, can you modify settings for the room ? (you should not be able to)

**Comment by jdauphant** [comment]
If you enter an ID can you open a DM ?

**Comment by mcalinghee** [comment]
- [x] Cannot edit room settings for an external : OK

General tab : 
Everything is disabled
We can only leave the room
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3725676/192000576-d559f664-ea08-4d49-a3d5-74faa620bba5.png">

Security tab : 
Note that the encryption cannot be changed as it is disabled and all other settings are disabled as well :
<img width="682" alt="Screenshot 2022-09-23 at 17 49 11" src="https://user-images.githubusercontent.com/3725676/192001411-14ef15d3-7015-42ad-b08b-654130a7b351.png">

Roles and Permission : 
<img width="742" alt="Screenshot 2022-09-23 at 17 47 50" src="https://user-images.githubusercontent.com/3725676/192001542-701dd7cc-11de-422f-bfac-014e4b9057ba.png">

Notifications :
Notifications can be modified
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3725676/192001703-b41f0c0f-91c3-450c-8c23-3cfb100bd8dc.png">

Advanced :
Nothing can be changed
<img width="491" alt="192001812-bda092ba-b951-4c8b-93ce-071edc2374e3" src="https://user-images.githubusercontent.com/3725676/192224975-9f3dfbfb-3c7b-42ba-b64a-42d262196020.png">

**Comment by mcalinghee** [comment]
- [x] Cannot join a public room by id : OK
<img width="713" alt="192002356-ed7f7719-5b9b-49b6-af75-168fb3ccf554" src="https://user-images.githubusercontent.com/3725676/192225069-84e989f5-07b5-4a3a-8b6a-3338998958d2.png">

**Comment by mcalinghee** [comment]
- [x] An internal user cannot give `Admin` or `Moderator` role to external user:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/3725676/192003804-6f8d6a68-f4dd-414c-ba00-dcd41df82649.png">

When trying to set admin or moderator, we have a failure :
<img width="738" alt="image" src="https://user-images.githubusercontent.com/3725676/192003905-6b2cded6-046a-459c-9821-39934ed9e0fd.png">

**Comment by mcalinghee** [comment]
Can we close this issue if we do not have anymore scenarios ?

**Comment by estellecomment** [comment]
Looks good to me :) Thanks !
