### ISSUE TITLE
Fermeture d'une room publique qui prête à confusion et dont l'admin n'est plus dispo (urgent)

### ISSUE THREAD

**Issue by bolinocroustibat** [tchapgouv/tchap-web-v4#919]
Nous sommes confronté à un problème. Une room publique est nommée comme notre service mais son admin est une personne qui ne fait plus partie de la DINUM depuis plusieurs années (et qui n'est plus dans la fonction publique je crois d'ailleurs). Personne de notre service ne peut l'administer, la modérer ni la supprimer. Cette room est nommée du nom de notre service et donc est susceptible de prêter à confusion, d'être mal utilisée, ou de servir à de l'impersonification du service sans que nous n'y pouvions rien.

**1. Dans un premier temps (urgent) :**

Il faudrait donc supprimer cette room le plus vite possible.

**2. Feature request (au passage) :**

Feature request : pouvoir faire en sorte de demander à rependre la main sur un channel abandonné.
Ouvert à la discussion pour trouver une solution adéquate et sûre.

Merci !

**Comment by odelcroi** [comment]
Bonjour,
Ce repository étant public, nous évitons d'y exposer des donnés personnelles. Pourriez-vous nous envoyer une demande de suppression room à notre adresse du support. 
Je vais traiter la feature request dans une autre issue

**Comment by bolinocroustibat** [comment]
@odelcroi Bonjour, oui aucun problème, effectivement vous avez raison, toutes mes excuses.
En revanche je ne trouve pas l'adresse de support, pouvez-vous la communiquer, puis fermer et effacer ce ticket ?
Merci !

**Comment by bolinocroustibat** [comment]
En attendant j'ai supprimé les infos privées du ticket.

**Comment by odelcroi** [comment]
merci, la voici :  https://tchap.beta.gouv.fr/#contact

**Comment by bolinocroustibat** [comment]
Merci, vous pouvez effacer le ticket donc.
