### ISSUE TITLE
Is there a Tchap public API?

### ISSUE THREAD

**Issue by bolinocroustibat** [tchapgouv/tchap-web-v4#928]
#### What would you like to do?

We would love to use Tchap for GitHub/GitLab/Project Management software to automatically post messages on some rooms we are admin of, in order to automate some functions and improve team efficiency.

#### Why would you like to do it?

Is there any Tchap API feature available or planned to be available, so we could post messages automatically?

#### How would you like to achieve it?

Could be done using the room ID, for the rooms we are admins, with an API key + API secret key, with a limit of posted messages per day or hour to avoid overutilization or high load.

### Additional context

I know it's a very large feature to implement if it doesn't exist already :)

**Comment by MarcWadai** [comment]
You can find the documentation about creating bots and integrations here https://aide.tchap.beta.gouv.fr/fr/article/documentation-technique-bot-et-integrations-tchap-1z3dfx/
