### ISSUE TITLE
Change home to Tchap Design

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#93]
### Your use case

We can remove Vector* and create TchapAuthPage (We can even embed the landing page here ^^)
https://github.com/tchapgouv/tchap-web-v4/tree/develop_tchap/src/components/views/auth

V2 home page : 
![Capture d’écran 2022-09-01 à 09 37 45](https://user-images.githubusercontent.com/4077729/187859071-311f6631-caff-4306-90ed-91748d4ccea0.png)

V4 home page : 
![Capture d’écran 2022-09-01 à 09 39 26](https://user-images.githubusercontent.com/4077729/187859252-ad86953d-12d0-4310-8964-42b9203b2eec.png)

**Comment by estellecomment** [comment]
Not needed for beta

**Comment by odelcroi** [comment]
Added screenshots, what is needed to do here? @areox-net

**Comment by areox-net** [comment]
@odelcroi not sure what @jdauphant means here. 
Julien, do you mean that we could replace the login page with another page (ex. landing page) and have the login page at a second level?

**Comment by jdauphant** [comment]
We have already implemented this ticket
