### ISSUE TITLE
Include technical information in rageshake (feedback - "Commentaire)

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#935]
### Steps to reproduce

1. Send a commentaire from tchap web (Menu : Commentaire)
2. it creates a rageshake and a ticket in crisp

#### What did you expect?
I expect technical information such as : platform, browser, logs etc.. Similar to rageshakes from Tchap mobile

#### What happened instead?
- we have only the matrixId and the user message 
- Technical Information is missing
- No logs are attached

![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/f75fa7b4-aed6-43cb-afec-5d6b1e115881)

### Will you send logs?

No

**Comment by odelcroi** [comment]
Whereas rageshake sent from auto-uisi are much more documented and have logs : 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/f101a150-7e58-405a-a5e0-21e166a4805d)

**Comment by odelcroi** [comment]
When going into : 
Menu>Aide et A propos> Signaler une anomalie

Le rageshake envoyé contient toutes les informations techniques et les logs 👍  

 
<details><summary>Ecran</summary>
<p>

<img width="875" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/0778c4a6-c516-450d-95ba-beab5dcda63c">

</p>
</details> 


<details><summary>Rageshake</summary>
<p>

<img width="582" alt="Capture d’écran 2024-03-14 à 14 33 45" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/6d72b2e1-e0ce-4a9a-944a-82c445eab492">


</p>
</details>

**Comment by estellecomment** [comment]
so we can just remove the "Commentaire" feature, and use the "Signaler une anomalie" feature, and we're good ?

**Comment by odelcroi** [comment]
> so we can just remove the "Commentaire" feature, and use the "Signaler une anomalie" feature, and we're good ?

I think so
