### ISSUE TITLE
Upgrade : 1.11.59 - 1.11.60 - 1.11.61

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#939]
Currently at 1.11.58.
What's new in the upgrade ?

**Comment by estellecomment** [comment]
[1.11.59](https://github.com/element-hq/element-web/releases/tag/v1.11.59)
- https://github.com/matrix-org/matrix-react-sdk/pull/12240 permet de remettre nos couleurs de user avatars. Il faut changer un peu la config, lire la doc.
- OIDC fixes (we don't use OIDC yet but that's nice to know)
- TAC (threads activity center, in labs) fixes. Seems to deal with notifications. Hopefully moves the threads stability forward. See [screenshots in PR](https://github.com/matrix-org/matrix-react-sdk/pull/12136)

**Comment by estellecomment** [comment]
[1.11.60](https://github.com/element-hq/element-web/releases/tag/v1.11.60)
- encore du OIDC
- [changes on rageshake for UISI](https://github.com/matrix-org/matrix-react-sdk/pull/12304/files) : en particulier ca ne renvoie pas de rageshake si on vient d'en envoyer un (pour eviter le spam je suppose)

**Comment by estellecomment** [comment]
[1.11.61](https://github.com/element-hq/element-web/releases/tag/v1.11.61)
Juste un bugfix sur compound (gestion des couleurs des avatars?)
Toute petite release, donc la faire en meme temps que 1.11.60 dans tous les cas.

**Comment by MarcWadai** [comment]
check [PR #947](https://github.com/tchapgouv/tchap-web-v4/pull/947)
