### ISSUE TITLE
Suggestion for tchap-web-v4 repository : never rebase on Element Web

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#94]
### Your use case

Element-Web only have a few change from react-sdk.
We can clean up this repository from element specific code and never rebase on element-web (We develop Tchap-web base on react sdk).

**Comment by estellecomment** [comment]
@jdauphant as we discussed, there is actually complicated code within element.
Do you want to discuss and evaluate this some more, or close ?

**Comment by jdauphant** [comment]
It could be nice to do a 1h workshop

**Comment by odelcroi** [comment]
Outdated issue, feel free to reopen.
