### ISSUE TITLE
Participer au lancement de tchap annonces et notifs mail

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#940]
- [x] add feature flag to limit email notifications to individual homeservers (already done :D)
- [x] Flag currently limited to Dinum. Set it to all homeservers (list them all in the config.json). Default = off.
- [x] faire une release
- [x] deployer ! (pas besoin d'attendre le backend)

< à remplir en fonction de ce qu'on trouve à faire >

**Comment by odelcroi** [comment]
ouvrir à tout le monde l’option de notif email à tout le monde (feature flag)
(remove this comment after use)

**Comment by estellecomment** [comment]
> ouvrir à tout le monde l’option de notif email à tout le monde (feature flag) (remove this comment after use)

ouais nan moi j'aime pas supprimer les commentaires :D

**Comment by estellecomment** [comment]
Note : notre flag actual cache/montre le bouton pour activer/desactiver les notifs.
Par contre il n'arrete pas l'envoi de mails. 

Ex : le flag est on, je vois le bouton, j'active les notifs.
Le flag passe à off, le bouton est caché, mais je continue de recevoir les notifs.

**Comment by estellecomment** [comment]
Pour les desactiver il faudrait faire un appel au backend, par l'intermediaire du MatrixClient, comme ca : 
https://github.com/matrix-org/matrix-react-sdk/blob/v3.92.0/src/components/views/settings/Notifications.tsx#L439
Il faudrait le faire on webapp startup (chepa trop ou)... 
Et ca ferait un reset du setting pour tous les users qui ont restarté l'app, mais pas les autres...
Bref c'est un peu bordélique et compliqué. 

Je vote : une fois que le setting est montré aux users, il reste montré pour toujours, et ils se debrouillent eux-memes pour le mettre on/off.
