### ISSUE TITLE
Can "Known Issues" be removed now ? 

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#944]
In the Help settings, we have a section "Problèmes connus"/"Known Issues", it was added in the first days of tchap-web v4 :

<img width="1049" alt="Screen Shot 2024-03-22 at 10 34 13 AM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/f2e9f0dc-3c7e-4796-981a-1797d8bad8b2">

It directs to this wiki page : https://github.com/tchapgouv/tchap-web-v4/wiki/Nouveau-Tchap-Web

Some issues are still current :
 - "utilisateurs externes" still see buttons that trigger errors (buttons should be hidden) -> see [issues labeled externs](https://github.com/tchapgouv/tchap-web-v4/issues?q=is%3Aopen+is%3Aissue+label%3Aexterns-externes+)
 - "Pas de partage du salon par lien" : there is a link that can be copied, but if you don't already have access to the room you cannot join it -> https://github.com/tchapgouv/tchap-web-v4/issues/612
 - "Liste rouge" : still not present on web -> https://github.com/tchapgouv/tchap-product/issues/296
 - "Annuaire des forums publics" : still sorted by homeserver -> https://github.com/tchapgouv/tchap-web-v4/issues/364

Some issues are probably outdated
 - issues are decrypting messages : FAQ will be most up to date for this
 - Invitation en masse : don't know why this feature is listed here, FAQ should have it
 
 Should we remove this "Known Issues" button completely ? Or leave it and update the wiki page to have only the current issues?

**Comment by estellecomment** [comment]
@Delphgateau @Nivann @Raphaelrobert65 if you have an opinion

**Comment by Delphgateau** [comment]
@estellecomment ok to leave it and update the wiki page.
Ex : https://aide.tchap.beta.gouv.fr/fr/article/mon-code-de-recuperation-est-refuse-b7suxq/
