### ISSUE TITLE
Investigate : should we use the "comment" section ?

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#95]
### Your use case

![image](https://user-images.githubusercontent.com/1238254/178462891-a5ceddbd-f449-4631-aee0-df8f99efed5d.png)
![image](https://user-images.githubusercontent.com/1238254/178462825-adb2f93b-33b2-42ad-a4a4-cd9ef56cf8ab.png)
 
We can personalize to get feedback or remove it if we can't personalize.

**Comment by estellecomment** [comment]
If this can be done simply, we can put it in the beta (having feedback in a beta is useful)
If it's too much work, we will do it after the beta (not having it does not block any of tchap's features)

**Comment by odelcroi** [comment]
The "comment" section has been connected to rageshake
