### ISSUE TITLE
Améliorer l'UX pour tchap annonce

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#955]
#### What would you like to do?
Changer le wording pour les tchap annonce (server notices)
La version actuelle affiche ça :

<img width="423" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/10048869/288fc350-55a7-4fed-858b-27c6f27440ed">

#### Why would you like to do it?
C'est pas un wording très compréhensible pour des annonces et notre utilisation

#### How would you like to achieve it?
TBD avec le produits :
- [ ] changer le menu Alerte Systemes en Annonces Tchap
- [ ] Mettre la section Tchap annonces en haut des autres rooms et DM?
- [x] https://github.com/tchapgouv/tchap-ios/issues/1000
- [x] https://github.com/tchapgouv/tchap-bizdev/issues/118

**Comment by yostyle** [comment]
On peut mettre "Annonces Tchap" comme vu lors du daliy

**Comment by MarcWadai** [comment]
@odelcroi est-ce qu'on fait le changement de bouger la section "Annonces Tchap" en haut des DMs ? (au plus de la barre latérale)

**Comment by odelcroi** [comment]
Le problème qu'on essaie de résoudre c'est de savoir si les gens vont "voir“ les messages du salon? 
- quels notifications sont disponibles pour ce salon?
- est ce qu'il va s'afficher dans un space?

Je pense qu'il est plus sage de continuer l'étude avant de proposer un "changement" si radical dans l'interface, qu'en penses tu @areox-net

**Comment by areox-net** [comment]
@odelcroi La position dans la liste des conversations me semble primordiale pour nous assurer que les users voyent le message.
A l'état actuel il sera tout en bas de la liste et tout user avec plus de 15 discussions risque de le louper sur Web.

Pour le wording, comme je disais dans le salon produit, je pense que le titre section est inutile. Le seul nom du salon devrait suffir à dire ce qu'il fait et à quoi ça sert. Une section serait utile uniquement si on pense avoir plusieurs salons de ce type.

**Comment by areox-net** [comment]
![Screenshot 2024-03-27 at 15 34 13](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/96e953fe-6ff2-4127-a498-38a4902f17e3)

**Comment by MarcWadai** [comment]
@odelcroi tu sais où en ai l'étude ? Est-ce qu'il y a eu des retours utilisateurs par rapport à la non visibilité de tchap annonces ? 
@areox-net Je suis d'accord avec toi, je pense qu'il est necessaire de bouger tchap annonce tout en haut de la liste. Par contre au niveau du code, il est compliqué de le sortir d'une section. il faudrait revoir toute la logique du code dans ce cas, je ne pense pas que ça vaut le coup niveau dev :/

**Comment by estellecomment** [comment]
@MarcWadai pour l'implementation, en modifiant OrderedDefaultTagIDs dans https://github.com/tchapgouv/tchap-web-v4/blob/develop_tchap_subtree/linked-dependencies/matrix-react-sdk/src/stores/room-list/models.ts, est-ce qu'on peut juste changer l'ordre ? (j'ai pas testé, ptet que c'est plus compliqué que ca :P)

Sinon on pourrait aussi faire notre propre composant séparé à ajouter, et supprimer le leur, si c'est plus facile...

**Comment by MarcWadai** [comment]
@estellecomment  oui je n'ai pas testé mais pour l'ordre ça doit être juste ça. 
Mais si on veut le sortir carrement de sa section et juste laisser le nom de la room, je pense qu'il vaut mieux rajouter notre composant a nous effectivement

**Comment by NicolasBuquet** [comment]
@MarcWadai @estellecomment 
Sur iOS, j'avais commencé à bouger la section en tête de liste puis regarder comment customiser l'affichage.

Finalement, après pas mal de recherche, j'ai découvert que les messages `serverNotice` étaient exclus de la requête de feed principal (les salons classiques).
J'ai plus eu qu'à ne pas les ignorer et à masquer la section "Tchap Annonces" pour que les ervernotices deviennent une room classique.

https://github.com/tchapgouv/tchap-ios/blob/619fdb0654f44d35882920f0d7aeb0929203cb45/Riot/Modules/Common/Recents/Service/MatrixSDK/RecentsListService.swift#L720

Il y a peut-être quelque chose de similaire possible côté web ?

**Comment by areox-net** [comment]
@MarcWadai Mon idée était de changer l'ordre des sections et cacher le titre de la section en CSS.

**Comment by estellecomment** [comment]
@areox-net C'est pas un peu spammy de mettre tchap-info coincé en haut? 
Il est là tout le temps et impossible à enlever. Il est même au dessus des favorites (par définition, "favorites" sert à naviguer rapidement parce qu'il est en haut).
Sachant que dans tchap info on va envoyer des messages importants (outages) mais aussi de la "pub" (actualités des nouvelles features, des trucs plutot moins primordiaux).


(ignorer le gros whitespace inutile pour le moment)
<img width="780" alt="Screen Shot 2024-04-09 at 12 17 05 PM" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/a6ff7f72-3a61-4fa8-b4b3-e5c7d6c047e6">



On pourrait ptet le mettre sous les Favorites ? 

Sur le fait que les utilisateurs ne le verront pas s'il est plus bas, il faut prendre en compte la notification : jusqu'a ce que tu aies lu le message, tu vas avoir un petit "1" rouge qui te nargue. Moi ca m'a fait chercher d'où il venait, et trouver "Alertes Systeme".
Donc je dirais qu'il le verront moins vite s'il est en bas, et que les gens qui ont des notifications dans tous les sens et qui les ignorent ne le verront pas (je me rends pas compte si c'est bcp de gens)

**Comment by areox-net** [comment]
@estellecomment idéalement il devrait remonter seulement quand il y a une notification. Mais faisons simple. 

En effets je pense que le mettre juste en bas des favoris peut être un bon compromis.
