### ISSUE TITLE
Study : how do we transition to mono-repo ?

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#958]
Can we build with the mono-repo ? 

Make the change, but allow ourselves to back out easily. 
 - keep patches.json up to date for new modifs (not necessary to generate the actual patch)

**Comment by MarcWadai** [comment]
Currently, studying the idea of submodule or subtree using our fork of matrix-react-sdk

**Comment by MarcWadai** [comment]
## Quelques avantages du mono-repo avec subtree d'un fork de matrix-react-sdk : 
- on ne maintient plus des patches mais un fork
- On ne maintient plus de scripts de patches fait maintien → on ne dépends plus non plus du package patch-package et de ses éventuelles changements
- La relecture de PR est plus simple
- Au niveau du mainlining c’est a peu près le même travail qu’auparavant, sauf qu’au lieu de s’occuper du merge de patches, on merge le fork.
- facilité d’ouverture de PR vers element grâce au format du fork

## Les commandes d'initialisation du mono-repo :
```
cd tchap-web-v4

// this will create a matrix-react-sdk-tchap directory in which it will pull the code from our fork
// we put the code in a new directory linked-dependencies, like this we keep the same level of relative path to the original yarn-linked-dependencies
git subtree add --prefix linked-dependencies/matrix-react-sdk https://github.com/tchapgouv/matrix-react-sdk-tchap develop_tchap --squash

// Change package.json
// remove postinstall patches script

// Remove dependencies on matrix sdk
yarn remove matrix-react-sdk

// change matrixreact-sdk dependencies to
// our fork is named matrix-react-sdk-tchap, so we use an alias in tchap-web in order to use only matrix-react-sdk as package name
yarn add matrix-react-sdk@"./linked-dependencies/matrix-react-sdk"


// remove previous link in case its still here
yarn unlink matrix-react-sdk

// rerun install to make the dependencies are correct
yarn install

// Fro now our fork doesnt contain codes from tchap, but is only a replicate of v3.95.0
// I am having trouble making a patch on the package since its not targeing the correct directory of my matric-react-sdk eventhough the one specify in the package.json is the local 
// So i applied the patches to the node_modules repo and copy paste the updated files to my linked-dependencies/matrix-react-sdk

Commit all the changes

// update the subtree remote
git subtree push --prefix linked-dependencies/matrix-react-sdk org-35118060@github.com:tchapgouv/matrix-react-sdk-tchap.git develop_tchap

```

## Les principaux changement dans le code
- Il n'y a plus l'utilisation de patches, donc on fait directment les changements dans le code subtree
- Ne pas oublier de temps en temps updater le upstream du subtree
- Le build webpack utilise le subtree au lieux du node_modules/matrix-react-sdk 
- Certains call en dur du chemin vers node_modules ont été modifié pour utiliser le subtree
- Si l'on veut ouvrir une PR vers element, il suffit de cherrypicker nos changement contre une nouvelle branche de notre fork avec comme base le upstream d'element. Ou s'il y a plusieurs commit, simplement les copier coller sur cette branche 

## Les principaux changements du workflow de dev par rapport a avant :
- Lors d'un upgrade, il faut d'abord upgrader la bonne version de matrix-react-sdk dans notre fork
- Plus besoin de merger et upgrader les patches
- Puis upgrader tchap-web sur la version d'element
- Enfin, pull les changements du subtree (avec la bonne version du sdk donc) dans tchap-web
