### ISSUE TITLE
Reword and styling for automatic response when geoloc is not activated

### ISSUE THREAD

**Issue by MarcWadai** [tchapgouv/tchap-web-v4#981]
The automatic response when sharing localisation when it's not available is cut by the avatar. 

![image](https://github.com/tchapgouv/tchap-web-v4/assets/10048869/2c59b85e-2fce-4bbc-bd8b-4e1a735db9d8)

## TODO
- [ ] reword the response to be friendlier
- [ ] Add the correct class css for the message

**Comment by odelcroi** [comment]
This message is displayed when the server map is not available, which
should not happen frequently hopefully.
I would either P3- or close this issue
