### ISSUE TITLE
When my account is expired, I cannot renew my account

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#986]
### Steps to reproduce

1. connect to Tchap Web with an account and open a room
2. set the account to be expired with a call to `{{url}}/_synapse/admin/v1/account_validity/validity`

#### What did you expect?
No button is working (request a renewal email or I renewed my account) on the popup
#### What happened instead?
![image](https://github.com/tchapgouv/tchap-web-v4/assets/3725676/9f79bc35-ffae-4fc2-a7f2-da471e4f0486)

#### What did you expect?
I expect the popup to appear
#### What happened instead?
<img width="1072" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/3725676/49218cf6-3228-4d2c-b02e-2226ab736ebf">

### Will you send logs?

Yes

**Comment by MarcWadai** [comment]
In version 4.5.0 there was a missing postinstall script, that didn't take into account our patch on the expired error. See this commit https://github.com/tchapgouv/tchap-web-v4/commit/ae77987110432e86da8f652edb7d134245ebb647
It will be fixed in next release 4.5.1
