### ISSUE TITLE
When in a voip call, sharing my screen interrupts the call (Chrome)

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#993]
### Steps to reproduce

1. call someone
2. share your screen

### Outcome
![image](https://github.com/tchapgouv/tchap-web-v4/assets/4077729/c9fb0d8c-14ad-4cdd-bdc5-abc73f297ce3)

### Operating system

MacOS

### Browser information

Version 124.0.6367.91 (Build officiel) (x86_64)

### Will you send logs?

No

**Comment by MarcWadai** [comment]
working on chrome version 125.0.64

**Comment by MarcWadai** [comment]
https://github.com/element-hq/element-web/issues/27373

**Comment by odelcroi** [comment]
does not work on my MacOs
Version 126.0.6478.56 (Build officiel) (x86_64)

**Comment by MarcWadai** [comment]
Configuration tested :

- Windows + chrome -> working since version >124 
- Linux + chrome -> working since version >124
- Mac + chrome -> not working with any version even >124

**Comment by MarcWadai** [comment]
This has been solved in element 1.11.69 ->  ~~to be tested~~ -> working
