### ISSUE TITLE
Changer l'image de fond des pages de connexion pour s'aligner à la DA de La Suite

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-web-v4#998]
### Your use case

Pour VivaTech la DINUM souhaite uniformiser les pages de connexion des outils de la suite.
Johann Giraud, DA de La Suite nous a fourni une image de fond à utiliser sur notre page de connexion.

<img width="2048" alt="im-bg-Tchap" src="https://github.com/tchapgouv/tchap-web-v4/assets/1255251/ce8318ce-cd90-4b89-b978-e86d973c11b7">

**Comment by MarcWadai** [comment]
@areox-net est-ce qu'il y a possibilité de compresser l'image un peu plus ou pas ? Là elle fait 9,8 Mb, ce qui est un peu gros :/

**Comment by areox-net** [comment]
@MarcWadai On peut faire mieux en effets

![im-bg-Tchap](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/8c6fcb80-9fb1-4b02-9112-86440df8d39e)
